$(function() {
	"use strict";

	// Some variables for later
	var dictionary, set_lang;
	var eng_lang = "english";
	var hindi_lang = "hindi";
	var current_lang = "";

	// Object literal behaving as multi-dictionary
	dictionary = {
		"english" : {
		
			"_indore_header": "Indore Smart Map",
			"_app_overview": "Application Overview",
			"_app_ov_homeScreen": "Home Screen",
			"_app_ov_loginScreen": "Login Screen",
			"_app_ov_cityMap": "City Map",
			"_app_ov_language": "Language",
			"_app_ov_mapTools": "Map Tools",
			"_app_ov_mt_globalSearch": "Global Search",
			"_app_ov_mt_zoomInOut": "Zoom In & Out",
			"_app_ov_mt_myLocation": "My Location",
			"_app_ov_mt_print": "Print",
			"_app_ov_mt_measurement": "Measurement",
			"_app_ov_mt_clearMap": "Clear Map",
			"_app_ov_mt_bookmark": "Bookmark",
			"_app_ov_mt_share": "Share",
			"_app_ov_menu": "Menu",
			"_app_ov_menu_baseMapGallery": "Base map Gallery",
			"_app_ov_menu_layers": "Layers",
			"_app_ov_menu_query": "Query",
			"_app_ov_menu_drawTool": "Draw Tool",
			"_app_ov_menu_aroundMe": "Around Me",
			"_app_ov_menu_events": "Events",
			"_app_ov_menu_wardInfo": "Ward Information",
			"_app_ov_menu_knowYourProperty": "Know Your Property",
			"_app_ov_menu_cityAnnouncements": "City Announcments",
			"_app_ov_menu_feedback": "Feedback and Suggestions",
			"_app_ov_menu_addData": "Add Data",
			"_app_ov_menu_fromToLocation": "From – To Location",
			"_app_ov_3dMap": "3D Map",
			"_help_for_citizen": "City Enterprise GIS Portal: For Citizens",
			"_use_city_gis": "Use City GIS Indore - Citizen Portal on your computer, phone, or tablet to explore and find more about your Smart City. Here's a guide to get you started using City GIS Indore Citizen Portal.",
			"_use_city_gis_note": "Note: Icons of all the functionalities are available on the menu bar at the left side of the portal.",
			"_home_screen_header": "Home Screen",
			"_home_screen_para1": "This is the landing page of the website. From home page you can get information about Indore city. ",
			"_home_screen_li1": "Click on “Login” button to login to the portal. It will redirect to Login page. ",
			"_home_screen_li2": "Click on “City GIS Map” button to go to City Map. ",
			"_home_screen_li3": "Click on Facebook, Instagram or Twitter icon to share the portal link on the social media.",
			"_home_screen_li4": "User can also click on Hindi or English to change the language of application.",
			"_home_screen_li5": "User can view the details of Heritage sites of Indore city with images.",
			"_login_screen_header": "Login Screen",
			"_login_screen_li1": "User can login with a valid username and password.",
			"_login_screen_li2": "If you forget your password click on Forgot Password link. ",
			"_login_screen_li3": "You can also sign up in the portal as citizen by clicking on “Sign Up” button.",
			"_city_map_header": "Smart Map",
			"_city_map_li1": "After login or clicking on City GIS map the map in 2D view will be shown.",
			"_language_header": "Language",
			"_language_li1": "User can select Hindi or English language from language selection from the right top corner.",
			"_language_li2": "If User selects Hindi, all information will be displayed in Hindi language only.",
			"_language_li3": "If user selects English language, all information will be displayed in English language only.",
			"_map_tools_header": "Map Tools",
			"_map_tools_globalSearch_header": "Global Search",
			"_map_tools_globalSearch_para1": "Search provides you with an opportunity to look up for features (e.g. Bus Stops, ATM, School, bank, government offices etc.) within a category and view their location on the map.",
			"_map_tools_globalSearch_li1": "Click on the down arrow on the search bar to select search category, type in the search term in the text box at the top left of the portal, as you type, you may see words begin to appear below the search box. These are auto-suggestions that may match what you’re interested in.",
			"_map_tools_globalSearch_li2": "As actual search result loads, click on the feature result to view location on the map and related information on the pop-up.",
			"_map_tools_zoomIn_header": "Zoom In",
			"_map_tools_zoomIn_para1": "Click on the Zoom in icon to view the map in detail. You can also use mouse scroll to zoom in to the map.",
			"_map_tools_zoomOut_header": "Zoom Out",
			"_map_tools_zoomOut_para1": "Click on the Zoom out icon to zoom out of the map. You can also use mouse scroll to zoom out to the map.",
			"_map_tools_home_header": "Home",
			"_map_tools_home_para1": "Click on the home icon to reset the map to its default extent. This function proves extremely helpful when you zoom in or out too much on the map and you can to return to your original landing page extent.",
			"_map_tools_myLocation_header": "My Location",
			"_map_tools_myLocation_para1": "On clicking the icon, a symbol displays on the map, showing your current location. The map extent is updated to show the current location as the area of interest.",
			"_map_tools_myLocation_para2": "The first time you visit Citizen Portal, you will have the option to allow or disallow the browser from sharing your location data. If you have denied the permission and would like to change the settings, follow the below steps to enable location sharing on your browser",
			"_map_tools_myLocation_chromeHeader": "Google Chrome",
			"_map_tools_myLocation_chromeli1": "Open Chrome.",
			"_map_tools_myLocation_chromeli2": "At the top right, click More and then Settings.",
			"_map_tools_myLocation_chromeli3": "At the bottom, click Advanced.",
			"_map_tools_myLocation_chromeli4": "Under \"Privacy and security,\" click Content settings.",
			"_map_tools_myLocation_chromeli5": "Click Location.",
			"_map_tools_myLocation_chromeli6": "Turn Ask before accessing on or off.",
			"_map_tools_myLocation_ieHeader": "IE",
			"_map_tools_myLocation_ieli1": "In Internet Explorer, click/tap on Tools (Menu bar or gear icon) and Internet Options.",
			"_map_tools_myLocation_ieli2": "Click/tap on the Privacy tab",
			"_map_tools_myLocation_ieli3": "To Allow Websites to Request Your Location, Uncheck the Never allow websites to request your physical location box, click/tap on OK.",
			"_map_tools_myLocation_ieli4": "Close and reopen Internet Explorer to apply.",
			"_map_tools_myLocation_firefoxHeader": "Firefox",
			"_map_tools_myLocation_firefoxli1": "Go to the Tools menu, and then select Page Info.",
			"_map_tools_myLocation_firefoxli2": "Select the Permissions tab.",
			"_map_tools_myLocation_firefoxli3": "Change the setting for Share Location.",
			"_map_tools_myLocation_note": "Current location is not supported in the Chrome via https due to Google’s privacy policy. Even in other browsers, the tool will only function when you let the website track your location.",
			"_map_tools_print_header": "Print",
			"_map_tools_print_para1": "Click on print to export and print files in PDF, PNG, JPG extensions. User can enter the title, file name and select page setup (A1 to A5), Orientation: Landscape/Portrait. User can include legends if required.",
			"_map_tools_measurement_header": "Measurement",
			"_map_tools_measurement_li1": "Click on the Measurement tool",
			"_map_tools_measurement_li2": "User can select this tool to measure any shape on the map. User can measure distance, area or find particular location of point by using this tool.",
			"_map_tools_measurement_li3": "User can also change the unit of measurement for Area, distance and location.",
			"_map_tools_measurement_li4": "To measure the length between any 2 points on the map; user can use the measure distance tool",
			"_map_tools_measurement_li5": "User can measure area by drawing a polygon on map by using Measure Area tool",
			"_map_tools_measurement_li6": "The find location tool under Measurement tool will let user find the location details of the selected point",
			"_map_tools_bookmark_header": "Bookmark",
			"_map_tools_bookmark_para1": "A spatial bookmark identifies a particular geographic location that you want to save and reference later. Bookmarks provide shortcuts to interesting places on a map. User can create a bookmark based on the current location and scale of the map. When other user clicks a bookmark, the map zooms to that location.",
			"_map_tools_bookmark_li1": "Click Bookmark icon from bottom left panel of the screen.",
			"_map_tools_bookmark_li2": "Zoom to the area on map which you frequently visit. For Example, if “Rajwada Palace” is one of your frequently mapped areas, search for it on map. Now, bookmark this map for later use.",
			"_map_tools_bookmark_li3": "Add name for the bookmark and click on ‘+’ to add the bookmark. For example, type ‘Rajwada Palace’ to successfully create the bookmark for Rajwada Palace area.",
			"_map_tools_bookmark_li4": "When done, you can come later and click on the Rajwada Palace Area bookmark to view the map zoomed to the map extent and scale saved",
			"_map_tools_bookmark_li5": "Select the bookmark you want to delete and click on delete button to remove it from the system",
			"_map_tools_bookmark_noteHeader": "Note",
			"_map_tools_bookmark_note": "The Guest User will not be able to save the bookmark in the system.",
			"_map_tools_share_header": "Share",
			"_map_tools_share_para1": "User can share the link of the Indore GIS Portal with others by sending an email, posting on social media or embed it on a web page.",
			"_map_tools_share_li1": "Click on the Share button, and choose an option for sharing it.",
			"_map_tools_share_li2": "Copy the short URL and paste it into an email, blog, or website.",
			"_map_tools_share_li3": "Embed the map in a website.",
			"_map_tools_share_li4": "Click the Gmail, Facebook and Twitter buttons in the Share pop-up.",
			"_map_tools_csb_header": "Custom Scale bar",
			"_map_tools_csb_li1": "User can set scale Custom Scale bar from minimum value 100 to maximum value 100000.",
			"_map_tools_clearMap_header": "Clear Map",
			"_map_tools_clearMap_para1": "Click on the clear map to clear the any displayed result on map.",
			"_map_tools_swipeLayer_header": "Swipe Layer",
			"_map_tools_swipeLayer_li1": "The Swipe widget enables users to easily compare the content of different layers in a map by sliding the swipe tool",
			"_map_tools_kyc_header": "Know Your Coordinates",
			"_map_tools_kyc_para1": "User can plot the point on map by using Know Your Coordinates Tool &amp; zoom to the desired location",
			"_map_tools_kyc_li1": "User can either select Current Location button or select Location By Map Click to plot a point.",
			"_map_tools_kyc_li2": "Click on Go To",
			"_map_tools_kyc_li3": "The point will be plotted and map will be zoomed to that location",
			"_menu_header": "Menu",
			"_menu_para1": "Menu will be on the left panel of the page & you can hide or show the menu. From menu you can navigate to different modules.",
			"_menu_basemap_header": "Basemap Gallery",
			"_menu_basemap_li1": "You can view and select different type of maps",
			"_menu_basemap_li2": "On selection of the map will be displayed on the screen",
			"_menu_basemap_li3": "Base map consists of ISCDL Drone Image 2020, ISCDL Satellite Image 2015, Dark grey canvas, Imagery, Imagery Hybrid, Light grey canvas, Navigation map, Oceans, Streets (Night), Street Map, Terrain with labels, Topographic world, No Base map.",
			"_menu_basemap_li4": "User can view any of the base map in one click.",
			"_menu_layers_header": "Layers",
			"_menu_layers_para1": "A group layer is collection of all features /facilities that fall within a category. You can select layer to view its related data to find out location(s) and information of particular features/facilities.",
			"_menu_layers_li1": "Click layers from left hand side menu bar of citizen portal.",
			"_menu_layers_li2": "On the widget you can view and expand all the group layer categories listed",
			"_menu_layers_li3": "By clicking the Layer, user can view list of layers such as: Building, Divider, Electric Pole, Street Light, Tree etc.",
			"_menu_layers_li4": "Layer will be visible on map by clicking on it from the layer panel.",
			"_menu_query_header": "Query",
			"_menu_query_para1": "Queries helps you identify and focus on finding relevant information regarding the layer.",
			"_menu_query_li1": "Click on query from Left menu bar of citizen portal.",
			"_menu_query_li2": "Select the ward from the drop down list",
			"_menu_query_li3": "Select Layer for which you want to apply query",
			"_menu_query_li4": "Mention the locality in which you want to search the query",
			"_menu_query_li5": "After clicking apply, the results will be displayed in the Result Tab",
			"_menu_query_li6": "On clicking on zoom to feature to any of the displayed result it will highlight and zoom on map",
			"_menu_query_li7": "By clicking clear result you can clear the results.",
			"_menu_drawTool_header": "Draw Tool",
			"_menu_drawTool_para1": "Select the type of draw mode you want to use from the Drawing tool.",
			"_menu_drawTool_li1": "Different types of draw mode are available such as Point, Line, Polyline, Triangle, Rectangle, Circle, Polygon, and Text.",
			"_menu_drawTool_li2": "For example, when you click on the Line string button, the tool activates the line geometry.",
			"_menu_drawTool_li3": "Move the mouse pointer over the map and click to add graphic/geometry on the map.",
			"_menu_drawTool_li4": "You can now view the graphic/geometry on the map, and also print this.",
			"_menu_drawTool_li5": "You can clear, undo and Redo from option available",
			"_menu_drawTool_noteHeader": "Note:",
			"_menu_drawTool_note": "Some graphics may require more than one click or a click and drag.",
			"_menu_aroundMe_header": "Around Me",
			"_menu_aroundMe_li1": "User can find out the nearby utilities by selecting any layer from the dropdown option.",
			"_menu_aroundMe_li2": "After selecting the layer user should click on the map to set the location & then set the nearby area range (km) to limit the search area.",
			"_menu_aroundMe_li3": "If user clicks outside the map then the error message will be displayed “Selected Location is outside Indore Boundary”.",
			"_menu_wardInfo_header": "Ward Information",
			"_menu_wardInfo_para1": "User can view the Ward Information of Indore City by clicking on Ward Information Tab.",
			"_menu_wardInfo_li1": "User has to select the Ward from the dropdown.",
			"_menu_wardInfo_li2": "The selected ward will be highlighted on map and following details can be viewed:",
			"_menu_wardInfo_li2_option1": "Corporator Details",
			"_menu_wardInfo_li2_option2": "Ward Details",
			"_menu_wardInfo_li2_option3": "Population",
			"_menu_wardInfo_li2_option4": "Educational Institute",
			"_menu_wardInfo_li2_option5": "Health Facilities",
			"_menu_wardInfo_li3": "User can also zoom in to any of the displayed health/education/hotels in their ward on",
			"_menu_kyp_header": "Know Your Property",
			"_menu_kyp_para1": "Citizens of Indore City can avail details about their property from this module.",
			"_menu_kyp_li1": "Click Know Your Property from the Menu Panel.",
			"_menu_kyp_li2": "On the widget select ward from the dropdown list and enter plot number or the Locality.",
			"_menu_kyp_li3": "Click on Search to view the results.",
			"_menu_kyp_li4": "The properties present in that locality will be shown in the Results Tab.",
			"_menu_kyp_li5": "Users can pay tax, electricity bill as well as view more details regarding their property from here.",
			"_menu_kyp_li6": "On clicking Zoom to Feature the map zooms to that particular location & the plot gets highlighted on the map.",
			"_menu_kyp_wardWise_header": "Ward Wise",
			"_menu_kyp_wardWise_li1": "Click on Ward Wise tab.",
			"_menu_kyp_wardWise_li2": "On the widget select ward from the dropdown list.",
			"_menu_kyp_wardWise_li3": "The properties present in that ward will be displayed in the Results Tab.",
			"_menu_kyp_wardWise_li4": "User can search for his property & pay tax, electricity bill as well as view more details regarding their property from here.",
			"_menu_kyp_wardWise_li5": "On clicking Zoom to Feature the map zooms to that particular location & the plot gets highlighted on the map.",
			"_menu_knowYourThana_header": "Know Your Police Thana",
			"_menu_knowYourThana_li1": "From the widget Select Location by plotting Latitude & Longitude on Map and then click on submit.",
			"_menu_knowYourThana_li2": "The Police Thana present in that location will be plotted on map and its details will be shown on the widget.",
			"_menu_citizenServices_header": "Citizen Services",
			"_menu_events_header": "Events",
			"_menu_events_para1": "User can add & view public event in Citizen Portal of Rajkot from Event Module.",
			"_menu_events_addEvent_header": "Add Event",
			"_menu_events_addEvent_li1": "Upon clicking this button, User can create an Event by entering details like “Event Name, Description, Venue, Start Date Time, End Date Time, Web Address, Entry Fees, Contact Person, Email ID, Contact Number, Organizer, Latitude, Longitude and can also Upload an attachment (If necessary)”.",
			"_menu_events_addEvent_li2": "By clicking on the submit button, It will be submitted to specific department for approval. Department Admin will check and verify the Event details.",
			"_menu_events_addEvent_li3": "After the approval of the Department Admin, It will be displayed on the map for public to view.",
			"_menu_events_viewEvents_header": "View Events",
			"_menu_events_viewEvents_li1": "Upon clicking this button, user can View Events by Selecting Duration from the dropdown list. User can search the event by selecting values from the dropdown like Today’s Event, Event in Next 7 days and Event in next 30 days.",
			"_menu_events_viewEvents_li2": "User can also share the event details with others via Share on WhatsApp facility.",
			"_menu_cityAnnouncement_header": "City Announcements",
			"_menu_cityAnnouncement_li1": "Any announcements made by authority for the citizens of Indore will be displayed on this menu. You can view the announcement details like Type of announcement, Announcement description, and Announcement date.",
			"_menu_cityAnnouncement_li2": "By clicking on Zoom to Announcement it will zoom the map to that location.",
			"_menu_fsc_header": "Feedback and Suggestions",
			"_menu_fsc_para1": "Help us make Indore City GIS citizen portal better by providing us your valuable feedback. Users can report problems or give us suggestions here. We’re always looking for ways to improve and would love to hear from you. Upon clicking this button, user can address a Grievance in the following ways:",
			"_menu_feedback_header": "Feedback",
			"_menu_feedback_li1": "User can give a feedback by entering “Name, Mobile Number, Email Address, Department from dropdown, Comment, Latitude and Longitude, Uploading file and Aadhar Photo”",
			"_menu_feedback_li2": "Select from Category that best fits your feedback (Sanitation, Road, Parks & Garden etc.).",
			"_menu_feedback_li3": "Add Comments and provide Personal Details.",
			"_menu_feedback_li4": "Click on the map to set location coordinates or get your current location for your Feedback.",
			"_menu_feedback_li5": "User can also attach the Photograph or documents to support your Feedback.",
			"_menu_feedback_li6": "Click Submit to send feedback to ISCDL.",
			"_menu_suggestion_header": "Suggestions",
			"_menu_suggestion_li1": "User can give a Suggestion by entering “Name, Mobile Number, Email Address, Department from dropdown, Comment, Latitude and Longitude, Uploading file and Aadhar Photo”",
			"_menu_suggestion_li2": "Select a Category that best fits your suggestion (Sanitation, Road, Parks & Garden etc.).",
			"_menu_suggestion_li3": "Add Comments and provide Personal Details.",
			"_menu_suggestion_li4": "Click on the map to set location coordinates or get your current location for your Suggestion.",
			"_menu_suggestion_li5": "User can also attach the Photograph or documents to support their Suggestions.",
			"_menu_suggestion_li6": "Click Submit to send suggestions to ISCDL.",
			"_menu_complaints_header": "Complaints",
			"_menu_complaints_li1": "User can make a Complaint by entering “Name, Mobile Number, Email Address, Department from dropdown, Comment, Latitude and Longitude, Uploading file and Aadhar Photo”",
			"_menu_complaints_li2": "Select the Category that best fits your complaint (Sanitation, Road, Parks & Garden etc.).",
			"_menu_complaints_li3": "Add Comments and provide Personal Details.",
			"_menu_complaints_li4": "Click on the map to set location coordinates or get your current location for your Complaint.",
			"_menu_complaints_li5": "User can also attach the Photograph or documents to support their Complaint.",
			"_menu_complaints_li6": "Click Submit to send complaint to ISCDL.",
			"_menu_fsc_noteHeader": "Note:",
			"_menu_fsc_note": "Only registered citizens will be able to submit feedback or suggestions. Be as specific as possible and include as much information as you can, so that we can serve you better.",
			"_menu_advancedTools_header": "Advance Tools",
			"_menu_addData_header": "Add Data",
			"_menu_addData_para1": "To add a new place which is not on map, Authorized user can click on add place from the menu.",
			"_menu_addData_li1": "Enter the Name",
			"_menu_addData_li2": "Select Image",
			"_menu_addData_li3": "Plot a location on map by clicking on pin icon",
			"_menu_addData_li4": "Enter remarks for the place.",
			"_menu_addData_li5": "Click on “Submit” button.",
			"_menu_addData_li6": "The added details will display on the map after the approval of specific department user. GIS cell will update the data on the map.",
			"_menu_addLayer_header": "Add Layer",
			"_menu_addLayer_li1": "User can add layers from “Add Layer” Module.",
			"_menu_addLayer_li2": "User can add shapefile by selecting zipped folder which contain valid file format (.shp, .shx etc.) or can add KML by selecting .kml or .kmz file format.",
			"_menu_addLayer_li3": "Click on Submit after selecting the file.",
			"_menu_addLayer_li4": "The added data will be plotted on map.",
			"_menu_addLayer_li5": "Other types of files are not allowed & system will pop up error if invalid file is uploaded.",
			"_menu_ftl_header": "From – To Location",
			"_menu_ftl_li1": "User can get directions between two locations by entering the Source and Destination.",
			"_menu_ftl_li2": "User can find the source & destination address by typing it in the auto complete box.",
			"_menu_ftl_li3": "Users can also “Set Source by Plotting Point” or “Set Current Location” with the help of Icons given in the box.",
			"_menu_ftl_li4": "On click of “Apply” it will show directions from source to destination on the map.",
			"_menu_help_header": "Help",
			"_menu_help_para1": "This page will show the information about how to use the portal.",
			"_3d_map_header": "3D Map",
			"_3d_map_li1": "After selecting “3D” on City GIS map the map in 3D view will be shown.",
			"_3d_map_li2": "3D Map consists of Main menu- Base Map Gallery, Layers Draw Tool, Heritage Building Tool and other map tools.",
			"_3d_mapTools_header": "Map Tools",
			"_3d_mapTools_para1": "All the map tools present in 2D Map are available in 3D Map. Some of the additional tools in 3D are as follows:",
			"_3d_mapTools_li1": "Toggle to Pan or Rotate in 3D",
			"_3d_mapTools_li2": "Reset Compass Orientation",
			"_3d_basemap_header": "Base Map Gallery",
			"_3d_basemap_li1": "User can view and select different type of maps",
			"_3d_basemap_li2": "On selection of the map will be displayed on the screen",
			"_3d_basemap_li3": "Base map consists of ISCDL Drone Image, ISCDL Satellite Image 2015, Dark grey canvas, Imagery, Imagery Hybrid, Light grey canvas, Navigation map, Oceans, Streets (Night), Street Map, Terrain with labels, Topographic world.",
			"_3d_basemap_li4": "User can view any of the base maps in one click.",
			"_3d_layers_header": "Layers",
			"_3d_layers_para1": "A group layer is collection of all features /facilities that fall within a category. You can select layer to view its related data to find out location(s) and information of particular features/facilities.",
			"_3d_layers_li1": "Click layers from left hand side menu bar of citizen portal.",
			"_3d_layers_li2": "On the widget you can view and expand all the group layer categories listed",
			"_3d_layers_li3": "By clicking the Layer, user can view list of layers such as: Building, Divider, Electric Pole, Street Light, Tree etc.",
			"_3d_layers_li4": "Layer will be visible on map by clicking on it from the layer panel.",
			"_3d_drawTool_header": "Draw Tool",
			"_3d_drawTool_para1": "You can get the drawing tool from the Menu in left panel of the Citizen Portal",
			"_3d_drawTool_li1": "Select the type of draw mode you want to use from the Drawing tool.",
			"_3d_drawTool_li2": "Different type of draw modes are available such as Point, Polyline and Polygon",
			"_3d_drawTool_li3": "For example, when you click on the Line string button, the tool activates the line geometry.",
			"_3d_drawTool_li4": "Move the mouse pointer over the map and click to add graphic/geometry on the map.",
			"_3d_drawTool_li5": "You can now view the graphic/geometry on the map, and also print this.",
			"_3d_drawTool_li6": "You can clear, undo and Redo from option available",
			"_3d_drawTool_noteHeader": "Note:",
			"_3d_drawTool_note": "Some graphics may require more than one click or a click and drag.",
			"_3d_heritage_header": "Heritage Building",
			"_3d_heritage_para1": "Users can view the list of heritage buildings present in Indore City.",
			"_3d_heritage_li1": "From the layer panel they can switch on/off any of the heritage building they wish to see",
			"_3d_heritage_li2": "Zoom to Feature will zoom to the particular heritage building",
			"_3d_heritage_li3": "User can also switch on the Drone Image to view as a base layer for the selected heritage building.",
			
			
		},
		"hindi" : {
			
			"_indore_header": "इंदौर स्मार्ट मैप",
			"_app_overview": "एप्लीकेशन अवलोकन",
			"_app_ov_homeScreen": "होम स्क्रीन",
			"_app_ov_loginScreen": "प्रवेश पट",
			"_app_ov_cityMap": "शहर का नक्शा",
			"_app_ov_language": "भाषा",
			"_app_ov_mapTools": "नक्शा उपकरण",
			"_app_ov_mt_globalSearch": "वैश्विक खोज",
			"_app_ov_mt_zoomInOut": "ज़ूम इन और आउट",
			"_app_ov_mt_myLocation": "माय लोकेशन",
			"_app_ov_mt_print": "प्रिंट",
			"_app_ov_mt_measurement": "माप",
			"_app_ov_mt_clearMap": "क्लियर मैप",
			"_app_ov_mt_bookmark": "बुकमार्क",
			"_app_ov_mt_share": "शेयर",
			"_app_ov_menu": "मेन्यू",
			"_app_ov_menu_baseMapGallery": "बेस मैप गैलरी",
			"_app_ov_menu_layers": "लेयर्स",
			"_app_ov_menu_query": "प्रश्न",
			"_app_ov_menu_drawTool": "ड्राइंग टूल",
			"_app_ov_menu_aroundMe": "मेरे आसपास",
			"_app_ov_menu_events": "आयोजन",
			"_app_ov_menu_wardInfo": "वार्ड की जानकारी",
			"_app_ov_menu_knowYourProperty": "अपनी संपत्ति को जानें",
			"_app_ov_menu_cityAnnouncements": "शहर की घोषणाएँ",
			"_app_ov_menu_feedback": "प्रतिक्रिया और सुझाव",
			"_app_ov_menu_addData": "डेटा जोड़ें",
			"_app_ov_menu_fromToLocation": "स्थान से - स्थान के लिए",
			"_app_ov_3dMap": "3डी नक्शा",
			"_help_for_citizen": "सिटी एंटरप्राइज जीआईएस पोर्टल: नागरिकों के लिए",
			"_use_city_gis": "अपने स्मार्ट सिटी के बारे में अधिक जानने और खोजने के लिए अपने कंप्यूटर, फोन या टैबलेट पर सिटी जीआईएस इंदौर सिटीजन पोर्टल का उपयोग करें। यहां आपको सिटी जीआईएस इंदौर सिटीजन पोर्टल का उपयोग शुरू करने के लिए एक गाइड दिया गया है।",
			"_use_city_gis_note": "नोट: सभी कार्यात्मकताओं के प्रतीक पोर्टल के बाईं ओर मेनू बार पर उपलब्ध हैं।",
			"_home_screen_header": "होम स्क्रीन",
			"_home_screen_para1": "यह वेबसाइट का लैंडिंग पेज है। होम पेज से आप इंदौर शहर के बारे में जानकारी प्राप्त कर सकते हैं।",
			"_home_screen_li1": "पोर्टल पर लॉगिन करने के लिए “लॉगिन” बटन पर क्लिक करें। यह लॉगिन पेज पर रीडायरेक्ट करेगा।",
			"_home_screen_li2": "सिटी मैप पर जाने के लिए \"सिटी जीआईएस मैप\" बटन पर क्लिक करें।",
			"_home_screen_li3": "सोशल मीडिया पर पोर्टल लिंक साझा करने के लिए फेसबुक, इंस्टाग्राम या ट्विटर आइकन पर क्लिक करें।",
			"_home_screen_li4": "उपयोगकर्ता आवेदन की भाषा बदलने के लिए हिंदी या अंग्रेजी पर भी क्लिक कर सकता है।",
			"_home_screen_li5": "उपयोगकर्ता छवियों के साथ इंदौर शहर के विरासत स्थलों का विवरण देख सकते हैं।",
			"_login_screen_header": "प्रवेश पट",
			"_login_screen_li1": "उपयोगकर्ता एक मान्य उपयोगकर्ता नाम और पासवर्ड के साथ लॉगिन कर सकता है।",
			"_login_screen_li2": "अगर आप अपना पासवर्ड भूल जाते हैं तो पासवर्ड भूल गए लिंक पर क्लिक करें।",
			"_login_screen_li3": "आप \"साइन अप\" बटन पर क्लिक करके नागरिक के रूप में पोर्टल में पंजीकरण कर सकते हैं।",
			"_city_map_header": "शहर का नक्शा",
			"_city_map_li1": "लॉगिन या सिटी जीआईएस मैप पर क्लिक करने के बाद 2डी व्यू में मैप दिखाई देगा।",
			"_language_header": "भाषा",
			"_language_li1": "उपयोगकर्ता ऊपरी दाएं कोने से भाषा चयन से हिन्दी या अंग्रेजी भाषा चुन सकते हैं।",
			"_language_li2": "यदि उपयोगकर्ता हिंदी का चयन करता है, तो सभी जानकारी हिंदी भाषा में ही प्रदर्शित की जाएगी।",
			"_language_li3": "यदि उपयोगकर्ता अंग्रेजी भाषा का चयन करता है, तो सभी जानकारी केवल अंग्रेजी भाषा में प्रदर्शित की जाएगी।",
			"_map_tools_header": "नक्शा उपकरण",
			"_map_tools_globalSearch_header": "वैश्विक खोज",
			"_map_tools_globalSearch_para1": "खोज आपको एक श्रेणी में सुविधाओं (उदाहरण के लिए बस स्टॉप, एटीएम, स्कूल, बैंक, सरकारी कार्यालय आदि) देखने का अवसर प्रदान करता है और मानचित्र पर उनका स्थान देखता है।",
			"_map_tools_globalSearch_li1": "खोज श्रेणी का चयन करने के लिए खोज बार पर डाउन एरो पर क्लिक करें, पोर्टल के शीर्ष पर पाठ बॉक्स में खोज शब्द लिखें, जैसा कि आप लिखते हैं, आप देख सकते हैं कि शब्द खोज बॉक्स के नीचे दिखाई देने लगते हैं। ये ऐसे ऑटो-सुझाव हैं जो आपकी रुचि के अनुरूप हो सकते हैं।",
			"_map_tools_globalSearch_li2": "वास्तविक खोज परिणाम लोड होने पर, मानचित्र पर स्थान और पॉप-अप पर संबंधित जानकारी देखने के लिए सुविधा परिणाम पर क्लिक करें।",
			"_map_tools_zoomIn_header": "ज़ूम इन",
			"_map_tools_zoomIn_para1": "मैप को विस्तार से देखने के लिए ज़ूम इन आइकन पर क्लिक करें। आप मैप को ज़ूम इन करने के लिए माउस स्क्रॉल का भी उपयोग कर सकते हैं।",
			"_map_tools_zoomOut_header": "ज़ूम आउट",
			"_map_tools_zoomOut_para1": "मैप से ज़ूम आउट करने के लिए ज़ूम आउट आइकन पर क्लिक करें। मैप को ज़ूम आउट करने के लिए आप माउस स्क्रॉल का भी उपयोग कर सकते हैं।",
			"_map_tools_home_header": "होम",
			"_map_tools_home_para1": "होम को उसकी डिफ़ॉल्ट सीमा तक रीसेट करने के लिए होम आइकन पर क्लिक करें। जब आप होम पर बहुत अधिक ज़ूम इन या आउट करते हैं तो यह फ़ंक्शन बेहद मददगार साबित होता है और आप अपने मूल लैंडिंग पृष्ठ पर वापस आ सकते हैं।",
			"_map_tools_myLocation_header": "माय लोकेशन",
			"_map_tools_myLocation_para1": "आइकन पर क्लिक करने पर, मैप पर एक प्रतीक प्रदर्शित होता है, जो आपके वर्तमान लोकेशन को दर्शाता है। मैप का स्थान वर्तमान लोकेशन को रुचि के क्षेत्र के रूप में दिखाने के लिए अद्यतन करता है।",
			"_map_tools_myLocation_para2": "पहली बार जब आप सिटीजन पोर्टल पर जाते हैं, तो आपके पास अपने स्थान डेटा को साझा करने से ब्राउज़र को अनुमति देने या अस्वीकार करने का विकल्प होगा। यदि आपने अनुमति से इनकार कर दिया है और सेटिंग्स बदलना चाहते हैं, तो अपने ब्राउज़र पर स्थान साझाकरण को सक्षम करने के लिए नीचे दिए गए चरणों का पालन करें:",
			"_map_tools_myLocation_chromeHeader": "गूगल क्रोम",
			"_map_tools_myLocation_chromeli1": "क्रोम खोलें।",
			"_map_tools_myLocation_chromeli2": "शीर्ष दाईं ओर, अधिक और फिर सेटिंग्स पर क्लिक करें।",
			"_map_tools_myLocation_chromeli3": "सबसे नीचे, उन्नत पर क्लिक करें।",
			"_map_tools_myLocation_chromeli4": "“गोपनीयता और सुरक्षा” के तहत, सामग्री सेटिंग पर क्लिक करें।",
			"_map_tools_myLocation_chromeli5": "स्थान पर क्लिक करें।",
			"_map_tools_myLocation_chromeli6": "चालू या बंद करने से पहले पूछें चालू करें।",
			"_map_tools_myLocation_ieHeader": "इंटरनेट एक्स्प्लोरर",
			"_map_tools_myLocation_ieli1": "इंटरनेट एक्सप्लोरर में, टूल (मेनू बार या गियर आइकन) और इंटरनेट विकल्प पर क्लिक / टैप करें।",
			"_map_tools_myLocation_ieli2": "प्राइवेसी टैब पर क्लिक / टैप करें",
			"_map_tools_myLocation_ieli3": "वेबसाइटों को आपके स्थान का अनुरोध करने की अनुमति देने के लिए, कभी भी वेबसाइटों को अपने भौतिक स्थान बॉक्स का अनुरोध करने की अनुमति न दें, ठीक पर क्लिक / टैप करें।",
			"_map_tools_myLocation_ieli4": "बंद करें और लागू करने के लिए इंटरनेट एक्सप्लोरर को फिर से खोलें।",
			"_map_tools_myLocation_firefoxHeader": "फ़ायरफ़ॉक्स",
			"_map_tools_myLocation_firefoxli1": "उपकरण मेनू पर जाएं, और फिर पृष्ठ जानकारी का चयन करें।",
			"_map_tools_myLocation_firefoxli2": "अनुमतियाँ टैब का चयन करें।",
			"_map_tools_myLocation_firefoxli3": "शेयर स्थान के लिए सेटिंग बदलें।",
			"_map_tools_myLocation_note": "Google की गोपनीयता नीति के कारण वर्तमान स्थान Chrome के माध्यम से Chrome में समर्थित नहीं है। अन्य ब्राउज़र में भी, टूल तभी कार्य करेगा जब आप वेबसाइट को अपना स्थान ट्रैक करने देंगे।",
			"_map_tools_print_header": "प्रिंट",
			"_map_tools_print_para1": "PDF, PNG, JPG एक्सटेंशन में फ़ाइलों को एक्सपोर्ट और प्रिंट करने के लिए प्रिंट पर क्लिक करें। उपयोगकर्ता शीर्षक, फ़ाइल नाम और पेज सेटअप A1 से A5, ओरिएंटेशन: लैंडस्केप / पोर्ट्रेट दर्ज कर सकता है। यदि आवश्यक हो तो उपयोगकर्ता लेजेंड्स को शामिल कर सकता है।",
			"_map_tools_measurement_header": "माप उपकरण",
			"_map_tools_measurement_li1": "मापन उपकरण पर क्लिक करें",
			"_map_tools_measurement_li2": "उपयोगकर्ता नक्शे पर किसी भी आकार को मापने के लिए इस उपकरण का चयन कर सकता है। उपयोगकर्ता इस उपकरण का उपयोग करके दूरी, क्षेत्र या बिंदु के विशेष स्थान को माप सकते हैं।",
			"_map_tools_measurement_li3": "उपयोगकर्ता क्षेत्र, दूरी और स्थान के लिए माप की इकाई को भी बदल सकता है।",
			"_map_tools_measurement_li4": "मानचित्र पर किसी भी 2 बिंदुओं के बीच की लंबाई को मापने के लिए; उपयोगकर्ता माप दूरी उपकरण का उपयोग कर सकते हैं।",
			"_map_tools_measurement_li5": "उपयोगकर्ता माप क्षेत्र उपकरण का उपयोग करके नक्शे पर बहुभुज खींचकर क्षेत्र को माप सकता है।",
			"_map_tools_measurement_li6": "माप उपकरण के तहत स्थान टूल ढूंढें उपयोगकर्ता को चयनित बिंदु के स्थान का विवरण मिलेगा।",
			"_map_tools_bookmark_header": "बुकमार्क",
			"_map_tools_bookmark_para1": "एक स्थानिक बुकमार्क एक विशेष भौगोलिक स्थान की पहचान करता है जिसे आप बाद में सहेजना और संदर्भित करना चाहते हैं। बुकमार्क नक्शे पर दिलचस्प स्थानों के लिए शॉर्टकट प्रदान करते हैं। उपयोगकर्ता मानचित्र के वर्तमान स्थान और पैमाने के आधार पर एक बुकमार्क बना सकता है। जब अन्य उपयोगकर्ता किसी बुकमार्क पर क्लिक करता है, तो मानचित्र उस स्थान पर पहुंच जाता है।",
			"_map_tools_bookmark_li1": "स्क्रीन के निचले बाएँ पैनल से बुकमार्क आइकन पर क्लिक करें।",
			"_map_tools_bookmark_li2": "उस क्षेत्र पर ज़ूम करें जो आप अक्सर आते हैं। उदाहरण के लिए, यदि \"राजवाड़ा पैलेस\" आपके अक्सर मैप किए गए क्षेत्रों में से एक है, तो इसे मैप पर खोजें। अब, बाद में उपयोग के लिए इस नक्शे को बुकमार्क करें।",
			"_map_tools_bookmark_li3": "बुकमार्क को नाम प्रदान करें और बुकमार्क जोड़ने के लिए + बटन पर क्लिक करें।",
			"_map_tools_bookmark_li4": "जब किया जाता है, तो आप बाद में आ सकते हैं और राजवाड़ा पैलेस क्षेत्र के बुकमार्क पर क्लिक करके मैप को ज़ूम करने के लिए मैप की सीमा और पैमाने पर ज़ूम करके देख सकते हैं",
			"_map_tools_bookmark_li5": "उस बुकमार्क को चुनें जिसे आप हटाना चाहते हैं और सिस्टम से बुकमार्क हटाने के लिए डिलीट बटन पर क्लिक करें।",
			"_map_tools_bookmark_noteHeader": "ध्यान दें",
			"_map_tools_bookmark_note": "अतिथि उपयोगकर्ता सिस्टम में बुकमार्क को सहेजने में सक्षम नहीं होगा।",
			"_map_tools_share_header": "शेयर",
			"_map_tools_share_para1": "उपयोगकर्ता इंदौर जीआईएस पोर्टल के लिंक को ईमेल भेजकर, सोशल मीडिया पर पोस्ट करके या वेब पेज पर एम्बेड करके साझा कर सकता है।",
			"_map_tools_share_li1": "शेयर बटन पर क्लिक करें, और इसे साझा करने के लिए एक विकल्प चुनें।",
			"_map_tools_share_li2": "शॉर्ट यूआरएल को कॉपी करें और ईमेल, ब्लॉग या वेबसाइट में पेस्ट करें।",
			"_map_tools_share_li3": "किसी वेबसाइट में नक्शा एम्बेड करें।",
			"_map_tools_share_li4": "शेयर पॉप-अप में जीमेल, फेसबुक और ट्विटर बटन पर क्लिक करें।",
			"_map_tools_csb_header": "कस्टम स्केल बार",
			"_map_tools_csb_li1": "उपयोगकर्ता न्यूनतम मान 100 से अधिकतम मूल्य 100000 तक कस्टम स्केल निर्धारित कर सकता है।",
			"_map_tools_clearMap_header": "क्लियर मैप",
			"_map_tools_clearMap_para1": "मैप पर प्रदर्शित किसी भी परिणाम को साफ़ करने के लिए स्पष्ट मानचित्र  क्लियर मैप पर क्लिक करें।",
			"_map_tools_swipeLayer_header": "स्वाइप लेयर",
			"_map_tools_swipeLayer_li1": "स्वाइप विजेट उपयोगकर्ताओं को आसानी से स्वाइप टूल को स्लाइड करके मैप में विभिन्न परतों की सामग्री की तुलना करने में सक्षम बनाता है।",
			"_map_tools_kyc_header": "अपने समन्वय को जानें",
			"_map_tools_kyc_para1": "उपयोगकर्ता अपने निर्देशांक उपकरण का उपयोग करके मानचित्र पर बिंदु को प्लॉट कर सकते हैं और इच्छित स्थान पर ज़ूम कर सकते हैं",
			"_map_tools_kyc_li1": "उपयोगकर्ता या तो वर्तमान स्थान बटन का चयन कर सकता है या बिंदु का चयन करने के लिए मानचित्र द्वारा स्थान का चयन कर सकता है।",
			"_map_tools_kyc_li2": "Go To पर क्लिक करें",
			"_map_tools_kyc_li3": "बिंदु को प्लॉट किया जाएगा और मानचित्र को उस स्थान पर ज़ूम किया जाएगा",
			"_menu_header": "मेन्यू",
			"_menu_para1": "मेनू पेज के बाएं पैनल पर होगा और आप मेनू को छिपा या दिखा सकते हैं। मेनू से आप विभिन्न मॉड्यूल पर नेविगेट कर सकते हैं।",
			"_menu_basemap_header": "बेस मैप गैलरी",
			"_menu_basemap_li1": "उपयोगकर्ता विभिन्न प्रकार के आधार मानचित्रों को देख और चुन सकता है।",
			"_menu_basemap_li2": "किसी भी आधार मानचित्र को चुनने पर इसे स्क्रीन पर प्रदर्शित किया जाएगा",
			"_menu_basemap_li3": "बेस मैप में ISCDL ड्रोन इमेज, ISCDL सैटेलाइट इमेज 2015, डार्क ग्रे कैनवास, इमेजरी, इमेजरी हाइब्रिड, लाइट ग्रे कैनवस, नेविगेशन मैप, ओसेन्स, स्ट्रीट्स (नाइट), स्ट्रीट मैप, टेरेन विद लेबल्स, टॉप वर्ल्ड शामिल हैं।",
			"_menu_basemap_li4": "उपयोगकर्ता किसी भी बेस मैप को एक क्लिक में देख सकता है।",
			"_menu_layers_header": "लेयर्स",
			"_menu_layers_para1": "एक समूह लेयर्स उन सभी सुविधाओं का संग्रह है जो किसी श्रेणी में आती हैं। स्थान (स्थानों) और विशेष सुविधाओं की जानकारी का पता लगाने के लिए आप इसके संबंधित डेटा को देखने के लिए लेयर्स का चयन कर सकते हैं।",
			"_menu_layers_li1": "नागरिक पोर्टल के बाएं हाथ की ओर मेनू बार से लेयर्स पर क्लिक करें।",
			"_menu_layers_li2": "विजेट पर आप सूचीबद्ध सभी समूह लेयर्स श्रेणियों को देख और विस्तारित कर सकते हैं",
			"_menu_layers_li3": "लेयर्स पर क्लिक करके, उपयोगकर्ता लेयर्स की सूची देख सकते हैं जैसे: बिल्डिंग, डिवाइडर, इलेक्ट्रिक पोल, स्ट्रीट लाइट, ट्री आदि।",
			"_menu_layers_li4": "लेयर पैनल से उस पर क्लिक करके लेयर दिखाई देगा।",
			"_menu_query_header": "प्रश्न",
			"_menu_query_para1": "क्वेरी आपको पहचानने और परत के संबंध में प्रासंगिक जानकारी खोजने पर ध्यान केंद्रित करने में मदद करती है।",
			"_menu_query_li1": "नागरिक पोर्टल के बाएँ मेनू बार से क्वेरी पर क्लिक करें।",
			"_menu_query_li2": "ड्रॉप डाउन सूची से वार्ड का चयन करें",
			"_menu_query_li3": "वह परत चुनें जिसके लिए आप क्वेरी लागू करना चाहते हैं",
			"_menu_query_li4": "उस इलाके का उल्लेख करें जिसमें आप क्वेरी खोजना चाहते हैं",
			"_menu_query_li5": "आवेदन पर क्लिक करने के बाद परिणाम प्रदर्शित किया जाएगा",
			"_menu_query_li6": "किसी भी प्रदर्शित परिणाम के लिए ज़ूम टू फीचर पर क्लिक करने पर यह फीचर को हाइलाइट करेगा और मैप पर ज़ूम करेगा",
			"_menu_query_li7": "क्लियर रिजल्ट पर क्लिक करके आप रिजल्ट क्लियर कर सकते हैं।",
			"_menu_drawTool_header": "ड्राइंग टूल",
			"_menu_drawTool_para1": "ड्रॉ मोड के प्रकार का चयन करें जिसे आप ड्राइंग टूल से उपयोग करना चाहते हैं।",
			"_menu_drawTool_li1": "विभिन्न प्रकार के ड्रा मोड उपलब्ध हैं जैसे कि बिंदु, पॉलीलाइन और बहुभुज",
			"_menu_drawTool_li2": "उदाहरण के लिए, जब आप लाइन स्ट्रिंग बटन पर क्लिक करते हैं, तो टूल लाइन ज्यामिति को सक्रिय करता है",
			"_menu_drawTool_li3": "मैप पर माउस पॉइंटर को मूव करें और मैप पर ग्राफिक / ज्योमेट्री जोड़ने के लिए क्लिक करें।",
			"_menu_drawTool_li4": "अब आप मानचित्र पर ग्राफिक / ज्यामिति देख सकते हैं, और इसे प्रिंट भी कर सकते हैं।",
			"_menu_drawTool_li5": "आप उपलब्ध विकल्प से स्पष्ट, पूर्ववत और फिर से कर सकते हैं",
			"_menu_drawTool_noteHeader": "नोट:",
			"_menu_drawTool_note": "कुछ ग्राफिक्स के लिए एक क्लिक या एक क्लिक और ड्रैग से अधिक की आवश्यकता हो सकती है।",
			"_menu_aroundMe_header": "मेरे आसपास",
			"_menu_aroundMe_li1": "उपयोगकर्ता ड्रॉपडाउन विकल्प से किसी भी परत का चयन करके पास की उपयोगिताओं का पता लगा सकता है।",
			"_menu_aroundMe_li2": "परत का चयन करने के बाद उपयोगकर्ता को स्थान निर्धारित करने के लिए मानचित्र पर क्लिक करना चाहिए और फिर खोज क्षेत्र को सीमित करने के लिए पास के क्षेत्र की सीमा (किमी) निर्धारित करनी चाहिए।",
			"_menu_aroundMe_li3": "यदि उपयोगकर्ता नक्शे के बाहर क्लिक करता है तो त्रुटि संदेश \"चयनित सीमा इंदौर सीमा के बाहर है\" प्रदर्शित होगा।",
			"_menu_wardInfo_header": "वार्ड की जानकारी",
			"_menu_wardInfo_para1": "उपयोगकर्ता इंदौर शहर के किसी भी वार्ड की जानकारी वार्ड सूचना टैब पर क्लिक करके देख सकते हैं।",
			"_menu_wardInfo_li1": "उपयोगकर्ता को ड्रॉपडाउन से वार्ड का चयन करना होगा।",
			"_menu_wardInfo_li2": "चयनित वार्ड को मानचित्र पर हाइलाइट किया जाएगा और निम्नलिखित विवरण देखे जा सकते हैं:",
			"_menu_wardInfo_li2_option1": "कॉर्पोरेटर का विवरण",
			"_menu_wardInfo_li2_option2": "वार्ड का विवरण",
			"_menu_wardInfo_li2_option3": "आबादी",
			"_menu_wardInfo_li2_option4": "शैक्षिक संस्थान",
			"_menu_wardInfo_li2_option5": "स्वास्थ्य सुविधाएं",
			"_menu_wardInfo_li3": "उपयोगकर्ता नक्शे में अपने वार्ड में प्रदर्शित स्वास्थ्य / शिक्षा / होटल में से किसी को भी ज़ूम कर सकते हैं",
			"_menu_kyp_header": "अपनी संपत्ति को जानें",
			"_menu_kyp_para1": "इंदौर शहर के नागरिक इस मॉड्यूल से अपनी संपत्ति के बारे में विवरण प्राप्त कर सकते हैं।",
			"_menu_kyp_li1": "मेनू पैनल से अपनी संपत्ति पता करें पर क्लिक करें।",
			"_menu_kyp_li2": "विजेट पर ड्रॉपडाउन सूची से वार्ड का चयन करें और प्लॉट नंबर या लोकलिटी दर्ज करें।",
			"_menu_kyp_li3": "परिणाम देखने के लिए खोज पर क्लिक करें।",
			"_menu_kyp_li4": "परिणाम टैब में उस इलाके में मौजूद संपत्ति दिखाए जाएंगे।",
			"_menu_kyp_li5": "उपयोगकर्ता कर, बिजली बिल के साथ-साथ अपनी संपत्ति के बारे में अधिक विवरण यहां से देख सकते हैं।",
			"_menu_kyp_li6": "ज़ूम टू फ़ीचर पर क्लिक करने पर उस स्थान पर मैप्स जूम हो जाते हैं और प्लॉट मैप पर हाइलाइट हो जाता है।",
			"_menu_kyp_wardWise_header": "वार्ड वार",
			"_menu_kyp_wardWise_li1": "वार्ड वार टैब पर क्लिक करें।",
			"_menu_kyp_wardWise_li2": "विजेट पर ड्रॉपडाउन सूची से वार्ड का चयन करें।",
			"_menu_kyp_wardWise_li3": "उस वार्ड में मौजूद गुण परिणाम टैब में प्रदर्शित किए जाएंगे।",
			"_menu_kyp_wardWise_li4": "उपयोगकर्ता अपनी संपत्ति की तलाश कर सकते हैं और कर, बिजली बिल का भुगतान कर सकते हैं और साथ ही यहां से उनकी संपत्ति के बारे में अधिक विवरण देख सकते हैं।",
			"_menu_kyp_wardWise_li5": "ज़ूम टू फ़ीचर पर क्लिक करने पर मानचित्र उस विशेष स्थान तक पहुँच जाता है और भूखंड मानचित्र पर हाइलाइट हो जाता है।",
			"_menu_knowYourThana_header": "अपने पुलिस थाना को जाने",
			"_menu_knowYourThana_li1": "विजेट से, उपयोगकर्ता को स्थान का चयन करने के लिए अक्षांश और देशांतर को प्लॉट करना होगा और फिर सबमिट पर क्लिक करना होगा।",
			"_menu_knowYourThana_li2": "उस स्थान पर मौजूद पुलिस थाने को मानचित्र पर प्लॉट किया जाएगा और उपयोगकर्ता विजेट पर इसके विवरण देख सकता है।",
			"_menu_citizenServices_header": "नागरिक सेवाएं",
			"_menu_events_header": "आयोजन",
			"_menu_events_para1": "उपयोगकर्ता इवेंट मॉड्यूल से इंदौर के सिटीजन पोर्टल में सार्वजनिक घटना को जोड़ और देख सकते हैं।",
			"_menu_events_addEvent_header": "कार्यक्रम जोड़ें",
			"_menu_events_addEvent_li1": "इस बटन पर क्लिक करने पर, उपयोगकर्ता ईवेंट नाम, विवरण, स्थान, प्रारंभ दिनांक समय, समाप्ति दिनांक समय, वेब पता, प्रवेश शुल्क, संपर्क व्यक्ति, ईमेल आईडी, संपर्क नंबर, आयोजक, अक्षांश, जैसे विवरण दर्ज करके एक ईवेंट बना सकते हैं। देशांतर और अनुलग्नक अपलोड कर सकते हैं ”।",
			"_menu_events_addEvent_li2": "सबमिट बटन पर क्लिक करके, इसे अनुमोदन के लिए विशिष्ट विभाग को प्रस्तुत किया जाएगा। विभाग व्यवस्थापक ईवेंट विवरण की जाँच और सत्यापन करेगा।",
			"_menu_events_addEvent_li3": "विभाग प्रशासक के अनुमोदन के बाद, इसे सार्वजनिक रूप से देखने के लिए मानचित्र पर प्रदर्शित किया जाएगा।",
			"_menu_events_viewEvents_header": "घटनाक्रम देखें",
			"_menu_events_viewEvents_li1": "इस बटन पर क्लिक करने पर, उपयोगकर्ता ड्रॉपडाउन सूची से अवधि का चयन करके घटनाक्रम देख सकता है। उपयोगकर्ता आज के ईवेंट, अगले 7 दिनों में ईवेंट, अगले 30 दिनों में ईवेंट और पिछले 7 दिनों में ईवेंट जैसे ड्रॉपडाउन से मानों का चयन करके ईवेंट खोज सकते हैं।",
			"_menu_events_viewEvents_li2": "उपयोगकर्ता व्हाट्सएप शेयर के माध्यम से घटना के विवरण को दूसरों के साथ साझा कर सकते हैं।",
			"_menu_cityAnnouncement_header": "शहर की घोषणाएँ",
			"_menu_cityAnnouncement_li1": "इंदौर के नागरिकों के लिए प्राधिकरण द्वारा की गई कोई भी घोषणा इस मेनू पर प्रदर्शित की जाएगी। आप घोषणा के प्रकार, घोषणा विवरण और घोषणा तिथि जैसे घोषणा विवरण देख सकते हैं।",
			"_menu_cityAnnouncement_li2": "ज़ूम टू अनाउंसमेंट पर क्लिक करके यह मैप को उस स्थान पर ज़ूम कर देगा।",
			"_menu_fsc_header": "प्रतिक्रिया और सुझाव",
			"_menu_fsc_para1": "हमें अपनी बहुमूल्य प्रतिक्रिया प्रदान करके इंदौर सिटी जीआईएस नागरिक पोर्टल को बेहतर बनाने में मदद करें। उपयोगकर्ता समस्याओं की रिपोर्ट कर सकते हैं या हमें यहाँ सुझाव दे सकते हैं। हम हमेशा सुधार के तरीके खोज रहे हैं और आपसे सुनना पसंद करेंगे। इस बटन पर क्लिक करने पर, उपयोगकर्ता निम्नलिखित तरीकों से एक शिकायत को संबोधित कर सकते हैं:",
			"_menu_feedback_header": "प्रतिपुष्टि",
			"_menu_feedback_li1": "उपयोगकर्ता \"नाम, मोबाइल नंबर, ईमेल पता, ड्रॉपडाउन से विभाग, टिप्पणी, अक्षांश और देशांतर, अपलोडिंग फ़ाइल और आधार फोटो\" दर्ज करके एक प्रतिक्रिया दे सकता है।",
			"_menu_feedback_li2": "वह श्रेणी चुनें जो आपकी प्रतिक्रिया (स्वच्छता, सड़क, पार्क और उद्यान आदि) के लिए सबसे उपयुक्त हो।",
			"_menu_feedback_li3": "टिप्पणियाँ जोड़ें और व्यक्तिगत विवरण प्रदान करें।",
			"_menu_feedback_li4": "स्थान निर्देशांक सेट करने के लिए मानचित्र पर क्लिक करें या अपनी प्रतिक्रिया के लिए अपना वर्तमान स्थान प्राप्त करें।",
			"_menu_feedback_li5": "उपयोगकर्ता आपकी प्रतिक्रिया का समर्थन करने के लिए फोटोग्राफ या दस्तावेज भी संलग्न कर सकता है।",
			"_menu_feedback_li6": "ISCDL पर प्रतिक्रिया भेजने के लिए सबमिट पर क्लिक करें।",
			"_menu_suggestion_header": "सुझाव",
			"_menu_suggestion_li1": "उपयोगकर्ता \"नाम, मोबाइल नंबर, ईमेल पता, ड्रॉपडाउन से विभाग, टिप्पणी, अक्षांश और देशांतर, अपलोडिंग फ़ाइल और आधार फोटो\" दर्ज करके एक सुझाव दे सकता है",
			"_menu_suggestion_li2": "एक श्रेणी का चयन करें जो आपके सुझाव (स्वच्छता, सड़क, पार्क और उद्यान आदि) के लिए सबसे उपयुक्त हो।",
			"_menu_suggestion_li3": "टिप्पणियाँ जोड़ें और व्यक्तिगत विवरण प्रदान करें।",
			"_menu_suggestion_li4": "स्थान निर्देशांक सेट करने के लिए मानचित्र पर क्लिक करें या अपने सुझाव के लिए अपना वर्तमान स्थान प्राप्त करें।",
			"_menu_suggestion_li5": "उपयोगकर्ता अपने सुझावों का समर्थन करने के लिए फोटोग्राफ या दस्तावेज भी संलग्न कर सकते हैं।",
			"_menu_suggestion_li6": "ISCDL को सुझाव भेजने के लिए सबमिट पर क्लिक करें।",
			"_menu_complaints_header": "शिकायतें",
			"_menu_complaints_li1": "उपयोगकर्ता \"नाम, मोबाइल नंबर, ईमेल पता, ड्रॉपडाउन से विभाग, टिप्पणी, अक्षांश और देशांतर, अपलोडिंग फ़ाइल और आधार फोटो\" दर्ज करके एक शिकायत कर सकते हैं",
			"_menu_complaints_li2": "वह श्रेणी चुनें जो आपकी शिकायत (स्वच्छता, सड़क, पार्क और उद्यान आदि) के लिए सबसे उपयुक्त हो।",
			"_menu_complaints_li3": "टिप्पणियाँ जोड़ें और व्यक्तिगत विवरण प्रदान करें।",
			"_menu_complaints_li4": "स्थान निर्देशांक सेट करने के लिए मानचित्र पर क्लिक करें या अपनी शिकायत के लिए अपना वर्तमान स्थान प्राप्त करें।",
			"_menu_complaints_li5": "उपयोगकर्ता अपनी शिकायत का समर्थन करने के लिए फोटोग्राफ या दस्तावेज भी संलग्न कर सकते हैं।",
			"_menu_complaints_li6": "ISCDL को शिकायत भेजने के लिए सबमिट पर क्लिक करें।",
			"_menu_fsc_noteHeader": "ध्यान दें:",
			"_menu_fsc_note": "केवल पंजीकृत नागरिक ही प्रतिक्रिया या सुझाव प्रस्तुत कर पाएंगे। जितना संभव हो उतना विशिष्ट बनें और इसमें जितनी जानकारी हो सके, शामिल करें, ताकि हम आपकी बेहतर सेवा कर सकें।",
			"_menu_advancedTools_header": "एडवांस टूल्स",
			"_menu_addData_header": "डेटा जोड़ें",
			"_menu_addData_para1": "एक नई जगह जोड़ने के लिए जो मानचित्र पर नहीं है, अधिकृत उपयोगकर्ता मेनू से ऐड प्लेस पर क्लिक कर सकता है।",
			"_menu_addData_li1": "नाम दर्ज करें",
			"_menu_addData_li2": "छवि चुने",
			"_menu_addData_li3": "पिन आइकन पर क्लिक करके मानचित्र पर एक स्थान प्लॉट करें",
			"_menu_addData_li4": "जगह के लिए टिप्पणी दर्ज करें।",
			"_menu_addData_li5": "“सबमिट” बटन पर क्लिक करें।",
			"_menu_addData_li6": "जोड़े गए विवरण विशिष्ट विभाग के उपयोगकर्ता के अनुमोदन के बाद मानचित्र पर प्रदर्शित होंगे। जीआईएस सेल मैप पर डेटा को अपडेट करेगा।",
			"_menu_addLayer_header": "परत जोड़ें",
			"_menu_addLayer_li1": "उपयोगकर्ता \"परत जोड़ें\" मॉड्यूल से परतें जोड़ सकते हैं।",
			"_menu_addLayer_li2": "उपयोगकर्ता ज़िप किए गए फ़ोल्डर का चयन करके आकार फ़ाइल जोड़ सकते हैं जिसमें मान्य फ़ाइल प्रारूप (.shp, .shx आदि) होते हैं या KML या .kmz फ़ाइल प्रारूप का चयन करके KML जोड़ सकते हैं।",
			"_menu_addLayer_li3": "फाइल सेलेक्ट करने के बाद Submit पर क्लिक करें।",
			"_menu_addLayer_li4": "जोड़े गए डेटा को मानचित्र पर प्लॉट किया जाएगा।",
			"_menu_addLayer_li5": "अन्य प्रकार की फ़ाइलों की अनुमति नहीं है और यदि अमान्य फ़ाइल अपलोड की गई है, तो सिस्टम त्रुटि उत्पन्न करेगा।",
			"_menu_ftl_header": "स्थान से - स्थान के लिए",
			"_menu_ftl_li1": "स्रोत और गंतव्य में प्रवेश करके उपयोगकर्ता दो स्थानों के बीच निर्देश प्राप्त कर सकते हैं।",
			"_menu_ftl_li2": "उपयोगकर्ता स्रोत और गंतव्य पते को स्वतः पूर्ण बॉक्स में लिखकर पा सकते हैं।",
			"_menu_ftl_li3": "उपयोगकर्ता बॉक्स में दिए गए आइकन्स की मदद से \"सेट सोर्स बाई प्लॉटिंग पॉइंट\" या \"करंट लोकेशन सेट करें\" भी कर सकते हैं।",
			"_menu_ftl_li4": "“लागू करें” पर क्लिक करने पर यह मानचित्र पर स्रोत से गंतव्य तक दिशाओं को दिखाएगा।",
			"_menu_help_header": "मदद",
			"_menu_help_para1": "यह पृष्ठ पोर्टल का उपयोग करने के तरीके के बारे में जानकारी दिखाएगा।",
			"_3d_map_header": "3डी नक्शा",
			"_3d_map_li1": "सिटी जीआईएस नक्शे पर \"3डी\" का चयन करने के बाद 3 डी दृश्य में नक्शा दिखाया जाएगा।",
			"_3d_map_li2": "3 डी मैप में मेन मेन्यू- बेस मैप गैलरी, लेयर्स ड्रॉ टूल, हेरिटेज बिल्डिंग टूल और अन्य मैप टूल्स शामिल हैं।",
			"_3d_mapTools_header": "मानचित्र उपकरण",
			"_3d_mapTools_para1": "2D मानचित्र में मौजूद सभी मानचित्र उपकरण 3D मानचित्र में उपलब्ध हैं। 3 डी में कुछ अतिरिक्त उपकरण इस प्रकार हैं:",
			"_3d_mapTools_li1": "पैन को टॉगल करें या 3 डी में घुमाएँ",
			"_3d_mapTools_li2": "कम्पास ओरिएंटेशन को रीसेट करें",
			"_3d_basemap_header": "बेस मैप गैलरी",
			"_3d_basemap_li1": "उपयोगकर्ता विभिन्न प्रकार के आधार मानचित्रों को देख और चुन सकता है।",
			"_3d_basemap_li2": "किसी भी आधार मानचित्र को चुनने पर इसे स्क्रीन पर प्रदर्शित किया जाएगा",
			"_3d_basemap_li3": "बेस मैप में ISCDL ड्रोन इमेज, ISCDL सैटेलाइट इमेज 2015, डार्क ग्रे कैनवास, इमेजरी, इमेजरी हाइब्रिड, लाइट ग्रे कैनवस, नेविगेशन मैप, ओसेन्स, स्ट्रीट्स (नाइट), स्ट्रीट मैप, टेरेन विद लेबल्स, टॉप वर्ल्ड शामिल हैं।",
			"_3d_basemap_li4": "उपयोगकर्ता किसी भी बेस मैप को एक क्लिक में देख सकता है।",
			"_3d_layers_header": "लेयर्स",
			"_3d_layers_para1": "एक समूह लेयर्स उन सभी सुविधाओं का संग्रह है जो किसी श्रेणी में आती हैं। स्थान (स्थानों) और विशेष सुविधाओं की जानकारी का पता लगाने के लिए आप इसके संबंधित डेटा को देखने के लिए लेयर्स का चयन कर सकते हैं।",
			"_3d_layers_li1": "नागरिक पोर्टल के बाएं हाथ की ओर मेनू बार से लेयर्स पर क्लिक करें।",
			"_3d_layers_li2": "विजेट पर आप सूचीबद्ध सभी समूह लेयर्स श्रेणियों को देख और विस्तारित कर सकते हैं",
			"_3d_layers_li3": "लेयर्स पर क्लिक करके, उपयोगकर्ता लेयर्स की सूची देख सकते हैं जैसे: बिल्डिंग, डिवाइडर, इलेक्ट्रिक पोल, स्ट्रीट लाइट, ट्री आदि।",
			"_3d_layers_li4": "लेयर पैनल से उस पर क्लिक करके लेयर दिखाई देगा।",
			"_3d_drawTool_header": "ड्राइंग टूल",
			"_3d_drawTool_para1": "आप नागरिक पोर्टल के बाएं पैनल में मेनू से ड्राइंग टूल प्राप्त कर सकते हैं",
			"_3d_drawTool_li1": "ड्रॉ मोड के प्रकार का चयन करें जिसे आप ड्राइंग टूल से उपयोग करना चाहते हैं।",
			"_3d_drawTool_li2": "विभिन्न प्रकार के ड्रा मोड उपलब्ध हैं जैसे कि बिंदु, पॉलीलाइन और बहुभुज",
			"_3d_drawTool_li3": "उदाहरण के लिए, जब आप लाइन स्ट्रिंग बटन पर क्लिक करते हैं, तो टूल लाइन ज्यामिति को सक्रिय करता है",
			"_3d_drawTool_li4": "मैप पर माउस पॉइंटर को मूव करें और मैप पर ग्राफिक / ज्योमेट्री जोड़ने के लिए क्लिक करें।",
			"_3d_drawTool_li5": "अब आप मानचित्र पर ग्राफिक / ज्यामिति देख सकते हैं, और इसे प्रिंट भी कर सकते हैं।",
			"_3d_drawTool_li6": "आप उपलब्ध विकल्प से स्पष्ट, पूर्ववत और फिर से कर सकते हैं",
			"_3d_drawTool_noteHeader": "नोट:",
			"_3d_drawTool_note": "कुछ ग्राफिक्स के लिए एक क्लिक या एक क्लिक और ड्रैग से अधिक की आवश्यकता हो सकती है।",
			"_3d_heritage_header": "हेरिटेज बिल्डिंग",
			"_3d_heritage_para1": "उपयोगकर्ता इंदौर शहर में मौजूद विरासत इमारतों की सूची देख सकते हैं।",
			"_3d_heritage_li1": "लेयर पैनल से वे जिस भी हेरिटेज बिल्डिंग को देखना चाहते हैं, उसे चालू / बंद कर सकते हैं",
			"_3d_heritage_li2": "ज़ूम टू फ़ीचर विशेष विरासत भवन में ज़ूम करेगा",
			"_3d_heritage_li3": "उपयोगकर्ता चयनित हेरिटेज बिल्डिंग के लिए बेस लेयर के रूप में देखने के लिए ड्रोन इमेज पर भी स्विच कर सकता है।",
			
			
		}
	};

	// set language according to type
	set_lang = function(language) {
		if (dictionary.hasOwnProperty(language)) {

			// $(".loader").fadeIn();

			$("[data-translate]").text(function() {
				var key = $(this).data("translate");
				if (dictionary.hasOwnProperty(language)) {
					if ($(this).is("input") || $(this).is("textarea")) {
						let value = dictionary[language][key];
						$(this).attr('placeholder', value)
					} else {
						let value = dictionary[language][key];
						$(this).text(value);
					}
				}
				// $(".loader").fadeOut();
			});
		}
	};

	/**
	 * Hindi language
	 */
	$("#pills-hindi-tab").click(function() {
		set_lang(hindi_lang);
		setCurrentLanguage(hindi_lang);
	});

	/**
	 * English language
	 */
	$("#pills-english-tab").click(function() {
		set_lang(eng_lang);
		setCurrentLanguage(eng_lang);
	});

	function setCurrentLanguage(language) {
		localStorage.setItem("current_language", language);
	}

	function configureLanguage() {

		var c_lang = localStorage.getItem("current_language");

		if (c_lang == null) {
			set_lang(eng_lang);
			setCurrentLanguage(eng_lang);
			$("#pills-tab #pills-hindi-tab").removeClass("active");
			$("#pills-tab #pills-english-tab").addClass("active");
		}

		if (c_lang == eng_lang) {
			$("#pills-tab #pills-hindi-tab").removeClass("active");
			$("#pills-tab #pills-english-tab").addClass("active");
		} else if (c_lang == hindi_lang) {
			$("#pills-tab #pills-english-tab").removeClass("active");
			$("#pills-tab #pills-hindi-tab").addClass("active");
		}
		set_lang(c_lang);
	}

	/**
	 * READY FUNCTION
	 */

	$(document).ready(function() {
		configureLanguage();
	});
});

