$(function() {
	"use strict";

	// Some variables for later
	var dictionary, set_lang;
	var eng_lang = "english";
	var hindi_lang = "hindi";
	var current_lang = "";

	// Object literal behaving as multi-dictionary
	dictionary = {
		"english" : {

			/**
			 * LOGIN PAGE
			 */
			
			"_indore_header": "Indore Smart Map",
			"_login" : "Login",
			"_city_gis" : "Smart Map",
			"_username" : "Username",
			"_password" : "Password",
			"_forgot_password" : "Forgot Password",
			"_enter_captcha" : "Enter Captcha",
			"_city_map" : "Smart Map",
			"_sign_up" : "Sign Up",
			"_change_password" : "Change Password",
			"_it_policy_heading": "IT Policy",
			"_it_policy_description1": "We do not collect personal information for any purpose other than to respond to you (for example, to respond to your queries ). If you choose to provide us with personal information like filling out a Contact Us form with an e-mail address or postal address, and submitting it to us through the website, we use that information to respond to your message, and to help you get the information you have requested.",
			"_it_policy_description2": "When you browse, read pages, or download information on this website, we automatically gather and store certain technical information about your visit. This information never identifies who you are. The information we collect and store about your visit is listed below:",
			"_it_policy_li1":"The Internet domain of your service provider (e.g. mtnl.net.in) and IP address (an IP address is a number that is automatically assigned to your computer whenever you are surfing the web) from which you access our website.",
			"_it_policy_li2":"The type of browser (such as Firefox, Netscape, or Internet Explorer) and operating system (Windows, Linux) used to access our site.",
			"_it_policy_li3":"The date and time you access/accessed our site.",
			"_it_policy_li4":"The pages/URLs you have visited, and",
			"_it_policy_li5":"If you reached this website from another website, the address of that referring website.",
			"_it_policy_description3":"This information is only used to help us make the site more useful for you. With this data, we learn about the number of visitors to our site and the types of technology our visitors use. We never track or record information about individuals and their visits.",
			"_it_policy_description4":"When you view our website, we may store some data on your computer in the form of a \"cookie\" to automatically recognize your PC next time you visit. Cookies can help us in many ways, for example, by allowing us to tailor a website to better match your interests or to store your password to save you having to re-enter it each time. If you do not wish to receive cookies, please configure your Internet browser to erase all cookies from your computer's hard drive, block all cookies or to receive a warning before a cookie is stored.",
			"_copyright_policy_heading": "Copyright Policy",
			"_copyright_policy_description": "Contents of this website may not be reproduced partially or fully, without due permission from Indore Smart City Development Limited. If referred to as a part of another website, the source must be appropriately acknowledged. The contents of this website cannot be used in any misleading or objectionable context.",
			"_tc_heading": "Terms & Conditions",
			"_tc_description1": "This website is designed, developed and maintained by Indore Smart City Development Limited and by accessing this website, you unconditionally accept to be legally bound by the terms and conditions.",
			"_tc_description2": "If you do not agree to the mentioned terms and conditions, please do not access the website.",
			"_tc_description3": "If you continue to browse and use this website you are agreeing to comply with and be bound by the following terms and conditions of use.",
			"_tc_description4": "We reserve the right to change these conditions from time to time without notice. You acknowledge and agree that it is your responsibility to review these Terms & Conditions periodically to familiarize yourself with any modifications. Your continued use of this site after such modifications will constitute acknowledgment and agreement of the modified terms and conditions.",
			"_tc_li1": "In order to access certain details, you may be required to provide some information about yourself (such as identification, email, phone number etc.) as part of the registration process, or as part of your ability to use the details. You agree that any information you provide will always be accurate, correct, and up to date.",
			"_tc_li2": "Attempting to copy, duplicate, reproduce, sell, trade, or resell our information is strictly prohibited.From time to time this website may also include links to other websites. These links are provided for your convenience to provide further information. They do not signify that we endorse the website(s). We have no responsibility for the content of the linked website(s).",
			"_tc_li3": "From time to time this website may also include links to other websites. These links are provided for your convenience to provide further information. They do not signify that we endorse the website(s). We have no responsibility for the content of the linked website(s).",
			"_tc_li4": "Efforts have been made to ensure the accuracy and currency of the content on this website; however, the same should not be interpreted as a statement of law or used for any legal purposes.",
			"_tc_li5": "In case of any ambiguity or doubts, users are advised to verify / check with the concerned Department(s) and / or other source(s), and obtain appropriate professional advice.",
			"_contact_us": "Contact Us",
			"_signup_email": "Email*",
			"_signup_name": "Name*",
			"_signup_contact": "Mobile No*",
			"_signup_address": "Address*",
			"_signup_zipcode": "Zipcode*",
			"_signup_city": "City*",
			"_signup_state": "State*",
			"_signup_terms": "I Accept All Terms & Conditions*",
			"_signup_readmore": "Read More",
			"_forgot_baktologin": "Back to Login",
			"_education": "Education",
			"_health": "Health",
			"_industrial": "Industrial",
			"_mppcb": "MPPCB",
			"_nic": "NIC",
			"_aictsl": "AICTSL",
			"_mpkvvcl": "MPKVVCL",
			"_police": "Police",
			"_tc_plannning": "T&C Planning",
			"_ida": "IDA",
			"_rto": "RTO",
			"_phe": "PHE",
			"_pwd": "PWD",
			"_wcwd": "WCWD",
			"_imc": "IMC",
			"_land_record": "Land Record",
			
			/**
			 * SIDE BAR/MAP
			 */
			"_find_address_or_place" : "Find address or place",
			"_basemap_gal" : "Basemap Gallery",
			"_layers" : "Layers",
			"_query" : "Query",
			"_draw" : "Draw",
			"_imc_services" : "IMC Services",
			"_around_me" : "Around Me",
			"_events" : "Events",
			"_ward_information" : "Ward Information",
			"_know_your_property" : "Know Your Property",
			"_authority_announcement" : "City Announcements",
			"_feedback_and_suggestion" : "Feedback & Suggestion",
			"_add_data" : "Add Data",
			"_from_location_to_location" : "Direction",
			
			"llist_layers" : "Layers",
			"llist_legend" : "Legend",
			"llist_opacity" : "Opacity",
			"opacity_by_individual_layer" : "Opacity By Individual Layer",
			"llist_ltransparency" : "All Visible Layer Transparency",
			"llist_transparent" : "Transparent",
			
			"_home" : "Home",
			"_find_my_location" : "Find My Location",
			"_print" : "Print",
			"_measurement" : "Measurement",
			"_bookmark" : "Bookmark",
			"_share" : "Share",
			"_clear_map" : "Clear Map",
			"_dark_gray_canvas" : "Dark Gray Canvas",
			"_imagery" : "Imagery",
			"_imagery_hybrid" : "Imagery Hybrid",
			"_light_gray_canvas" : "Light Gray Canvas",
			"_navigation_map" : "Navigation Map",
			"_oceans" : "Oceans",
			"_streets_night" : "Streets (Night)",
			"_streets_map" : "Streets Map",
			"_topographic" : "Topographic",
			"_task" : "Task",
			"_locate" : "Locate",
			"_result" : "Result",
			"_select_ward" : "Select Ward",
			"_execute" : "Execute",
			"_select_draw_mode" : "Select Draw Mode",
			"_pollution_details" : "Pollution Details",
			"_avls_details" : "AVLS Details",
			"_pollution_level" : "Pollution Level",
			"_select_details" : "Select Details",
			"_set_nearby_area" : "Set Nearby Area",
			"_select_layer" : "Select Layer",
			"_view_event" : "View Event",
			"_add_event" : "Add Event",
			"_select_duration" : "Select Duration",
			"_select_department" : "Select Department",
			"_event_name" : "Event Name",
			"_description" : "Description",
			"_venue" : "Venue",
			"_date" : "Date",
			"_web_address" : "Web Address",
			"_entry_fee" : "Entry Fee",
			"_conatct_person" : "Contact Person",
			"_email_id" : "Email Id",
			"_conatct_number" : "Contact Number",
			"_organizer" : "Organizer",
			"_latitude" : "Latitude",
			"_longitude" : "Longitude",
			"_goto_longitude" : "Longitude (X)",
			"_goto_latitude": "Latitude (Y)",
			"_upload_file" : "Upload File",
			"_submit" : "Submit",
			"_clear" : "Clear",
			"_choose_file" : "Choose File",
			"_corporator_details" : "Corporator Details",
			"_ward_details" : "Ward Details",
			"_zone_details" : "Zone Details",
			"_officers" : "Officers",
			"_population" : "Population",
			"_educational_institute" : "Educational Institute",
			"_health_facilities" : "Health Facilities",
			"_hotel_and_entertainment" : "Hotel & Entertainment",
			"_name" : "Name",
			"_ward_name" : "Ward Name",
			"_zone_name" : "Zone Name",
			"_zone_no" : "Zone No",
			"_health_officer" : "Health Officer",
			"_inspector" : "Inspector",
			"_total_population" : "Total Population",
			"_gender" : "Gender",
			"_schools" : "Schools",
			"_colleges" : "Colleges",
			"_institutes" : "Institutes",
			"_hospital" : "Hospital",
			"_dispensary" : "Dispensary",
			"_clinics" : "Clinics",
			"_hotels" : "Hotels",
			"_restaurants" : "Restaurants",
			"_know_your_location" : "Know Your Location",
			"_id" : "Id",
			"_mobile_number" : "Mobile Number",
			"_address" : "Address",
			"_feedback" : "Feedback",
			"_suggestion" : "Suggestion",
			"_complaint" : "Complaint",
			"_category" : "Category",
			"_comment" : "Comment",
			"_city" : "City",
			"_pincode" : "Pincode",
			"_select_image" : "Select Image",
			"_no_file_chosen" : "No File Chosen",
			"_remark" : "Remark",
			"_note_for_from_to_location" : "Note: To get direction please set from & to location and please click on Map",
			"_to_location" : "To Location",
			"_from_location" : "From Location",
			"_enter_from_location" : "Enter From Location",
			"_enter_to_location" : "To From Location",
			"_select_location" : "Select Location",
			
			"_from_location_by_name" : "From Location By Name",
			"_to_location_by_name" : "To Location By Name",
			
			"_apply" : "Apply",
			"_clear_location" : "Clear Location",
			"_login_content" : "Indore is most populous and the largest city of Madhya Pradesh and the district headquarters of Indore District. Indore is one of the cities that were selected in the first top 20 Smart cities Indore Smart City is emerging as an urban ecosystem that aims to integrate digital technology, knowledge and assets, to become more responsive to citizens, improve city services, and make the city more loveable than it already is. Indore Smart city GIS Platform not only makes government data more accessible for the public but also provide the complete geospatial information of various point of interest(POI’s) which will help the city administration and public as well .",

			"_draw_preview" : "Preview",
			"_draw_strok_color" : "Stroke Color",
			"_draw_border_width" : "Border Width",
			"_draw_fill_color" : "Fill Color",
			"_draw_color" : "Color",
			"_draw_line_width" : "Line Width",
			"_draw_text" : "Text",
			"_draw_font_color" : "Font Color",
			"_draw_font_size" : "Font Size",

			// "_imc_iswm" : "ISWM",
			"imc_smart_led" : "Smart LED",
			"imc_ptax" : "Property Tax",
			"imc_pid" : "Plot ID",
			"imc_bid" : "Building ID",
			"imc_landmark" : "Landmark",
			"_imc_from_date":"From Date",
			"_imc_to_date":"To Date",
			"search" : "Search",

			"_around_note" : "Note: After Selection of layer and distance, Please click on map",

			"kyp_note" : "Note: To view the property details, Performed the identifier operation on the plot point.",
			"kyp_by_ward" : "Ward Wise",
			"kyp_locality" : "Locality/Area Name",
			"select_locality_thana": "Select Locality",
			"kyp_or" : "Or",
			"kyp_oR" : "OR",

			/*******************************************************************
			 * BOTTOM BAR
			 */

			"_print_ptitle" : "Title Name",
			"_print_etitle" : "Enter Title",
			"_print_playout" : "Layout",
			"_print_pformat" : "Format",
			"_print_gprintout" : "Get Printout",

			"bmark_addbmark" : "Add Bookmark",
			"bmark_dbmark" : "Delete",

			"_share_title" : "Share a link to this app",
			"_share_linkop" : "Link Option",
			
			"_swipe_layer" : "Swipe Layer",
			"_swipe" : "Swipe",
			
			/*
			 * Department Portal
			 */

			"head_announce" : "Announcement",
			"head_umanagement" : "User Management",
			"head_cmasterdata" : "Citizen Master Data",
			"head_masterdata" : "Master Data",
			"head_adddata" : "Add Data",
			"head_pmonitoring" : "Project Monitoring",
			"head_palerts" : "Project Alerts",
			"head_emanagement" : "Event Management",
			"head_fsuggestions" : "Feedback & Suggestions",
			"head_reports" : "Reports",

			"_query_basic" : "Basic Query",
			"_query_advanced" : "Advanced Query",
			"_query_spatial" : "Spatial Query",
			"_query_result" : "Result",
			"_query_department" : "Department",
			"_query_sdepartment" : "Select Department",
			"_query_ward" : "Ward",
			"_query_sward" : "Select Ward",
			"_query_layer" : "Layer",
			"_query_slayer" : "Select Layer",
			"_query_field" : "Field",
			"_query_sfield" : "Select Field",
			"_query_value" : "Value",
			"_query_evalue" : "Enter Value",
			"_query_logical_op" : "Logical Operator",
			"_query_operator" : "Select Operator",

			"squery_slayer" : "Source Layer",
			"squery_qtype" : "Query Type",
			"squery_mlayer" : "Mask Layer",

			"_ann_add_announcement" : "Add Announcement",
			"_ann_view_announcement" : "View Announcement",
			"ann_type_announcement" : "Type Of Announcement",
			"ann_title_announcement" : "Announcement Title",
			"ann_etitle_announcement" : "Enter Title",
			"ann_description_announcement" : "Announcement Description",
			"ann_data_time" : "Announcement Date & time",
			"ann_date" : "Announcement Date",

			"umanagement_dmaster" : "Department Master",
			"umanagement_rmaster" : "Role Master",
			"umanagement_umaster" : "User Master",
			"umanagement_l_dmaster" : "List of Department Master",
			"umanagement_add_department" : "Add Department",
			"umanagement_dname" : "Department Name",
			"umanagement_edepartment" : "Enter Department",
			"umanagement_created_by" : "Created By",
			"umanagement_enter_name" : "Enter Name",
			"umanagement_description" : "Description",
			"umanagement_add_description_here" : "Add Description Here",
			"umanagement_sstatus" : "Select Status",
			"umanagement_u_department" : "Update Department",

			"umanagement_role_add_role" : "Add Role",
			"umanagement_role_lrole_master" : "List of Role Master",
			"umanagement_role_sdepatrment" : "Select Department",
			"umanagement_role_rname" : "Role Name",
			"umanagement_role_erolename" : "Enter Role Name",
			"umanagement_role_webapp" : " Web Application",
			"umanagement_role_mobapp" : "Mobile Application",
			"umanagement_role_sroletype" : "Select Role Type",

			"umnanagement_user_adduser" : "Add User",
			"umnanagement_user_list_user" : "List of User",
			"umnanagement_user_name" : "Name",
			"umnanagement_user_ename" : "Enter Name",
			"umnanagement_user_email" : "Email",
			"umnanagement_user_eemail" : "Enter email Id",
			"umnanagement_user_password" : "Password",
			"umnanagement_user_epassword" : "Enter Password",
			"umnanagement_user_mnumber" : "Mobile Number",
			"umnanagement_user_emnumber" : "Enter Mobile Number",
			"umnanagement_user_sdepartment" : "Select Department",
			"umnanagement_user_srole" : "Select Role",

			"cmdata_cmaster" : "Citizen Master",
			"cmdata_lcmaster" : "List of Citizen Master",

			"fsc_t_feedback" : "Feedback",
			"fsc_t_suggestion" : "Suggestions",
			"fsc_t_complaint" : "Complaint",
			"fsc_lfeedback" : "List of Feedback",
			"fsc_lsuggestion" : "List of Suggestions",
			"fsc_lcomplaint" : "List of Complaint",

			"report_greport" : "Get Report",

			"master_data_get" : "Get Master Data",

			"event_events" : "Events",
			"events_levents" : "List of Events",
			"events_addevent" : "Add Event",
			"events_ename" : "Event Name",
			"events_eename" : "Enter Event Name",
			"events_desc" : "Description",
			"events_venue" : "Venue",
			"events_evenue" : "Enter Venue",
			"events_date" : "Date & Time",
			"events_webaddress" : "Web Address",
			"events_ewebaddress" : "Enter Web Address",
			"events_entree_fee" : "Entry Fee",
			"events_eentree_fee" : "Enter Entry Fee",
			"events_contact_person" : "Enter Contact Person",
			"events_e_contact_person" : "Enter Contact Person",
			"events_email_id" : "Email Id",
			"events_eemail_id" : "Enter Email Id",
			"events_cnumber" : "Contact Number",
			"events_ecumber" : "Enter Contact Number",
			"events_organizer" : "Organizer",
			"events_eorganizer" : "Enter Organizer",
			"events_upload_file" : "Upload File",
			"events_edit" : "Edit Event",

			"pm_manage_project" : "Manage Project",
			"pm_project_reports" : "Project Reports",
			"pm_projects_projects" : "Projects",
			"pm_projects_add_project" : "Add Project",
			"pm_projects_location" : "Location",
			"pm_projects_binfo" : "Basic Info",
			"pm_projects_finance" : "Finance",
			"pm_projects_assign_users" : "Assign Users",
			"pm_projects_imagedocs" : "Images & Docs",
			"pm_projects_location_lname" : "Project Location",
			"pm_projects_location_elocation" : "Enter Project Location",
			"pm_projects_location_lat" : "Latitude",
			"pm_projectslocation_elat" : "Enter Latitude",
			"pm_projects_location_long" : "Longitude",
			"pm_projects_location_elong" : "Enter Longitude",
			"pm_projects_location_tehsil" : "Tehsil",
			"pm_projectslocation_ward" : "Ward No",
			"pm_projects_location_district" : "District",
			"pm_projects_location_village" : "Village",
			"pm_projects_location_zone" : "Zone No",
			"pm_projects_location_ward_name" : "Ward Name",
			"pm_projects_location_zone_name" : "Zone Name",
			"pm_projects_expected_start_date" : "Expected Start Date",
			"pm_projects_expected_completion_date" : "Expected Completion Date",
			"pm_projects_type" : "Project Type",

			"pm_projects_binfo_pname" : "Project Name",
			"pm_projects_binfo_epname" : "Enter Project Name",
			"pm_projects_binfo_cnumber" : "Mobile Number",
			"pm_projects_binfo_ecnumber" : "Enter Mobile Number",
			"pm_projects_binfo_cemail": "Contractor Email Id",
			"pm_projects_binfo_ecemail": "Enter Contractor Email Id",
			"pm_projects_binfo_wperiod" : "Work Order Period",
			"pm_projects_binfo_ewperiod" : "Enter Work Order Period",
			"pm_projects_binfo_sdate" : "Project Start Date",
			"pm_projects_binfo_ssdate" : "Select Date",
			"pm_projects_binfo_consultantname" : "Design Consultant Name",
			"pm_projects_binfo_econsultantname" : "Enter Design Consultant Name",
			"pm_projects_binfo_pprogress" : "Physical Progress (%)",
			"pm_projects_binfo_epprogress" : "Enter Physical Progress",
			"pm_projects_binfo_remarks" : "Remarks",
			"pm_projects_binfo_eremarks" : "Enter Remarks",
			"pm_projects_binfo_cname" : "Contractor Name",
			"pm_projects_binfo_ecname" : "Enter Contractor Name",
			"pm_projects_binfo_cagency" : "Contractor Agency",
			"pm_projects_binfo_ecagency" : "Enter Contractor Agency",
			"pm_projects_binfo_workorderno" : "Work Order No",
			"pm_projects_binfo_eworkorderno" : "Enter Work Order No.",
			"pm_projects_binfo_edate" : "Project Completion Date",
			"pm_projects_binfo_eedate" : "Select Date",
			"pm_projects_binfo_consultannumber" : "Design Consultant Contact Number",
			"pm_projects_binfo_ecunsultantnumber" : "Enter Design Consultant Contact No.",
			"pm_projects_binfo_cperiod" : "Contract Period",
			"pm_projects_binfo_ecperiod" : "Enter Contract Period",
			"pm_projects_binfo_pstatus" : "Project Status",

			"pm_projects_finance_pfc" : "Project Total Cost",
			"pm_projects_finance_epfc" : "Enter Project Total Cost",
			"pm_projects_finance_pbd" : "Performance Bank Date",
			"pm_projects_finance_spbd" : "Select Performance Bank Date",
			"pm_projects_finance_pbg" : "Performance Bank Guarantee",
			"pm_projects_finance_epbg" : "Enter Performance Bank Guarantee",
			"pm_projects_finance_fp" : "Financial Progress (%)",
			"pm_projects_finance_efp" : "Enter Financial Progress",
			
			"pm_projects_allotted_to": "Project Allotted To",
			"pm_projects_allotted_to_contactNo": "Contact Number",
			"pm_projects_allotted_to_name": "Name",
			"pm_projects_allotted_to_email": "Email Id",

			"pm_projects_img_imgs" : "Images",
			"pm_projects_img_uimage" : "Upload Images",
			"pm_projects_img_docs" : "Documents",
			"pm_projects_img_udocs" : "Upload Documents",

			"pm_projects_milestones" : "Milestones",
			"pm_miles_select_pro" : "Select Project",
			"pm_miles_add_milestone" : "Add Milestone",
			"pm_miles_update_milestone" : "Update Milestone",
			"pm_miles_mname" : "Milestone Name",
			"pm_miles_description" : "Description",
			"pm_miles_startdate" : "Start Date",
			"pm_miles_enddate" : "End Date",
			"pm_miles_image" : "Image",
			"pm_miles_document" : "Document",
			"pm_miles_mstatus" : "Milestone Status",
			"pm_miles_remarks" : "Remarks",
			"pm_miles_emname" : "Enter Milestone Name",
			"pm_miles_add_desc" : "Add Description Here",
			"pm_miles_add_remarks" : "Add Remarks Here",

			"_x_y_coordinates" : "Know Your Coordinates",
			"_go_to" : "Go To",
			
			"_buffer_polygon_buf" : "Polygon Buffer",
			"_buffer_direction" : "Direction",
			"_buffer_draw_polygon" : "Draw Polygon",
			"_buffer_sslocation" : "Select Source Location",
			"_buffer_sdlocation" : "Select Destination Location",
			"_buffer_slocation" : "Source Location",
			"_buffer_dlocation" : "Destination Location",
			"_buffer_gdirection" : "Get Direction",
			"_buffer" : "Buffer",
			
			"_generate_heat_map" : "Generate Heat Map",
			"_heat_map_analysis" : "Heat Map Analysis",
			"_heat_map_scriteria" : "Select Criteria",

			"_save" : "Save",
			"_cancel" : "Cancel",
			"_city_dep" : "City Department",
			"_s_category" : "Select Department",
			"_update" : "Update",
			
			"_custom_scalebar" : "Custom Scalebar",
			"_scale" : "Scale",
			"_enter_scale" : "Enter Scale",
			"_scale_note" : "Note: Minimum Scale value is 100 and maximum scale value is 1,00,000.",
			
			"_add_layer" : "Add Layer",
			"_add_layer_note" : "Note: To add shapefiles select zipped folder containing (.shp, .shx, .prj etc.) file formats & to add KML select .kmz or .kml files.",
			"_add_layer_file" : "Select File",
			
			"_proxomity_anaylysis" : "Proximity Analysis",
			
			"_poi_select_dept": "Select Department",
			"_poi_select_poi": "Select POI",
			"_poi_from_date": "From Date",
			"_poi_to_date": "To Date",
			"_poi_submit": "Submit",
			
			/**
			 * Place holders
			 */

			"plot_placeHolder" : "Plot Number",
			"bid_placeHolder" : "Building ID",
			"pholder_evt_name" : "Enter Event Name",
			"pholder_venue" : "Enter Venue",
			"pholder_date" : " Date & Time",
			"pholder_web_address" : "Enter Web Address",
			"pholder_efee" : "Enter Entry Fee",
			"pholder_cperson" : "Enter Contact Person",
			"pholder_eid" : "Enter Email Id",
			"pholder_cnumber" : "Enter Mobile Number",
			"pholder_organizer" : "Enter Organizer",
			"pholder_lat" : "Enter Latitude",
			"pholder_long" : "Enter Longitude",
			"pholder_event_desc" : "Enter Description",

			"pholder_comment" : "Enter Comment",
			"pholder_fs_address" : "Enter Address",
			"pholder_fsc_name" : "Enter Name",
			"pholder_fsc_city" : "Enter City",
			"pholder_fsc_pincode" : "Enter Pincode",
			"pholder_fsc_mnumber" : "Enter Mobile Number",
			"pholder_fsc_emil" : "Enter Email",

			"fsc_feedback" : "Feedback",
			"fsc_suggestions" : "Suggestion",
			"fsc_complain" : "Complaint",

			"_2d" : "2D",
			"_3d" : "3D",
			
			"_filter" : "Filter",
			"_ward" : "Ward",

			"_attribute_query" : "Attribute Query",
			
			"_incident_type" : "Select Incident Type",
			"_incident_title" : "Reported Issues",
			
			"_know_your_thana": "Know Your Thana",
			"_thana_select_location": "Select Location",
			"_thana_info_heading": "Police Thana Details",
			"_thana_info_name": "Police Thana Name",
			"_thana_info_address": "Address",
			"_thana_info_contact": "Contact Number",
			"_thana_info_incharge": "Thana Incharge Name",
			"_thana_call_text": "For any assistance Dial 100",
			
			"_unauthorized_user_text_popup": "You are not an Authorized User !",
			"_unauthorized_user_event_popup":"In order to add event , Please register to our portal by clicking below",
			"_unauthorized_user_feedback_popup": "In order to provide feedback or suggestion , Please register to our portal by clicking below",
			"_unauthorized_user_addData_popup":"In order to add data , Please register to our portal by clicking below",
			"_unauthorized_user_addLayer_popup":"In order to add layer , Please register to our portal by clicking below",
			"_unauthorized_user_tool_popup": "In order to use this tool , Please register to our portal by clicking below",
			
			"_send_intimation": "Send Intimation",
			
		},
		"hindi" : {

			/**
			 * LOGIN PAGE
			 */
			
			"_indore_header": "इंदौर स्मार्ट मैप",
			"_login" : "लॉग इन करें",
			"_city_gis" : "सिटी जी.आई.एस.",
			"_username" : "उपयोगकर्ता नाम",
			"_password" : "पासवर्ड",
			"_forgot_password" : "पासवर्ड भूल गए",
			"_enter_captcha" : "केप्चा भरे",
			"_city_map" : "स्मार्ट मैप",
			"_sign_up" : "साइन अप करें",
			"_change_password" : "पासवर्ड बदलें",
			"_it_policy_heading": "आईटी नीति",
			"_it_policy_description1": "हम आपको जवाब देने के अलावा किसी भी उद्देश्य के लिए व्यक्तिगत जानकारी एकत्र नहीं करते हैं (उदाहरण के लिए, आपके प्रश्नों का जवाब देने के लिए)। यदि आप हमें एक ई-मेल पते या डाक पते के साथ हमसे संपर्क फ़ॉर्म भरने और वेबसाइट के माध्यम से हमें इसे सबमिट करने जैसी व्यक्तिगत जानकारी प्रदान करने का चयन करते हैं, तो हम आपके संदेश का जवाब देने के लिए और आपको प्राप्त करने में मदद करने के लिए उस जानकारी का उपयोग करते हैं। आपके द्वारा अनुरोधित जानकारी।",
			"_it_policy_description2": "जब आप इस वेबसाइट पर ब्राउज़ करते हैं, पृष्ठ पढ़ते हैं या जानकारी डाउनलोड करते हैं, तो हम आपकी यात्रा के बारे में कुछ तकनीकी जानकारी को स्वचालित रूप से इकट्ठा करते हैं और संग्रहीत करते हैं। यह जानकारी कभी भी यह नहीं बताती है कि आप कौन हैं। आपकी यात्रा के बारे में हम जो जानकारी एकत्र करते हैं और संग्रहीत करते हैं, वह नीचे सूचीबद्ध है:",
			"_it_policy_li1":"आपके सेवा प्रदाता का इंटरनेट डोमेन (उदा। Mtnl.net.in) और आईपी पता (एक आईपी पता एक संख्या है जो स्वचालित रूप से आपके कंप्यूटर को सौंपा जाता है जब भी आप वेब सर्फ कर रहे होते हैं) जिससे आप हमारी वेबसाइट तक पहुँचते हैं।",
			"_it_policy_li2":"ब्राउज़र का प्रकार (जैसे फ़ायरफ़ॉक्स, नेटस्केप या इंटरनेट एक्सप्लोरर) और ऑपरेटिंग सिस्टम (विंडोज, लिनक्स) हमारी साइट तक पहुंचने के लिए उपयोग किया जाता है।",
			"_it_policy_li3":"वह दिनांक और समय जब आप हमारी साइट तक पहुँचते / पहुँचते हैं।",
			"_it_policy_li4":"आपके द्वारा देखे गए पृष्ठ / URL और",
			"_it_policy_li5":"यदि आप किसी अन्य वेबसाइट से इस वेबसाइट पर पहुंचे, तो उस रेफ़रिंग वेबसाइट का पता।",
			"_it_policy_description3": "इस जानकारी का उपयोग केवल साइट को आपके लिए अधिक उपयोगी बनाने में हमारी सहायता के लिए किया जाता है। इस डेटा के साथ, हम अपनी साइट पर आगंतुकों की संख्या और हमारे आगंतुकों द्वारा उपयोग की जाने वाली तकनीक के प्रकारों के बारे में सीखते हैं। हम कभी भी व्यक्तियों और उनकी यात्राओं के बारे में जानकारी को ट्रैक या रिकॉर्ड नहीं करते हैं।",
			"_it_policy_description4": "जब आप हमारी वेबसाइट देखते हैं, तो हम आपके कंप्यूटर पर अगली बार आपके पीसी को देखने के लिए स्वचालित रूप से पहचानने के लिए \"कुकी\" के रूप में कुछ डेटा स्टोर कर सकते हैं। मिसाल के तौर पर कुकीज़ हमारी कई तरह से मदद कर सकती हैं, जैसे कि हमें किसी वेबसाइट को अपनी रुचियों से बेहतर मिलान करने के लिए या अपने पासवर्ड को स्टोर करने की अनुमति देकर, ताकि आप उसे हर बार फिर से दर्ज कर सकें। यदि आप कुकीज़ प्राप्त नहीं करना चाहते हैं, तो कृपया अपने कंप्यूटर के हार्ड ड्राइव से सभी कुकीज़ को मिटाने के लिए अपने इंटरनेट ब्राउज़र को कॉन्फ़िगर करें, सभी कुकीज़ को ब्लॉक करें या कुकी संग्रहीत होने से पहले चेतावनी प्राप्त करें।",
			"_copyright_policy_heading": "कॉपीराइट नीति",
			"_copyright_policy_description": "इंदौर स्मार्ट सिटी डेवलपमेंट लिमिटेड की अनुमति के बिना इस वेबसाइट की सामग्री को आंशिक रूप से या पूरी तरह से पुन: प्रस्तुत नहीं किया जा सकता है। यदि किसी अन्य वेबसाइट के हिस्से के रूप में संदर्भित किया जाता है, तो स्रोत को उचित रूप से स्वीकार किया जाना चाहिए। इस वेबसाइट की सामग्री का उपयोग किसी भी भ्रामक या आपत्तिजनक संदर्भ में नहीं किया जा सकता है।",
			"_tc_heading": "नियम एवं शर्तें",
			"_tc_description1": "यह वेबसाइट इंदौर स्मार्ट सिटी डेवलपमेंट लिमिटेड द्वारा डिज़ाइन, विकसित और अनुरक्षित है और इस वेबसाइट को एक्सेस करके, आप बिना शर्त नियम और शर्तों के अनुसार कानूनी रूप से बाध्य होना स्वीकार करते हैं।",
			"_tc_description2": "यदि आप उल्लिखित नियमों और शर्तों से सहमत नहीं हैं, तो कृपया वेबसाइट तक न पहुँचें।",
			"_tc_description3": "यदि आप इस वेबसाइट को ब्राउज़ करना और उपयोग करना जारी रखते हैं, जिसका आप पालन करने के लिए सहमत हैं और उपयोग के निम्नलिखित नियमों और शर्तों से बाध्य हैं।",
			"_tc_description4": "हम बिना सूचना के इन स्थितियों को समय-समय पर बदलने का अधिकार सुरक्षित रखते हैं। आप स्वीकार करते हैं और सहमत हैं कि किसी भी संशोधनों के साथ खुद को परिचित करने के लिए समय-समय पर इन नियमों और शर्तों की समीक्षा करना आपकी जिम्मेदारी है। इस तरह के संशोधनों के बाद इस साइट का आपका निरंतर उपयोग संशोधित नियमों और शर्तों की पावती और समझौते का गठन करेगा।",
			"_tc_li1": "कुछ विवरणों तक पहुंचने के लिए, आपको पंजीकरण प्रक्रिया के भाग के रूप में या विवरणों का उपयोग करने की अपनी क्षमता के हिस्से के रूप में अपने बारे में कुछ जानकारी (जैसे पहचान, ईमेल, फोन नंबर आदि) प्रदान करने की आवश्यकता हो सकती है। आप सहमत हैं कि आपके द्वारा प्रदान की जाने वाली कोई भी जानकारी हमेशा सही, सही और अद्यतित रहेगी।",
			"_tc_li2": "हमारी जानकारी को कॉपी, डुप्लिकेट, पुन: पेश, बेचने, व्यापार करने या फिर से बेचना करने का प्रयास करना पूरी तरह से प्रतिबंधित है।",
			"_tc_li3": "समय-समय पर इस वेबसाइट में अन्य वेबसाइटों के लिंक भी शामिल हो सकते हैं। ये लिंक आपकी सुविधा के लिए और जानकारी प्रदान करने के लिए दिए गए हैं। इनका आशय यह नहीं है कि हम वेबसाइटों का समर्थन करते हैं)। लिंक की गई वेबसाइट की सामग्री के लिए हमारी कोई ज़िम्मेदारी नहीं है।",
			"_tc_li4": "इस वेबसाइट पर सामग्री की सटीकता और मुद्रा सुनिश्चित करने के प्रयास किए गए हैं; हालाँकि, इसे कानून के एक बयान के रूप में व्याख्या नहीं किया जाना चाहिए या किसी कानूनी उद्देश्यों के लिए उपयोग नहीं किया जाना चाहिए।",
			"_tc_li5": "किसी भी अस्पष्टता या संदेह के मामले में, उपयोगकर्ताओं को सलाह दी जाती है कि वे संबंधित विभाग (ओं) और / या अन्य स्रोत के साथ सत्यापन / जांच करें और उचित पेशेवर सलाह लें।",
			"_contact_us": "संपर्क करें",
			"_signup_email": "ईमेल*",
			"_signup_name": "नाम*",
			"_signup_contact": "मोबाइल नंबर*",
			"_signup_address": "पता*",
			"_signup_zipcode": "ज़िप कोड*",
			"_signup_city": "शहर*",
			"_signup_state": "राज्य*",
			"_signup_terms": "मैं सभी नियमों और शर्तों को स्वीकार करता हूं*",
			"_signup_readmore": "अधिक पढ़ें",
			"_forgot_baktologin": "लॉगिन पर वापस जाएं",
			"_education": "शिक्षण",
			"_health": "स्वास्थ्य",
			"_industrial": "औद्योगिक",
			"_mppcb": "एमपीपीसीबी",
			"_nic": "एनआईसी",
			"_aictsl": "एआईसीटीएसएल",
			"_mpkvvcl": "एमपीकेवीवीसीएल",
			"_police": "पुलिस",
			"_tc_plannning": "टीऔर सी योजना",
			"_ida": "आईडीए",
			"_rto": "आरटीओ",
			"_phe": "पीएचई",
			"_pwd": "पीडब्लूडी",
			"_wcwd": "डब्लूसीडब्लूडी",
			"_imc": "आईएमसी",
			"_land_record": "भूमि अभिलेख",

			/**
			 * SIDE BAR/MAP
			 */
			"_find_address_or_place" : "पता या स्थान खोजें",
			"_basemap_gal" : "बेसमैप गैलरी",
			"_layers" : "परतें",
			// "_query": "सवाल,प्रश्न",
			"_query" : "प्रश्न",
			// "_draw": "अंकित करना,चित्र बनाना",
			"_draw" : "चित्र बनाना",
			"_imc_services" : "IMC सेवाएँ",
			// "_around_me": "अराउंड मी,मेरे आसपास",
			"_around_me" : "मेरे आसपास",
			"_events" : "आयोजन",
			"_ward_information" : "वार्ड की जानकारी",
			"_know_your_property" : "अपनी संपत्ति को जानें",
			// "_authority_announcement": "प्राधिकरण की घोषणा,अतॉरिटी
			// अनाउन्स्मेंट",
//			"_authority_announcement" : "प्राधिकरण की घोषणा",
			"_authority_announcement" : "शहर की घोषणा",
			"_feedback_and_suggestion" : "प्रतिक्रिया और सुझाव",
			"_add_data" : "डेटा जोड़ें",
			"_from_location_to_location" : "दिशा",
			
			"llist_layers" : "परतें",
			"llist_legend" : "किंवदंती",
			"llist_opacity" : "अस्पष्टता",
			"opacity_by_individual_layer" : "व्यक्तिगत परत द्वारा अस्पष्टता",
			"llist_ltransparency" : "सभी दृश्यमान परत पारदर्शिता",
			"llist_transparent" : "पारदर्शक",
			
			"_home" : "होम",
			"_find_my_location" : "मेरा स्थान ढूंढें",
			"_print" : "प्रिंट",
			"_measurement" : "नाप",
			"_bookmark" : "बुकमार्क",
			"_share" : "शेयर",
			"_clear_map" : "क्लियर मॅप",
			"_dark_gray_canvas" : "डार्क ग्रे कैनवस",
			"_imagery" : "इमेजरी",
			"_imagery_hybrid" : "इमेजरी हाइब्रिड",
			"_light_gray_canvas" : "लाइट ग्रे कैनवस",
			"_navigation_map" : "नेविगेशन नक्शा,नेविगेशन मॅप",
			"_oceans" : "ओशियन्स",
			"_streets_night" : "स्ट्रीट्स (नाइट)",
			"_streets_map" : "स्ट्रीट्स मॅप",
			"_topographic" : "टपोग्रॅफिक",
			"_task" : "कार्य",
			"_locate" : "पता लगाएँ",
			"_result" : "परिणाम",
			// "_select_ward": "वार्ड का चयन करें,सेलेक्ट वॉर्ड ",
			"_select_ward" : "वार्ड का चयन करें ",
			"_execute" : "एक्सेक्यूट",
			"_select_draw_mode" : "ड्रा मोड का चयन करें,सेलेक्ट ड्रॉ मोड",
			"_pollution_details" : "प्रदूषण का विवरण",
			"_avls_details" : "AVLS विवरण",
			"_pollution_level" : "प्रदूषण स्तर",
			"_select_details" : "विवरण का चयन करें",
			"_set_nearby_area" : "आस-पास का क्षेत्र निर्धारित करें",
			"_select_layer" : "परत का चयन करें",
			// "_view_event": "घटना देखें,व्यू इवेंट",
			"_view_event" : "घटना देखें",
			"_add_event" : "कार्यक्रम जोड़ें",
			"_select_duration" : "अवधि का चयन करें",
			"_select_department" : "विभाग का चयन करें",
			"_event_name" : "इवेंट नेम",
			"_description" : "विवरण",
			"_venue" : "स्थान",
			"_date" : "दिनांक",
			"_web_address" : "वेब पता",
			"_entry_fee" : "एंट्री फी",
			"_conatct_person" : "संपर्क सूत्र",
			"_email_id" : "ईमेल आईडी",
			"_contact_numner" : "संपर्क संख्या",
			"_organizer" : "व्यवस्था करनेवाला",
			"_latitude" : "लॅटिट्यूड",
			"_longitude" : "लॉंजिट्यूड",
			"_goto_longitude" : "लॅटिट्यूड (X)",
			"_goto_latitude": "लॉंजिट्यूड (Y)",
			"_upload_file" : "दस्तावेज अपलोड करें",
			"_submit" : "सब्मिट",
			"_clear" : "हटाना",
			"_choose_file" : "फ़ाइल का चयन",
			"_corporator_details" : "कॉर्पोरेटर का विवरण",
			"_ward_details" : "वार्ड का विवरण",
			"_zone_details" : "ज़ोन का विवरण",
			"_officers" : "अधिकारी",
			"_population" : "आबादी",
			"_educational_institute" : "शैक्षिक संस्थान",
			"_health_facilities" : "स्वास्थ्य सुविधाएं",
			"_hotel_and_entertainment" : "होटल और मनोरंजन",
			"_name" : "नाम",
			"_ward_name" : "वार्ड का नाम",
			"_zone_name" : "जोन का नाम",
			"_zone_no" : "जोन संख्या",
			"_health_officer" : "स्वास्थ्य अधिकारी",
			"_inspector" : "निरीक्षक",
			"_total_population" : "कुल जनसंख्या",
			"_gender" : "लिंग",
			"_schools" : "विद्यालय",
			"_colleges" : "कॉलेज",
			"_institutes" : "संस्थान",
			"_hospital" : "अस्पताल",
			"_dispensary" : "औषधालय",
			"_clinics" : "दवाख़ाना",
			"_hotels" : "होटल",
			"_restaurants" : "भोजनालय",
			"_know_your_location" : "अपनी लोकेशन जानिए",
			"_id" : "आईडी",
			"_mobile_number" : "मोबाइल नंबर",
			"_address" : "पता",
			"_feedback" : "प्रतिपुष्टि",
			"_suggestion" : "सुझाव",
			"_complaint" : "शिकायत",
			"_category" : "वर्ग",
			"_comment" : "टिप्पणी",
			"_city" : "शहर",
			"_pincode" : "पिन कोड",
			"_select_image" : "इमेज चुने",
			"_no_file_chosen" : "कोई फ़ाइल नहीं चुनी गई",
			"_remark" : "रिमार्क",
			"_note_for_from_to_location" : "नोट: दिशा पाने के लिए कृपया स्थान से & तक सेट करें और कृपया मॅप पर क्लिक करें",
			"_to_location" : "स्थान के लिए",
			"_from_location" : "स्थान से",
			"_enter_from_location" : "स्थान से दर्ज करें",
			"_enter_to_location" : "स्थान के लिए दर्ज करें",
			"_select_location" : "स्थान चुनें",
			"_from_location_by_name" : "नाम से स्थान",
			"_to_location_by_name" : "नाम से स्थान के लिए",
			
			"_apply" : "लागू",
			"_clear_location" : "स्थान क्लियर करें",
			"_login_content" : "इंदौर सबसे अधिक आबादी वाला और मध्य प्रदेश का सबसे बड़ा शहर है। इंदौर उन शहरों में से एक है जिन्हें पहले शीर्ष 20 स्मार्ट शहरों में चुना गया था इंदौर स्मार्ट सिटी एक शहरी पारिस्थितिकी तंत्र के रूप में उभर रहा है जिसका उद्देश्य डिजिटल प्रौद्योगिकी, ज्ञान और संपत्ति को एकीकृत करना है, नागरिकों के लिए अधिक संवेदनशील बनना, शहर की सेवाओं में सुधार करना और उन्हें बनाना है। शहर पहले से ज्यादा  प्यारा है। इंदौर स्मार्ट सिटी जीआईएस प्लेटफ़ॉर्म न केवल सरकारी डेटा को जनता के लिए अधिक सुलभ बनाता है, बल्कि विभिन्न बिंदुओं (पीओआई) की संपूर्ण भू-स्थानिक जानकारी भी प्रदान करता है जो शहर प्रशासन और जनता को भी मदद करेगा।",

			"_draw_preview" : "पूर्वावलोकन",
			"_draw_strok_color" : "स्ट्रोक का रंग",
			"_draw_border_width" : "सीमा चौड़ाई",
			"_draw_fill_color" : "रंग भरें",
			"_draw_color" : "रंग",
			"_draw_line_width" : "रेखा की चौड़ाई",
			"_draw_text" : "टेक्स्ट",
			"_draw_font_color" : "लिपि का रंग",
			"_draw_font_size" : "फ़ॉन्ट आकार",

			// "_imc_iswm" : "",
			"imc_smart_led" : "स्मार्ट नेतृत्व किया",
			"imc_ptax" : "संपत्ति कर",
			"imc_pid" : "प्लॉट आईडी",
			"imc_bid" : "बिल्डिंग आईडी",
			"imc_landmark" : "सीमा चिन्ह",
			"search" : "खोज",
			"_imc_from_date":"तारीख से",
			"_imc_to_date":"तारीख तक",
			"_around_note" : "ध्यान दें : परत और दूरी के चयन के बाद, कृपया मानचित्र पर क्लिक करें",

			"kyp_locality" : "स्थानीयता / क्षेत्र का नाम",
			"select_locality_thana": "स्थानीयता का चयन करें",
			"kyp_by_ward" : "वार्डवार",
			"kyp_note" : "ध्यान दें : संपत्ति विवरण देखने के लिए, प्लॉट बिंदु पर पहचानकर्ता ऑपरेशन निष्पादित किया।",
			"kyp_or" : "या",
			"kyp_oR" : "या",

			/*******************************************************************
			 * BOTTOM BAR
			 */

			"_print_ptitle" : "शीर्षक नाम",
			"_print_etitle" : "शीर्षक नाम दर्ज करें",
			"_print_playout" : "ख़ाका",
			"_print_pformat" : "स्वरूप",
			"_print_gprintout" : "प्रिंटआउट लें",

			"bmark_addbmark" : "बुकमार्क जोड़ें",
			"bmark_dbmark" : "हटाना",

			"_share_title" : "इस ऐप का लिंक साझा करें",
			"_share_linkop" : "लिंक का विकल्प",

			"_swipe_layer" : "स्वाइप की परत",
			"_swipe" : "स्वाइप",
			
			/*
			 * Department Portal
			 */

			"head_announce" : "घोषणा",
			"head_umanagement" : "उपयोगकर्ता प्रबंधन",
			"head_cmasterdata" : "सिटीजन मास्टर डाटा",
			"head_masterdata" : "मास्टर डाटा",
			"head_adddata" : "डेटा जोड़ें",
			"head_pmonitoring" : "परियोजना की निगरानी",
			"head_palerts" : "प्रोजेक्ट अलर्ट",
			"head_emanagement" : "इवेंट मैनेजमेंट",
			"head_fsuggestions" : "प्रतिक्रिया और सुझाव",
			"head_reports" : "रिपोर्ट",

			"_query_basic" : "बुनियादी प्रश्न",
			"_query_advanced" : "अग्रिम प्रश्न",
			"_query_spatial" : "स्थानिक प्रश्न",
			"_query_result" : "परिणाम",
			"_query_department" : "विभाग",
			"_query_sdepartment" : "विभाग का चयन करें",
			"_query_ward" : "वार्ड",
			"_query_sward" : "वार्ड का चयन करें",
			"_query_layer" : "परत",
			"_query_slayer" : "परत का चयन करें",
			"_query_field" : "फ़ील्ड",
			"_query_sfield" : "फ़ील्ड का चयन करें",
			"_query_value" : "मूल्य",
			"_query_evalue" : "मान दर्ज करें",
			"_query_logical_op" : "तार्किक संचालक",
			"_query_operator" : "ऑपरेटर का चयन करें",

			"squery_slayer" : "स्रोत परत",
			"squery_qtype" : "क्वेरी प्रकार",
			"squery_mlayer" : "मास्क परत",

			"_ann_add_announcement" : "घोषणा जोड़ें",
			"_ann_view_announcement" : "देखें घोषणा",
			"ann_type_announcement" : "घोषणा का प्रकार",
			"ann_title_announcement" : "घोषणा शीर्षक",
			"ann_etitle_announcement" : "शीर्षक दर्ज करें",
			"ann_description_announcement" : "घोषणा विवरण",
			"ann_data_time" : "घोषणा की तारीख और समय",
			"ann_date" : "घोषणा की तिथि",

			"umanagement_dmaster" : "विभाग के मास्टर",
			"umanagement_rmaster" : "भूमिका मास्टर",
			"umanagement_umaster" : "उपयोगकर्ता मास्टर",
			"umanagement_l_dmaster" : "विभाग मास्टर की सूची",
			"umanagement_add_department" : "विभाग जोड़ें",
			"umanagement_dname" : "विभाग का नाम",
			"umanagement_edepartment" : "विभाग दर्ज करें",
			"umanagement_created_by" : "के द्वारा बनाई गई",
			"umanagement_enter_name" : "नाम दर्ज",
			"umanagement_description" : "विवरण",
			"umanagement_add_description_here" : "विवरण यहाँ जोड़ें",
			"umanagement_sstatus" : "स्थिति का चयन करें",
			"umanagement_u_department" : "अद्यतन विभाग",

			"umanagement_role_add_role" : "भूमिका जोड़ें",
			"umanagement_role_lrole_master" : "रोल मास्टर की सूची",
			"umanagement_role_sdepatrment" : "विभाग का चयन करें",
			"umanagement_role_rname" : "भूमिका का नाम",
			"umanagement_role_erolename" : "भूमिका का नाम दर्ज करें",
			"umanagement_role_mobapp" : "मोबाइल एप्लिकेशन",
			"umanagement_role_webapp" : "वेब एप्लीकेशन",
			"umanagement_role_sroletype" : "रोल प्रकार का चयन करें",

			"umnanagement_user_adduser" : "उपयोगकर्ता जोड़ें",
			"umnanagement_user_list_user" : "उपयोगकर्ता की सूची",
			"umnanagement_user_name" : "उपयोगकर्ता नाम",
			"umnanagement_user_ename" : "नाम दर्ज",
			"umnanagement_user_email" : "ईमेल",
			"umnanagement_user_eemail" : "ईमेल आईडी दर्ज करें",
			"umnanagement_user_password" : "पासवर्ड",
			"umnanagement_user_epassword" : "पास वर्ड दर्ज करें",
			"umnanagement_user_mnumber" : "फोन नंबर",
			"umnanagement_user_emnumber" : "मोबाइल नंबर दर्ज करें",
			"umnanagement_user_sdepartment" : "विभाग का चयन करें",
			"umnanagement_user_srole" : "भूमिका का चयन करें",

			"cmdata_cmaster" : "सिटीजन मास्टर",
			"cmdata_lcmaster" : "सिटीजन मास्टर की सूची",

			"fsc_t_feedback" : "प्रतिपुष्टि",
			"fsc_t_suggestion" : "सुझाव",
			"fsc_t_complaint" : "शिकायत",
			"fsc_lfeedback" : "प्रतिक्रिया की सूची",
			"fsc_lsuggestion" : "सुगंधों की सूची",
			"fsc_lcomplaint" : "शिकायतों की सूची",

			"report_greport" : "रिपोर्ट प्राप्त करें",

			"master_data_get" : "मास्टर डेटा प्राप्त करें",

			"event_events" : "आयोजन",
			"events_levents" : "घटनाओं की सूची",
			"events_addevent" : "कार्यक्रम जोड़ें",
			"events_ename" : "इवेंट नेम",
			"events_eename" : "ईवेंट नाम दर्ज करें",
			"events_desc" : "विवरण",
			"events_venue" : "स्थान",
			"events_evenue" : "स्थल में प्रवेश करें",
			"events_date" : "तारीख और समय",
			"events_webaddress" : "वेब पता",
			"events_ewebaddress" : "वेब पता दर्ज करें",
			"events_entree_fee" : "एंट्री फी",
			"events_eentree_fee" : "प्रवेश शुल्क दर्ज करें",
			"events_contact_person" : "संपर्क सूत्र",
			"events_e_contact_person" : "संपर्क व्यक्ति दर्ज करें",
			"events_email_id" : "ईमेल आईडी",
			"events_eemail_id" : "ईमेल आईडी दर्ज करें",
			"events_cnumber" : "संपर्क संख्या",
			"events_ecumber" : "संपर्क नंबर दर्ज करें",
			"events_organizer" : "व्यवस्था करनेवाला",
			"events_eorganizer" : "आयोजक दर्ज करें",
			"events_upload_file" : "दस्तावेज अपलोड करें",
			"events_edit" : "घटना संपादित करें",

			"pm_manage_project" : "परियोजना का प्रबंधन",
			"pm_project_reports" : "प्रोजेक्ट रिपोर्ट",

			"pm_projects_projects" : "परियोजनाओं",
			"pm_projects_add_project" : "प्रोजेक्ट जोड़ें",
			"pm_projects_location" : "स्थान",
			"pm_projects_binfo" : "बुनियादी जानकारी",
			"pm_projects_finance" : "वित्त",
			"pm_projects_assign_users" : "उपयोगकर्ता नियुक्त करें",
			"pm_projects_imagedocs" : "छवियाँ और डॉक्स",
			"pm_projects_location_lname" : "प्रोजेक्ट का स्थान",
			"pm_projects_location_elocation" : "प्रोजेक्ट का स्थान दर्ज करें",
			"pm_projects_location_lat" : "अक्षांश",
			"pm_projectslocation_elat" : "अक्षांश दर्ज करें",
			"pm_projects_location_long" : "देशांतर",
			"pm_projects_location_elong" : "देशांतर दर्ज करें",
			"pm_projects_location_tehsil" : "तहसील",
			"pm_projectslocation_ward" : "वार्ड क्रमांक",
			"pm_projects_location_district" : "जिला",
			"pm_projects_location_village" : "गाँव",
			"pm_projects_location_zone" : "क्षेत्र क्रमांक",
			"pm_projects_location_ward_name" : "वार्ड नाम",
			"pm_projects_location_zone_name" : "क्षेत्र नाम",
			"pm_projects_expected_start_date" : "अपेक्षित आरंभ तिथि",
			"pm_projects_expected_completion_date" : "अपेक्षित समापन तिथि",
			"pm_projects_type" : "प्रोजेक्ट का प्रकार",

			"pm_projects_binfo_pname" : "परियोजना का नाम",
			"pm_projects_binfo_epname" : "प्रोजेक्ट का नाम दर्ज करें",
			"pm_projects_binfo_cnumber" : "मोबाइल नंबर",
			"pm_projects_binfo_ecnumber" : "मोबाइल नंबर दर्ज करें",
			"pm_projects_binfo_cemail": "ठेकेदार का ईमेल आईडी",
			"pm_projects_binfo_ecemail": "ठेकेदार का ईमेल आईडी दर्ज करें",
			"pm_projects_binfo_wperiod" : "कार्य क्रम अवधि",
			"pm_projects_binfo_ewperiod" : "कार्य क्रम अवधि दर्ज करें",
			"pm_projects_binfo_sdate" : "प्रोजेक्ट प्रारंभ दिनांक",
			"pm_projects_binfo_ssdate" : "तारीख़ चुनें",
			"pm_projects_binfo_consultantname" : "डिजाइन सलाहकार का नाम",
			"pm_projects_binfo_econsultantname" : "डिजाइन सलाहकार नाम दर्ज करें",
			"pm_projects_binfo_pprogress" : "भौतिक प्रगति (%)",
			"pm_projects_binfo_epprogress" : "भौतिक प्रगति दर्ज करें",
			"pm_projects_binfo_remarks" : "टिप्पणी",
			"pm_projects_binfo_eremarks" : "टिप्पणी दर्ज करें",
			"pm_projects_binfo_cname" : "ठेकेदार का नाम",
			"pm_projects_binfo_ecname" : "ठेकेदार का नाम दर्ज करें",
			"pm_projects_binfo_cagency" : "ठेकेदार एजेंसी",
			"pm_projects_binfo_ecagency" : "ठेकेदार एजेंसी दर्ज करें",
			"pm_projects_binfo_workorderno" : "कार्य क्रम सं",
			"pm_projects_binfo_eworkorderno" : "कार्य क्रम सं।",
			"pm_projects_binfo_edate" : "परियोजना की पूर्णता तिथि",
			"pm_projects_binfo_eedate" : "तारीख़ चुनें",
			"pm_projects_binfo_consultannumber" : "डिज़ाइन सलाहकार संपर्क नंबर",
			"pm_projects_binfo_ecunsultantnumber" : "डिजाइन सलाहकार से संपर्क करें।",
			"pm_projects_binfo_cperiod" : "अनुबंधनकाल",
			"pm_projects_binfo_ecperiod" : "अनुबंध अवधि दर्ज करें",
			"pm_projects_binfo_pstatus" : "परियोजना की स्थिति",

			"pm_projects_finance_pfc" : "परियोजना की कुल लागत",
			"pm_projects_finance_epfc" : "परियोजना की कुल लागत दर्ज करें",
			"pm_projects_finance_pbd" : "प्रदर्शन बैंक की तारीख",
			"pm_projects_finance_spbd" : "प्रदर्शन बैंक तिथि का चयन करें",
			"pm_projects_finance_pbg" : "प्रदर्शन बैंक गारंटी",
			"pm_projects_finance_epbg" : "प्रदर्शन बैंक गारंटी दर्ज करें",
			"pm_projects_finance_fp" : "वित्तीय प्रगति (%)",
			"pm_projects_finance_efp" : "वित्तीय प्रगति दर्ज करें",

			"pm_projects_allotted_to": "प्रोजेक्ट आवंटन",
			"pm_projects_allotted_to_contactNo": "संपर्क नंबर",
			"pm_projects_allotted_to_name": "नाम",
			"pm_projects_allotted_to_email": "ईमेल आईडी",
			
			"pm_projects_img_imgs" : "छवि",
			"pm_projects_img_uimage" : "तस्वीर डालिये",
			"pm_projects_img_docs" : "दस्तावेज़",
			"pm_projects_img_udocs" : "दस्तावेज़ अपलोड करें",

			"pm_projects_milestones" : "माइलस्टोन",
			"pm_miles_select_pro" : "प्रोजेक्ट का चयन करें",
			"pm_miles_add_milestone" : "माइलस्टोन जोड़ें",
			"pm_miles_update_milestone" : "अद्यतन माइलस्टोन",
			"pm_miles_mname" : "माइलस्टोन का नाम",
			"pm_miles_description" : "विवरण",
			"pm_miles_startdate" : "प्रारंभ दिनांक",
			"pm_miles_enddate" : "समाप्ति तिथि",
			"pm_miles_image" : "छवि",
			"pm_miles_document" : "दस्तावेज़",
			"pm_miles_mstatus" : "माइलस्टोन की स्थिति",
			"pm_miles_remarks" : "टिप्पणी",
			"pm_miles_emname" : "माइलस्टोन का नाम दर्ज करें",
			"pm_miles_add_desc" : "विवरण यहाँ जोड़ें",
			"pm_miles_add_remarks" : "यहाँ रिमार्क जोड़ें",

			"_x_y_coordinates" : "अपने समन्वय को जानें",
			"_go_to" : "के लिए जाओ",

			"_buffer_polygon_buf" : "बहुभुज बफर",
			"_buffer_direction" : "दिशा",
			"_buffer_draw_polygon" : "बहुभुज बनाएं",
			"_buffer_sslocation" : "स्रोत स्थान का चयन करें",
			"_buffer_sdlocation" : "गंतव्य स्थान का चयन करें",
			"_buffer_slocation" : "स्रोत स्थान",
			"_buffer_dlocation" : "गंतव्य स्थान",
			"_buffer_gdirection" : "दिशा प्राप्त करें",
			"_buffer" : "बफर",

			"_generate_heat_map" : "हीट मैप जनरेट करें",
			"_heat_map_analysis" : "हीट मैप विश्लेषण",
			"_heat_map_scriteria" : "मानदंड चुनें",
			
			"_save" : "सहेजें",
			"_cancel" : "रद्द करना",
			"_city_dep" : "नगर विभाग",
			"_s_category" : "विभाग का चयन करें",
			"_update" : "अपडेट करें",
			
			"_custom_scalebar" : "कस्टम स्केलबार",
			"_scale" : "स्केल",
			"_enter_scale" : "स्केल दर्ज करें",
			"_scale_note" : "नोट: न्यूनतम स्केल मान 100 है और अधिकतम स्केल मान 1,00,000 है",


			"_add_layer" : "परत जोड़ें",
			"_add_layer_note" : "नोट: शपफीलेस ऐड करने के लिए ज़िपित फोल्डर को सेलेक्ट करें जिसमे ये (.shp, .shx, .prj etc.) फाइल फोर्मट्स मौजूद हैं और KML तो ऐड करने के लिए .kmz या .kml को सेलेक्ट करे।  ",
			"_add_layer_file" : "फ़ाइल का चयन करें",
			
			"_proxomity_anaylysis" : "निकटता विश्लेषण",
			
			"_poi_select_dept": "विभाग का चयन करें",
			"_poi_select_poi": "पीओआई का चयन करें",
			"_poi_from_date": "तारीख से",
			"_poi_to_date": "तारीख तक",
			"_poi_submit": "जमा करें",
			
			/**
			 * place holders
			 * 
			 */

			"plot_placeHolder" : "प्लॉट नंबर",
			"bid_placeHolder" : "बिल्डिंग आईडी",
			"pholder_evt_name" : "ईवेंट का नाम दर्ज करें",
			"pholder_venue" : "वेन्यू दर्ज करें",
			"pholder_date" : "तारीख और समय",
			"pholder_web_address" : "वेब पता दर्ज करें",
			"pholder_efee" : "प्रवेश शुल्क दर्ज करें",
			"pholder_cperson" : "संपर्क व्यक्ति दर्ज करें",
			"pholder_eid" : "ईमेल आईडी दर्ज करें",
			"pholder_cnumber" : "मोबाइल नंबर दर्ज करें",
			"pholder_organizer" : "आयोजक दर्ज करें",
			"pholder_lat" : "अक्षांश दर्ज करें",
			"pholder_long" : "देशांतर दर्ज करें",
			"pholder_event_desc" : "विवरण दर्ज करें",

			"pholder_comment" : "टिप्पणी दर्ज करें",
			"pholder_fs_address" : "पता दर्ज करें",
			"pholder_fsc_name" : "नाम दर्ज",
			"pholder_fsc_city" : "शहर दर्ज करें",
			"pholder_fsc_pincode" : "पिनकोड दर्ज करें",
			"pholder_fsc_mnumber" : "मोबाइल नंबर दर्ज करें",
			"pholder_fsc_emil" : "ईमेल दर्ज करें",

			"fsc_feedback" : "प्रतिपुष्टि",
			"fsc_suggestions" : "सुझाव",
			"fsc_complain" : "शिकायत",

			"_2d" : "2 डी",
			"_3d" : "3 डी",
			
			"_filter" : "फ़िल्टर",
			"_ward" : "वार्ड",
			
			"_attribute_query" : "गुण को स्वीकार करें",
			
			"_incident_type" : "घटना प्रकार का चयन करें",
			"_incident_title" : "रिपोर्ट की गई समस्याएं",
			
			"_know_your_thana": "जानिए आपका थाना",
			"_thana_select_location": "स्थान चुनें",
			"_thana_info_heading": "पुलिस थाना विवरण",
			"_thana_info_name": "पुलिस थाना नाम",
			"_thana_info_address": "पता",
			"_thana_info_contact": "संपर्क नंबर",
			"_thana_info_incharge": "थाना कार्यभारी नाम",
			"_thana_call_text": "किसी भी सहायता के लिए डायल 100",
			
			"_unauthorized_user_text_popup": "आप एक अधिकृत उपयोगकर्ता नहीं हैं!",
			"_unauthorized_user_event_popup":"ईवेंट जोड़ने के लिए, कृपया नीचे क्लिक करके हमारे पोर्टल पर रजिस्टर करें",
			"_unauthorized_user_feedback_popup":"प्रतिक्रिया या सुझाव देने के लिए, कृपया नीचे क्लिक करके हमारे पोर्टल पर रजिस्टर करें",
			"_unauthorized_user_addData_popup":"डेटा जोड़ने के लिए, कृपया नीचे क्लिक करके हमारे पोर्टल पर रजिस्टर करें",
			"_unauthorized_user_addLayer_popup":"परत जोड़ने के लिए, कृपया नीचे क्लिक करके हमारे पोर्टल पर पंजीकरण करें",
			"_unauthorized_user_tool_popup": "इस उपकरण का उपयोग करने के लिए , कृपया नीचे क्लिक करके हमारे पोर्टल पर रजिस्टर करें",

			"_send_intimation": "सूचना भेजे",
		}
	};

	// set language according to type
	set_lang = function(language) {
		if (dictionary.hasOwnProperty(language)) {

			// $(".loader").fadeIn();

			$("[data-translate]").text(function() {
				var key = $(this).data("translate");
				if (dictionary.hasOwnProperty(language)) {
					if ($(this).is("input") || $(this).is("textarea")) {
						let value = dictionary[language][key];
						$(this).attr('placeholder', value)
					} else {
						let value = dictionary[language][key];
						$(this).text(value);
					}
				}
				// let value = dictionary[language][key];
				// console.log("value > "+value);
				// $(this).text(value);
				// $(".loader").fadeOut();
			});
		}
	};

	/**
	 * Hindi language
	 */
	$("#pills-hindi-tab").click(function() {
		set_lang(hindi_lang);
		setCurrentLanguage(hindi_lang);
	});

	/**
	 * English language
	 */
	$("#pills-english-tab").click(function() {
		set_lang(eng_lang);
		setCurrentLanguage(eng_lang);
	});

	function setCurrentLanguage(language) {
		localStorage.setItem("current_language", language);
	}

	function configureLanguage() {

		var c_lang = localStorage.getItem("current_language");

		if (c_lang == null) {
			set_lang(eng_lang);
			setCurrentLanguage(eng_lang);
			$("#pills-tab #pills-hindi-tab").removeClass("active");
			$("#pills-tab #pills-english-tab").addClass("active");
		}

		if (c_lang == eng_lang) {
			$("#pills-tab #pills-hindi-tab").removeClass("active");
			$("#pills-tab #pills-english-tab").addClass("active");
		} else if (c_lang == hindi_lang) {
			$("#pills-tab #pills-english-tab").removeClass("active");
			$("#pills-tab #pills-hindi-tab").addClass("active");
		}
		set_lang(c_lang);
	}

	/**
	 * READY FUNCTION
	 */

	$(document).ready(function() {
		configureLanguage();
	});
});

