$(function() {
	"use strict";

	// Some variables for later
	var dictionary, set_lang;
	var eng_lang = "english";
	var hindi_lang = "hindi";
	var current_lang = "";

	// Object literal behaving as multi-dictionary
	dictionary = {
		"english" : {
		
			"_indore_header": "Indore Smart Map",
			"_app_overview": "Application Overview",
			"_app_ov_loginScreen": "Login Screen",
			"_app_ov_centralDashboard": "Central Dashboard",
			"_app_ov_cityMap": "City Map",
			"_app_ov_language": "Language",
			"_app_ov_mapTools": "Map Tools",
			"_app_ov_mt_globalSearch": "Global Search",
			"_app_ov_mt_zoomInOut": "Zoom In & Out",
			"_app_ov_mt_myLocation": "My Location",
			"_app_ov_mt_print": "Print",
			"_app_ov_mt_measurement": "Measurement",
			"_app_ov_mt_clearMap": "Clear Map",
			"_app_ov_mt_bookmark": "Bookmark",
			"_app_ov_menu": "Menu",
			"_app_ov_menu_baseMapGallery": "Base map Gallery",
			"_app_ov_menu_layers": "Layers",
			"_app_ov_menu_query": "Query",
			"_app_ov_menu_drawTool": "Draw Tool",
			"_app_ov_menu_proximityAnalysis": "Proximity Analysis",
			"_app_ov_menu_projectMonitoring": "Project Monitoring",
			"_app_ov_menu_projectAlerts": "Project Alert",
			"_app_ov_menu_reports": "Reports",
			"_app_ov_menu_poiData": "POI Data",
			"_app_ov_3dMap": "3D Map",
			"_help_for_dept": "City Enterprise GIS Portal: Departmental User",
			"_login_screen_header": "Login Screen",
			"_login_screen_para1": "Department user can login with a valid username and password provided by the admin",
			"_login_screen_para2": "If you forget your password click on Forgot Password link.",
			"_central_dashboard_header": "Central Dashboard",
			"_central_dashboard_para1": "After the login by Super Admin/GIS Cell, Admin user can see the central Dashboard with different department cumulative information. By clicking on it, User will be redirected to respective department dashboard for more details.",
			"_central_dashboard_para2": "Super admin will be able to see the following department's information on the Central Dashboard.",
			"_central_dashboard_aictsl": "AICTSL - Total no of Bus Stops",
			"_central_dashboard_electric": "MPKVVCL - Total No of Street Lights",
			"_central_dashboard_police": "Police - Total no. of Police station",
			"_central_dashboard_tcplanning": "Town & Country Planning – Total Town planning Area in sq. km.",
			"_central_dashboard_ida": "IDA – Total no of IDA Schemes",
			"_central_dashboard_health": "Health – Total No. of Hospitals",
			"_central_dashboard_phe": "PHE Urban – Total length of Water lines in km.",
			"_central_dashboard_pwd": "PWD – Total No of roads",
			"_central_dashboard_education": "Education Department – Total No. of Schools",
			"_central_dashboard_wcwd": "Women & Child Welfare – Total no. of Anganwadi",
			"_central_dashboard_mppcb": "MPPCB (Pollution) – No. of AQI - PM 2.5",
			"_central_dashboard_industry": "MPAKVN – Total Industrial land in Sq. Km.",
			"_central_dashboard_imc": "IMC - Litter Bin Locations",
			"_central_dashboard_smartCity": "Indore Smart City - Total No. of Projects",
			"_aictsl_header": "AICTSL",
			"_aictsl_li1": "AICTSL Department dashboard will display the Type wise total no. of buses working in the Indore city.",
			"_aictsl_li2": "User can navigate to reports such as:",
			"_aictsl_chart1": "Bus Routes",
			"_aictsl_chart1_li1": "Bus Route Wise Count",
			"_aictsl_chart1_li2": "Total Bus Routes",
			"_aictsl_chart2": "Bus Stops",
			"_aictsl_chart2_li1": "Ward Wise Bus Stop Count",
			"_aictsl_chart2_li2": "Total Bus Stops",
			"_aictsl_chart3": "AFCS",
			"_aictsl_chart3_li1": "Equipment Type Wise Collection Amount",
			"_aictsl_li3": "User can also filter the data as per the ward",
			"_aictsl_li4": "User can hover on each bar for more details about the graph.",
			"_aictsl_li5": "On clicking any of the chart the data will be plotted on map.",
			"_aictsl_li6": "User can increase the width of slider bar to increase the no. of bars in graph to be seen at that point of time.",
			"_aictsl_li7": "User can also download the graph by clicking on the Download button.",
			"_electric_header": "Electrical",
			"_electric_li1": "Electrical dashboard will display the complete data of Electric Department as follows:",
			"_electric_chart1": "Street light",
			"_electric_chart1_li1": "Total Street Lights",
			"_electric_chart1_li2": "Ward Wise Street Lights",
			"_electric_chart2": "Transformers",
			"_electric_chart2_li1": "Total Transformers",
			"_electric_chart2_li2": "Ward Wise Transformers",
			"_electric_chart3": "Smart LED",
			"_electric_chart3_li1": "Total Smart LED",
			"_electric_chart3_li2": "Ward Wise Smart LED",
			"_electric_chart3_li3": "Watt Wise Smart LED Distribution (%)",
			"_electric_li2": "User can also filter the data as per the ward.",
			"_electric_li3": "User can hover on each bar for more details about the graph.",
			"_electric_li4": "On clicking any of the chart the data will be plotted on map.",
			"_electric_li5": "User can increase the width of slider bar to increase the no. of bars in graph to be seen at that point of time.",
			"_electric_li6": "User can also download the graph by clicking on the Download button.",
			"_police_header": "Police",
			"_police_li1": "Police dashboard will display the data related to Police Department which includes",
			"_police_chart1": "Police Station",
			"_police_chart1_li1": "Total Police Stations",
			"_police_chart1_li2": "Zone Wise Police Stations",
			"_police_chart1_li3": "Police Station Wise Number Of Road Accidents",
			"_police_chart1_li4": "Nature Of Injury In Accidents (%)",
			"_police_chart1_li5": "Vehicle Type Involved In Accidents (%)",
			"_police_chart1_li6": "Road Category Wise Accident Count (%)",
			"_police_chart1_li7": "Police Station Wise Vehicle Theft Incidents",
			"_police_li2": "User can also filter the data as per the ward.",
			"_police_li3": "User can hover on each bar for more details about the graph.",
			"_police_li4": "On clicking any of the chart the data will be plotted on map.",
			"_police_li5": "User can increase the width of slider bar to increase the no. of bars in graph to be seen at that point of time.",
			"_police_li6": "User can also download the graph by clicking on the Download button.",
			"_tcplanning_header": "Town & Country Planning",
			"_tcplanning_li1": "Town planning dashboard will display the following data:",
			"_tcplanning_chart1": "Town Planning Area",
			"_tcplanning_chart1_li1": "Land Use Distribution (%)",
			"_tcplanning_chart1_li2": "Projected Growth Rate In Commercial Area (From 2020 To 2031)",
			"_tcplanning_chart1_li3": "Projected Growth Rate In Residential Area (From 2020 To 2031)",
			"_tcplanning_li2": "User can also filter the data as per the ward.",
			"_tcplanning_li3": "User can hover on each bar for more details about the graph.",
			"_tcplanning_li4": "On clicking any of the chart the data will be plotted on map.",
			"_tcplanning_li5": "User can increase the width of slider bar to increase the no. of bars in graph to be seen at that point of time.",
			"_tcplanning_li6": "User can also download the graph by clicking on the Download button.",
			"_ida_header": "IDA",
			"_ida_li1": "IDA Dashboard will display the total count of town planning schemes with status as follows:",
			"_ida_chart1": "Status Wise Total TP Schemes",
			"_ida_chart1_li1": "Total TP Schemes",
			"_ida_chart2": "Developed Schemes",
			"_ida_chart2_li1": "Total Developed Schemes",
			"_ida_chart3": "Proposed Schemes",
			"_ida_chart3_li1": "Total Proposed Schemes",
			"_ida_li2": "User can also filter the data as per the ward.",
			"_ida_li3": "User can hover on each bar for more details about the graph.",
			"_ida_li4": "On clicking any of the chart the data will be plotted on map.",
			"_ida_li5": "User can increase the width of slider bar to increase the no. of bars in graph to be seen at that point of time.",
			"_ida_li6": "User can also download the graph by clicking on the Download button.",
			"_health_header": "Health",
			"_health_li1": "Health dashboard will display health facilities available in Indore city as follows:",
			"_health_chart1": "Hospitals",
			"_health_chart1_li1": "Total Hospitals",
			"_health_chart1_li2": "Ownership Type wise Hospitals",
			"_health_chart1_li3": "Hospital Wise ICU",
			"_health_chart1_li4": "Emergency Services (%)",
			"_health_chart1_li5": "Blood Bank Facility (%)",
			"_health_chart1_li6": "Mortuary (%)",
			"_health_chart1_li7": "Ward Wise Hospitals",
			"_health_chart2": "Pharmacies",
			"_health_chart2_li1": "Total Pharmacies",
			"_health_chart2_li2": "Ward Wise Pharmacies",
			"_health_li2": "User can also filter the data as per the ward.",
			"_health_li3": "User can hover on each bar for more details about the graph.",
			"_health_li4": "On clicking any of the chart the data will be plotted on map.",
			"_health_li5": "User can increase the width of slider bar to increase the no. of bars in graph to be seen at that point of time.",
			"_health_li6": "User can also download the graph by clicking on the Download button.",
			"_phe_header": "Public Health Engineering (Urban)",
			"_phe_li1": "Public Health Engineering (Urban) dashboard will display total length of water supply line in km. also total count of tube well and water valves as follows:",
			"_phe_chart1": "Water Supply Line (ABD Area)",
			"_phe_chart1_li1": "Total Water Line Length (in meter)",
			"_phe_chart1_li2": "Diameter Wise Water Supply (mm)",
			"_phe_chart1_li3": "Ward Wise Water Supply Length (mt.)",
			"_phe_chart2": "Water Valves (ABD Area)",
			"_phe_chart2_li1": "Total Water Valves",
			"_phe_chart2_li2": "Ward Wise Water Valves",
			"_phe_li2": "User can also filter the data as per the ward.",
			"_phe_li3": "User can hover on each bar for more details about the graph.",
			"_phe_li4": "On clicking any of the chart the data will be plotted on map.",
			"_phe_li5": "User can increase the width of slider bar to increase the no. of bars in graph to be seen at that point of time.",
			"_phe_li6": "User can also download the graph by clicking on the Download button.",
			"_pwd_header": "PWD",
			"_pwd_li1": "PWD Department dashboard will display the Road network details of Indore City as follows:",
			"_pwd_chart1": "Roadways",
			"_pwd_chart1_li1": "Total Road Length (KM)",
			"_pwd_chart1_li2": "Type Wise Road Length (KM)",
			"_pwd_chart1_li3": "Surface Type Wise Road Length (KM)",
			"_pwd_chart2": "Bridges",
			"_pwd_chart2_li1": "Total Bridges",
			"_pwd_chart2_li2": "Ward Wise Bridges",
			"_pwd_li2": "User can also filter the data as per the ward.",
			"_pwd_li3": "User can hover on each bar for more details about the graph.",
			"_pwd_li4": "On clicking any of the chart the data will be plotted on map.",
			"_pwd_li5": "User can increase the width of slider bar to increase the no. of bars in graph to be seen at that point of time.",
			"_pwd_li6": "User can also download the graph by clicking on the Download button.",
			"_education_header": "Education",
			"_education_li1": "Education dashboard will display the education infrastructure available in the Indore city as follows:",
			"_education_chart1": "Primary Schools",
			"_education_chart1_li1": "Total Primary Schools",
			"_education_chart1_li2": "Play Ground Distribution (%)",
			"_education_chart1_li3": "Male Hostel Distribution (%)",
			"_education_chart1_li4": "Female Hostel Distribution (%)",
			"_education_chart2": "Secondary Schools",
			"_education_chart2_li1": "Total Secondary Schools",
			"_education_chart2_li2": "Play Ground Distribution (%)",
			"_education_chart2_li3": "Male Hostel Distribution (%)",
			"_education_chart2_li4": "Female Hostel Distribution (%)",
			"_education_li2": "User can also filter the data as per the ward.",
			"_education_li3": "User can hover on each chart for more details about the graph.",
			"_education_li4": "On clicking any of the chart the data will be plotted on map.",
			"_education_li5": "User can also download the graph by clicking on the Download button.",
			"_wcwd_header": "Women Child & Welfare",
			"_wcwd_li1": "Women & Child welfare department dashboard will display the details of total number of Anganwadi in the Indore city as follows:",
			"_wcwd_chart1": "Anganwadi",
			"_wcwd_chart1_li1": "Total Anganwadi",
			"_wcwd_chart1_li2": "Open Space or Playground Present In Anganwadi (%)",
			"_wcwd_chart1_li3": "Ward Wise Anganwadi",
			"_wcwd_li2": "User can also filter the data as per the ward.",
			"_wcwd_li3": "User can hover on each chart for more details about the graph.",
			"_wcwd_li4": "On clicking any of the chart the data will be plotted on map.",
			"_wcwd_li5": "User can also download the graph by clicking on the Download button.",
			"_mppcb_header": "MPPCB (Pollution)",
			"_mppcb_li1": "Pollution department dashboard will display the details of mixture of gases and minerals with bifurcations.",
			"_industry_header": "Industrial (MPIDA)",
			"_industry_li1": "Industrial dashboard will display the details of Ward wise, sector wise, Ownership wise, type wise Industrial parks as follows:",
			"_industry_chart1": "Industrial Training Centers",
			"_industry_chart1_li1": "Zone Wise Industrial Training Centers",
			"_industry_chart2": "Industrial Park",
			"_industry_chart2_li1": "Zone Wise Industrial Park Area Distribution (%)",
			"_industry_li2": "User can also filter the data as per the ward.",
			"_industry_li3": "User can hover on each bar for more details about the graph.",
			"_industry_li4": "On clicking any of the chart the data will be plotted on map.",
			"_industry_li5": "User can increase the width of slider bar to increase the no. of bars in graph to be seen at that point of time.",
			"_industry_li6": "User can also download the graph by clicking on the Download button.",
			"_imc_header": "IMC",
			"_imc_li1": "IMC Dashboards displays as per Ward wise Dustbin location, Public toilets, Zone wise population, Sewer Network Information and much more as follows:",
			"_imc_chart1": "Litter Bin Locations",
			"_imc_chart1_li1": "Total Litter Bin Locations",
			"_imc_chart1_li2": "Ward Wise Litter Bin Locations",
			"_imc_chart2": "Public Toilets",
			"_imc_chart2_li1": "Total Public Toilets",
			"_imc_chart2_li2": "Ward Wise Public Toilets",
			"_imc_chart3": "Zone Wise Population",
			"_imc_chart4": "Sewer Network Information",
			"_imc_chart4_li1": "Total Sewers",
			"_imc_chart4_li2": "Diameter Wise Sewers (%)",
			"_imc_chart4_li3": "Ward Wise Sewer Length",
			"_imc_chart5": "Indore 311",
			"_imc_chart5_li1": "Category Wise Complaints",
			"_imc_chart5_li2": "Status Wise Complaints",
			"_imc_chart6": "Property Tax",
			"_imc_chart6_li1": "Construction Type Wise Property Tax",
			"_imc_chart6_li2": "Ward Wise Property Tax",
			"_imc_chart6_li3": "Ward Wise Building Details",
			"_imc_chart7": "ISWM",
			"_imc_chart7_li1": "GTS Wise Weight Collection",
			"_imc_chart7_li2": "Status Wise Vehicles",
			"_imc_li2": "User can also filter the data as per the ward, zone as well as date.",
			"_imc_li3": "User can hover on each bar for more details about the graph.",
			"_imc_li4": "On clicking any of the chart the data will be plotted on map.",
			"_imc_li5": "User can increase the width of slider bar to increase the no. of bars in graph to be seen at that point of time.",
			"_imc_li6": "User can also download the graph by clicking on the Download button.",
			"_land_header": "Land Record",
			"_land_li1": "Land Record Dashboard displays the land distribution of Indore City as follows:",
			"_land_chart1": "Agricultural Land",
			"_land_chart1_li1": "Zone Wise Agricultural Land",
			"_land_chart2": "Village Area",
			"_land_chart2_li1": "Zone Wise Village Area",
			"_land_chart3": "Open Space Area",
			"_land_chart3_li1": "Zone Wise Open Space Area",
			"_land_chart4": "Khasra Boundary",
			"_land_chart4_li1": "Zone Wise Khasra Distribution (%)",
			"_land_li2": "User can also filter the data as per the ward.",
			"_land_li3": "User can hover on each bar for more details about the graph.",
			"_land_li4": "On clicking any of the chart the data will be plotted on map.",
			"_land_li5": "User can increase the width of slider bar to increase the no. of bars in graph to be seen at that point of time.",
			"_land_li6": "User can also download the graph by clicking on the Download button.",
			"_smartCity_header": "Indore Smart City",
			"_smartCity_li1": "Indore Smart City Dashboard displays data related to the projects executed by Indore Smart City as follows:",
			"_smartCity_chart1": "Project Wise Cost",
			"_smartCity_chart2": "Zone Wise Projects",
			"_smartCity_chart3": "Category Wise Projects",
			"_cityMap_header": "City Map",
			"_cityMap_li1": "After login the map in 2D view will be shown.",
			"_language_header": "Language",
			"_language_li1": "User can select Hindi or English language from language selection from the right top corner.",
			"_language_li2": "If User selects Hindi, all information will be displayed in Hindi language only.",
			"_language_li3": "If user selects English language, all information will be displayed in English language only.",
			"_map_tools_header": "Map Tools",
			"_map_tools_globalSearch_header": "Global Search",
			"_map_tools_globalSearch_para1": "Search provides you with an opportunity to look up for features (e.g. Bus Stops, ATM, School, bank, government offices etc.) within a category and view their location on the map.",
			"_map_tools_globalSearch_li1": "Click on the down arrow on the search bar to select search category, type in the search term in the text box at the top left of the portal, as you type, you may see words begin to appear below the search box. These are auto-suggestions that may match what you’re interested in.",
			"_map_tools_globalSearch_li2": "As actual search result loads, click on the feature result to view location on the map and related information on the pop-up.",
			"_map_tools_zoomIn_header": "Zoom In",
			"_map_tools_zoomIn_para1": "Click on the Zoom in icon to view the map in detail. You can also use mouse scroll to zoom in to the map.",
			"_map_tools_zoomOut_header": "Zoom Out",
			"_map_tools_zoomOut_para1": "Click on the Zoom out icon to zoom out of the map. You can also use mouse scroll to zoom out to the map.",
			"_map_tools_home_header": "Home",
			"_map_tools_home_para1": "Click on the home icon to reset the map to its default extent. This function proves extremely helpful when you zoom in or out too much on the map and you can to return to your original landing page extent.",
			"_map_tools_myLocation_header": "My Location",
			"_map_tools_myLocation_para1": "On clicking the icon, a symbol displays on the map, showing your current location. The map extent is updated to show the current location as the area of interest.",
			"_map_tools_myLocation_para2": "The first time you visit Citizen Portal, you will have the option to allow or disallow the browser from sharing your location data. If you have denied the permission and would like to change the settings, follow the below steps to enable location sharing on your browser:",
			"_map_tools_myLocation_chromeHeader": "Google Chrome",
			"_map_tools_myLocation_chromeli1": "Open Chrome.",
			"_map_tools_myLocation_chromeli2": "At the top right, click More and then Settings.",
			"_map_tools_myLocation_chromeli3": "At the bottom, click Advanced.",
			"_map_tools_myLocation_chromeli4": "Under \"Privacy and security,\" click Content settings.",
			"_map_tools_myLocation_chromeli5": "Click Location.",
			"_map_tools_myLocation_chromeli6": "Turn Ask before accessing on or off.",
			"_map_tools_myLocation_ieHeader": "IE",
			"_map_tools_myLocation_ieli1": "In Internet Explorer, click/tap on Tools (Menu bar or gear icon) and Internet Options.",
			"_map_tools_myLocation_ieli2": "Click/tap on the Privacy tab",
			"_map_tools_myLocation_ieli3": "To Allow Websites to Request Your Location, Uncheck the Never allow websites to request your physical location box, click/tap on OK.",
			"_map_tools_myLocation_ieli4": "Close and reopen Internet Explorer to apply.",
			"_map_tools_myLocation_firefoxHeader": "Firefox",
			"_map_tools_myLocation_firefoxli1": "Go to the Tools menu, and then select Page Info.",
			"_map_tools_myLocation_firefoxli2": "Select the Permissions tab.",
			"_map_tools_myLocation_firefoxli3": "Change the setting for Share Location.",
			"_map_tools_myLocation_noteHeader": "Note:",
			"_map_tools_myLocation_note": "Current location is not supported in the Chrome via https due to Google’s privacy policy. Even in other browsers, the tool will only function when you let the website track your location.",
			"_map_tools_print_header": "Print",
			"_map_tools_print_para1": "Click on print to export and print files in PDF, PNG, JPG extensions. User can enter the title, file name and select page setup (A1 to A5), Orientation: Landscape/Portrait. User can include legends if required.",
			"_map_tools_measurement_header": "Measurement",
			"_map_tools_measurement_li1": "Click on the Measurement tool",
			"_map_tools_measurement_li2": "User can select this tool to measure any shape on the map. User can measure distance, area or find particular location of point by using this tool.",
			"_map_tools_measurement_li3": "User can also change the unit of measurement for Area, distance and location.",
			"_map_tools_measurement_li4": "To measure the length between any 2 points on the map; user can use the measure distance tool",
			"_map_tools_measurement_li5": "User can measure area by drawing a polygon on map by using Measure Area tool",
			"_map_tools_measurement_li6": "The find location tool under Measurement tool will let user find the location details of the selected point",
			"_map_tools_bookmark_header": "Bookmark",
			"_map_tools_bookmark_para1": "A spatial bookmark identifies a particular geographic location that you want to save and reference later. Bookmarks provide shortcuts to interesting places on a map. User can create a bookmark based on the current location and scale of the map. When other user clicks a bookmark, the map zooms to that location.",
			"_map_tools_bookmark_li1": "Click Bookmark icon from bottom left panel of the screen.",
			"_map_tools_bookmark_li2": "Zoom to the area on map which you frequently visit. For Example, if “Rajwada Palace” is one of your frequently mapped areas, search for it on map. Now, bookmark this map for later use. ",
			"_map_tools_bookmark_li3": "Add name for the bookmark and click on ‘+’ to add the bookmark. For example, type ‘Rajwada Palace’ to successfully create the bookmark for Rajwada Palace area.",
			"_map_tools_bookmark_li4": "When done, you can come later and click on the Rajwada Palace Area bookmark to view the map zoomed to the map extent and scale saved",
			"_map_tools_bookmark_li5": "Select the bookmark you want to delete and click on delete button to remove it from the system",
			"_map_tools_bookmark_noteHeader": "Note",
			"_map_tools_bookmark_note": "The Guest User will not be able to save the bookmark in the system.",
			"_map_tools_share_header": "Share",
			"_map_tools_share_para1": "User can share the link of the Indore GIS Portal with others by sending an email, posting on social media or embed it on a web page.",
			"_map_tools_share_li1": "Click on the Share button, and choose an option for sharing it.",
			"_map_tools_share_li2": "Copy the short URL and paste it into an email, blog, or website.",
			"_map_tools_share_li3": "Embed the map in a website.",
			"_map_tools_share_li4": "Click the Gmail, Facebook and Twitter buttons in the Share pop-up.",
			"_map_tools_csb_header": "Custom Scale bar",
			"_map_tools_csb_li1": "User can set scale Custom Scale bar from minimum value 100 to maximum value 100000.",
			"_map_tools_clearMap_header": "Clear Map",
			"_map_tools_clearMap_para1": "Click on the clear map to clear the any displayed result on map.",
			"_map_tools_swipeLayer_header": "Swipe Layer",
			"_map_tools_swipeLayer_li1": "The Swipe widget enables users to easily compare the content of different layers in a map by sliding the swipe tool",
			"_map_tools_kyc_header": "Know Your Coordinates",
			"_map_tools_kyc_para1": "User can plot the point on map by using Know Your Coordinates Tool &amp; zoom to the desired location",
			"_map_tools_kyc_li1": "User can either select Current Location button or select Location By Map Click to plot a point.",
			"_map_tools_kyc_li2": "Click on Go To",
			"_map_tools_kyc_li3": "The point will be plotted and map will be zoomed to that location",
			"_menu_header": "Menu",
			"_menu_para1": "Menu will be on the left panel of the page & you can hide or show the menu. From menu you can navigate to different modules.",
			"_menu_basemap_header": "Basemap Gallery",
			"_menu_basemap_li1": "You can view and select different type of maps",
			"_menu_basemap_li2": "On selection of the map will be displayed on the screen",
			"_menu_basemap_li3": "Base map consists of ISCDL Drone Image 2020, ISCDL Satellite Image 2015, Hybrid, Street Map & No Base map.",
			"_menu_basemap_li4": "User can view any of the base maps in one click.",
			"_menu_layers_header": "Layers",
			"_menu_layers_para1": "A group layer is collection of all features /facilities that fall within a category. You can select layer to view its related data to find out location(s) and information of particular features/facilities.",
			"_menu_layers_li1": "Click layers from left hand side menu bar of citizen portal.",
			"_menu_layers_li2": "On the widget you can view and expand all the group layer categories listed",
			"_menu_layers_li3": "By clicking the Layer, user can view list of layers such as: Building, Divider, Electric Pole, Street Light, Tree etc.",
			"_menu_layers_li4": "Layer will be visible on map by clicking on it from the layer panel.",
			"_menu_query_header": "Query",
			"_menu_query_para1": "The power of geographic analysis is the ability to ask and answer questions about geographic features and their attributes and the relationship between them.",
			"_menu_query_basicQuery_header": "Basic Query",
			"_menu_query_basicQuery_para1": "User needs to perform following actions to view a particular attribute query:",
			"_menu_query_basicQuery_li1": "Select Layer",
			"_menu_query_basicQuery_li2": "Select Field Type – Depending upon the layer selected it may vary",
			"_menu_query_basicQuery_li3": "Select Value – from dropdown",
			"_menu_query_basicQuery_li4": "Select Ward",
			"_menu_query_basicQuery_li5": "Click on Search",
			"_menu_query_adQuery_header": "Advanced Query",
			"_menu_query_adQuery_para1": "User can select records from the database by applying set (less than, greater than, equal to & not equal to) or Boolean algebra (and, or, like & not). User needs to perform following actions to view a particular attribute query:",
			"_menu_query_adQuery_li1": "Select Ward",
			"_menu_query_adQuery_li2": "Select Layer",
			"_menu_query_adQuery_li3": "Select Field Type – Depending upon the layer selected it may vary",
			"_menu_query_adQuery_li4": "Select Logical Operators – Depending upon the Field Type selected it may vary",
			"_menu_query_adQuery_li5": "Select Value – from dropdown",
			"_menu_query_adQuery_li6": "Click on Search",
			"_menu_query_para2": "Based on selected data searched results will be shown which can be viewed on map.",
			"_menu_query_noteHeader": "Note:",
			"_menu_query_note": "In case user wants to perform multiple attribute query they can do so by clicking on “+” button.",
			"_menu_query_spQuery_header": "Spatial Query",
			"_menu_query_spQuery_para1": "It is the process of selecting features based on their geographic relationship, or spatial relationship, to other features. User can perform the spatial query as follows:",
			"_menu_query_spQuery_li1": "Select Ward",
			"_menu_query_spQuery_li2": "Select Source Layer",
			"_menu_query_spQuery_li3": "Select Query Type",
			"_menu_query_spQuery_li4": "Select Mask Layer",
			"_menu_query_spQuery_li5": "Click on Search",
			"_menu_query_spQuery_para2": "Based on selected data searched results will be shown which can be viewed on map.",
			"_menu_userMgmt_header": "User Management",
			"_menu_userMgmt_para1": "User can manage users and roles from this module. Click on User management from the menu.",
			"_menu_userMgmt_deptMaster_header": "Department Master",
			"_menu_userMgmt_deptMaster_li1": "List of departments will be shown in grid. You can edit or delete the department from Action column.",
			"_menu_userMgmt_deptMaster_li2": "User can search the department from the list. Departments can be exported to Excel by clicking on Export to Excel button and PDF by clicking on Export to PDF button.",
			"_menu_userMgmt_deptMaster_li3": "Admin can change or update the details of each department",
			"_menu_userMgmt_roleMaster_header": "Role Master",
			"_menu_userMgmt_roleMaster_li1": "List of roles will be shown in grid. Admin can edit or delete the role from Action column.",
			"_menu_userMgmt_roleMaster_li2": "User can search the roles from the list. Roles can be exported to Excel by clicking on Export to Excel button and PDF by clicking on Export to PDF button.",
			"_menu_userMgmt_roleMaster_li3": "To add new roles click on Add Role and do the following",
			"_menu_userMgmt_roleMaster_li31": "Click on Add role button",
			"_menu_userMgmt_roleMaster_li32": "Select Department",
			"_menu_userMgmt_roleMaster_li33": "Enter Role Name",
			"_menu_userMgmt_roleMaster_li34": "Provide rights of the already existing modules by checking the checkboxes",
			"_menu_userMgmt_roleMaster_li35": "Select Role Type",
			"_menu_userMgmt_roleMaster_li36": "Click on Save",
			"_menu_userMgmt_roleMaster_li37": "Role will be added and will appear in the list",
			"_menu_userMgmt_userMaster_header": "User Master",
			"_menu_userMgmt_userMaster_li1": "On clicking User Master; user will be navigated to List of users shown in grid.",
			"_menu_userMgmt_userMaster_li2": "User can edit or delete the role from Action column. Admin user can search the users from the list.",
			"_menu_userMgmt_userMaster_li3": "Users can be exported to Excel by clicking on Export to Excel button and PDF by clicking on Export to PDF button.",
			"_menu_userMgmt_userMaster_li4": "To add new user click on Add New Users and do the following",
			"_menu_userMgmt_userMaster_li41": "In popup, enter Name.",
			"_menu_userMgmt_userMaster_li42": "Enter Mobile number.",
			"_menu_userMgmt_userMaster_li43": "Enter Email.",
			"_menu_userMgmt_userMaster_li44": "Select Department.",
			"_menu_userMgmt_userMaster_li45": "Set password for this user.",
			"_menu_userMgmt_userMaster_li46": "Select Role from the dropdown.",
			"_menu_userMgmt_userMaster_li47": "Click on Save.",
			"_menu_userMgmt_userMaster_li48": "User will be added and it will appear in list.",
			"_menu_citizenServices_header": "Citizen Services",
			"_menu_event_header": "Event Management",
			"_menu_event_para1": "User can add event and manage event details from Event Management Module",
			"_menu_event_li1": "Authorized user can view the details of the event to be conducted & can approve or reject the event based on the details provided.",
			"_menu_event_li2": "User can search the event from the list. Events can be exported to Excel by clicking on Export to Excel button and PDF by clicking on Export to PDF button.",
			"_menu_event_li3": "User can also add event by clicking on Add Event Button",
			"_menu_announcement_header": "Announcement",
			"_menu_announcement_addHeader": "Add Announcement",
			"_menu_announcement_addli1": "Select Department",
			"_menu_announcement_addli2": "Enter Announcement Title.",
			"_menu_announcement_addli3": "Enter Announcement Description.",
			"_menu_announcement_addli4": "Select Announcement date and time.",
			"_menu_announcement_addli5": "Plot a point a map to get the longitude and latitude.",
			"_menu_announcement_addli6": "Click on Submit.",
			"_menu_announcement_addli7": "In case you want to remove the data entered click on Clear.",
			"_menu_announcement_viewHeader": "View Announcement",
			"_menu_announcement_viewpara1": "List of announcements will be shown in this tab. The location details related to announcement can also be viewed on map.",
			"_menu_feedback_header": "Feedback & Suggestions",
			"_menu_feedback_feedback_header": "Feedback",
			"_menu_feedback_li1": "On clicking Feedback & Suggestions user will be navigated to Feedback Page where he/she can view the list of feedbacks received from the citizens of ISCDL.",
			"_menu_feedback_li2": "To provide response on the received feedback admin has to click on the Add Response & Popup will be shown with feedback details, scroll down and add your response in Response field.",
			"_menu_feedback_li3": "You can search the feedback from the list. Feedback can be deleted by clicking on Delete icon from Action column. Feedbacks can be exported to Excel by clicking on Export to Excel button and PDF by clicking on Export to PDF button.",
			"_menu_suggestion_header": "Suggestions",
			"_menu_suggestion_li1": "On clicking the Suggestion Tab from the Feedback page user will be redirected to Suggestions Page where he/she can view the list of suggestions received from the citizens of ISCDL.",
			"_menu_suggestion_li2": "To provide response on the received suggestion admin has to click on the Add Response & Popup will be shown with suggestion details, scroll down and add your response in Response field.",
			"_menu_suggestion_li3": "You can search the suggestions from the list. Suggestions can be deleted by clicking on Delete icon from Action column. Suggestions can be exported to Excel by clicking on Export to Excel button and PDF by clicking on Export to PDF button.",
			"_menu_complaint_header": "Complaints",
			"_menu_complaint_li1": "On clicking Complaint Tab user can view the list of complaints received from the citizens of ISCDL.",
			"_menu_complaint_li2": "To provide response on the received complaints; admin has to click on the Add Response & Popup will be shown with complaint details, scroll down and add your response in Response field.",
			"_menu_complaint_li3": "You can search the complaints from the list. Complaints can be deleted by clicking on Delete icon from Action column. Complaints can be exported to Excel by clicking on Export to Excel button and PDF by clicking on Export to PDF button.",
			"_menu_citizenMaster_header": "Citizen Master Data",
			"_menu_citizenMaster_para1": "All registered citizen information will be shown. Click on Citizen Master data from the menu.",
			"_menu_citizenMaster_para2": "List of citizens will be shown with Username, Name, Email, Phone number, Address and Status. User can search the citizen from the list. Citizen list can be exported to Excel by clicking on Export to Excel button and PDF by clicking on Export to PDF button.",
			"_menu_adServices_header": "Advanced Services",
			"_menu_addData_header": "Add Data",
			"_menu_addData_para1": "To add a new place which is not on map, Authorized user can click on add place from the menu.",
			"_menu_addData_li1": "Enter the Name",
			"_menu_addData_li2": "Select Image",
			"_menu_addData_li3": "Plot a location on map by clicking on pin icon",
			"_menu_addData_li4": "Enter remarks for the place.",
			"_menu_addData_li5": "Click on “Submit” button. ",
			"_menu_addData_li6": "The added details will display on the map after the approval of specific department user. GIS cell will update the data on the map.",
			"_menu_addLayer_header": "Add Layer",
			"_menu_addLayer_li1": "User can add layers from “Add Layer” Module.",
			"_menu_addLayer_li2": "User can add shapefile by selecting zipped folder which contain valid file format (.shp, .shx etc.) or can add KML by selecting .kml or .kmz file format.",
			"_menu_addLayer_li3": "Click on Submit after selecting the file.",
			"_menu_addLayer_li4": "The added data will be plotted on map.",
			"_menu_addLayer_li5": "Other types of files are not allowed & system will pop up error if invalid file is uploaded.",
			"_menu_proximity_header": "Proximity Analysis",
			"_menu_proximity_para1": "User can search a particular utility by selecting the layer from the dropdown. After selecting the layer user needs to draw a polygon on the map.",
			"_menu_proximity_para2": "It will search the selected layer in the drawn polygon and the details will be displayed on map.",
			"_menu_proximity_para3": "Click on Zoom to Feature to view the result on map",
			"_menu_heatMap_header": "Heat Map Analysis",
			"_menu_heatMap_para1": "Heat Map analysis is a graphical representation of data that visualizes the density of points in a layer. This helps the department in better planning of the services within the city.",
			"_menu_heatMap_li1": "Select the Department from the drop down",
			"_menu_heatMap_li2": "Select criteria on the basis of which you want to generate heat map",
			"_menu_heatMap_li3": "Click on Generate Heat Map",
			"_menu_pm_header": "Project Monitoring",
			"_menu_pm_manageProject_header": "Manage Project",
			"_menu_pm_manageProject_project": "Projects",
			"_menu_pm_manageProject_li1": "In Projects tab, list of projects will be shown. User can edit the information by clicking on Edit icon from the Action column.",
			"_menu_pm_manageProject_li2": "User can search the project from the list. Project list can be exported to Excel by clicking on Export to Excel button and PDF by clicking on Export to PDF button.",
			"_menu_pm_manageProject_li3": "User can add new project.",
			"_menu_pm_manageProject_li31": "Enter all the details in one by one and click on next to go to next details.",
			"_menu_pm_manageProject_li32": "At last after filling all details click on Submit.",
			"_menu_pm_manageProject_li33": "Project details will added and appear in project list.",
			"_menu_pm_milestone_header": "Milestones",
			"_menu_pm_milestone_li1": "In Milestone tab, list of milestones for a project will be shown. Select a project from the dropdown. Milestone information will be shown in grid. User can edit the information by clicking on Edit icon from the Action column.",
			"_menu_pm_milestone_li2": "User can search the milestone from the list. Milestone list can be exported to Excel by clicking on Export to Excel button and PDF by clicking on Export to PDF button.",
			"_menu_pm_milestone_li3": "User can also add a milestone for a particular project by clicking on Add Milestone",
			"_menu_projectReports_header": "Project Reports",
			"_menu_projectReports_li1": "List of projects and its status will be displayed here",
			"_menu_projectReports_li2": "User can navigate to the projects location by clicking on show to map.",
			"_menu_projectAlerts_header": "Project Alerts",
			"_menu_ftl_header": "From – To Location",
			"_menu_ftl_para1": "User can get directions between two locations by entering the Source and Destination.",
			"_menu_ftl_li1": "User can find the source & destination address by typing it in the auto complete box.",
			"_menu_ftl_li2": "Users can also “Set Source by Plotting Point” or “Set Current Location” with the help of Icons given in the box.",
			"_menu_ftl_li3": "On click of “Apply” it will show directions from source to destination on the map.",
			"_menu_reports_header": "Reports",
			"_menu_reports_para1": "User can generate various reports based on the selection of the department he is interested in.",
			"_menu_reports_para2": "Ward wise filter can be applied in the reports",
			"_menu_reports_para3": "Any data selected from the table will be highlighted on map. Various other options are also provided which can be used by the user.",
			"_menu_poi_header": "POI Data",
			"_menu_poi_para1": "Data collected from the POI Mobile Application will be shown in the web portal. User can filter data as per the department, POI type, date.",
			"_menu_help_header": "Help",
			"_menu_help_para1": "This page will show the information about how to use the portal.",
			"_3d_map_header": "3D Map",
			"_3d_map_li1": "After selecting “3D” on City GIS map the map in 3D view will be shown.",
			"_3d_map_li2": "3D Map consist of Main menu- Base Map Gallery, Layers Draw Tool, Heritage Building Tool, LiDAR, Proximity Analysis and other map tools.",
			"_3d_mapTools_header": "Map Tools",
			"_3d_mapTools_para1": "All the map tools present in 2D Map are available in 3D Map. Some of the additional tools in 3D are as follows:",
			"_3d_mapTools_li1": "Toggle to Pan or Rotate in 3D",
			"_3d_mapTools_li2": "Reset Compass Orientation",
			"_3d_basemap_header": "Base Map Gallery",
			"_3d_basemap_li1": "User can view and select different type of maps",
			"_3d_basemap_li2": "On selection of the map will be displayed on the screen",
			"_3d_basemap_li3": "Base map consists of ISCDL Drone Image, ISCDL Satellite Image 2015, Dark grey canvas, Imagery, Imagery Hybrid, Light grey canvas, Navigation map, Oceans, Streets (Night), Street Map, Terrain with labels, Topographic world.",
			"_3d_basemap_li4": "User can view any of the base maps in one click.",
			"_3d_layers_header": "Layers",
			"_3d_layers_para1": "A group layer is collection of all features /facilities that fall within a category. You can select layer to view its related data to find out location(s) and information of particular features/facilities.",
			"_3d_layers_li1": "Click layers from left hand side menu bar of citizen portal.",
			"_3d_layers_li2": "On the widget you can view and expand all the group layer categories listed",
			"_3d_layers_li3": "By clicking the Layer, user can view list of layers such as: Building, Divider, Electric Pole, Street Light, Tree etc.",
			"_3d_layers_li4": "Layer will be visible on map by clicking on it from the layer panel.",
			"_3d_drawTool_header": "Draw Tool",
			"_3d_drawTool_para1": "You can get the drawing tool from the Menu in left panel of the Portal.",
			"_3d_drawTool_li1": " Select the type of draw mode you want to use from the Drawing tool.",
			"_3d_drawTool_li2": "Different type of draw modes is available such as Point, Polyline and Polygon.",
			"_3d_drawTool_li3": "For example, when you click on the Line string button, the tool activates the line geometry.",
			"_3d_drawTool_li4": "Move the mouse pointer over the map and click to add graphic/geometry on the map.",
			"_3d_drawTool_li5": "You can now view the graphic/geometry on the map, and also print this.",
			"_3d_drawTool_li6": "You can clear, undo and Redo from option available.",
			"_3d_drawTool_noteHeader": "Note:",
			"_3d_drawTool_note": "Some graphics may require more than one click or a click and drag.",
			"_3d_heritage_header": "Heritage Building",
			"_3d_heritage_para1": "Users can view the list of heritage buildings present in Indore City.",
			"_3d_heritage_li1": "From the layer panel they can switch on/off any of the heritage building they wish to see",
			"_3d_heritage_li2": "Zoom to Feature will zoom to the particular heritage building",
			"_3d_heritage_li3": "User can also switch on the Drone Image to view as a base layer for the selected heritage building.",
			"_3d_lidar_header": "LiDAR",
			"_3d_lidar_para1": "Department users can view the LiDAR data of Indore City.",
			"_3d_lidar_li1": "From the menu click on LiDAR and it will redirect the user to LiDAR Dashboard.",
			"_3d_lidar_li2": "User can measure the height of any building using the measure area tool.",
			"_3d_lidar_li3": "User can also measure distance between two points which is more accurate.",
			"_3d_attrQuery_header": "Attribute Query",
			"_3d_attrQuery_para1": "Department users can perform attribute query on road and building layers",
			"_3d_attrQuery_li1": "Select Attribute Query from menu",
			"_3d_attrQuery_li2": "Select Layer from drop down",
			"_3d_attrQuery_li3": "Select field from drop down",
			"_3d_attrQuery_li4": "Apply Logical Operator",
			"_3d_attrQuery_li5": "Select Value from drop down",
			"_3d_issue_header": "Reported Issues",
			"_3d_issue_para1": "Department users can view any issues if reported in any department in 3D",
			"_3d_issue_li1": "Select Department from drop down",
			"_3d_issue_li2": "Select the issue you want to view",
			"_3d_issue_li3": "Click on Submit",
			"_3d_proximity_header": "Proximity Analysis",
			"_3d_proximity_li1": "Select layer from drop down",
			"_3d_proximity_li2": "Draw polygon on map",
			"_3d_proximity_li3": "The buildings or road falling in that polygon will be displayed in the results tab",
			"_3d_proximity_li4": "On click of Zoom to Feature it will be highlighted & zoomed on map.",
			
			
		},
		"hindi" : {
			
			"_indore_header": "इंदौर स्मार्ट मैप",
			"_app_overview": "एप्लीकेशन अवलोकन",
			"_app_ov_loginScreen": "प्रवेश पट",
			"_app_ov_centralDashboard": "सेंट्रल डैशबोर्ड",
			"_app_ov_cityMap": "शहर का नक्शा",
			"_app_ov_language": "भाषा",
			"_app_ov_mapTools": "नक्शा उपकरण",
			"_app_ov_mt_globalSearch": "वैश्विक खोज",
			"_app_ov_mt_zoomInOut": "ज़ूम इन और आउट",
			"_app_ov_mt_myLocation": "माय लोकेशन",
			"_app_ov_mt_print": "प्रिंट",
			"_app_ov_mt_measurement": "माप",
			"_app_ov_mt_clearMap": "क्लियर मैप",
			"_app_ov_mt_bookmark": "बुकमार्क",
			"_app_ov_menu": "मेन्यू",
			"_app_ov_menu_baseMapGallery": "बेस मैप गैलरी",
			"_app_ov_menu_layers": "लेयर्स",
			"_app_ov_menu_query": "प्रश्न",
			"_app_ov_menu_drawTool": "ड्राइंग टूल",
			"_app_ov_menu_proximityAnalysis": "निकटता विश्लेषण",
			"_app_ov_menu_projectMonitoring": "परियोजना की निगरानी",
			"_app_ov_menu_projectAlerts": "प्रोजेक्ट अलर्ट",
			"_app_ov_menu_reports": "रिपोर्ट",
			"_app_ov_menu_poiData": "POI डेटा",
			"_app_ov_3dMap": "3डी नक्शा",
			"_help_for_dept": "सिटी एंटरप्राइज जीआईएस पोर्टल: विभागीय उपयोगकर्ता",
			"_login_screen_header": "लॉगइन करें",
			"_login_screen_para1": "विभाग उपयोगकर्ता व्यवस्थापक द्वारा प्रदान किए गए मान्य उपयोगकर्ता नाम और पासवर्ड के साथ लॉगिन कर सकता है",
			"_login_screen_para2": "अगर आप अपना पासवर्ड भूल जाते हैं तो पासवर्ड भूल गए लिंक पर क्लिक करें।",
			"_central_dashboard_header": "सेंट्रल डैशबोर्ड",
			"_central_dashboard_para1": "सुपर एडमिन / जीआईएस सेल द्वारा लॉगिन करने के बाद, व्यवस्थापक उपयोगकर्ता केंद्रीय डैशबोर्ड को विभिन्न विभाग संचयी जानकारी के साथ देख सकता है। उस पर क्लिक करके, उपयोगकर्ता को अधिक विवरण के लिए संबंधित विभाग के डैशबोर्ड पर पुनर्निर्देशित किया जाएगा।",
			"_central_dashboard_para2": "सुपर एडमिन सेंट्रल डैशबोर्ड पर विभाग की निम्न जानकारी देख सकेगा।",
			"_central_dashboard_aictsl": "AICTSL - बस स्टॉप की कुल संख्या",
			"_central_dashboard_electric": "MPKVVCL - स्ट्रीट लाइट की कुल संख्या",
			"_central_dashboard_police": "पुलिस - पुलिस स्टेशन की कुल संख्या",
			"_central_dashboard_tcplanning": "टाउन एंड कंट्री प्लानिंग - वर्ग किमी में कुल टाउन प्लानिंग एरिया",
			"_central_dashboard_ida": "आईडीए - आईडीए योजनाओं की कुल संख्या",
			"_central_dashboard_health": "स्वास्थ्य - अस्पतालों की कुल संख्या",
			"_central_dashboard_phe": "PHE शहरी - पानी की लाइनों की कुल लंबाई (k.m.)",
			"_central_dashboard_pwd": "पीडब्ल्यूडी - सड़कों की कुल संख्या",
			"_central_dashboard_education": "शिक्षा विभाग - स्कूलों की कुल संख्या",
			"_central_dashboard_wcwd": "महिला और बाल कल्याण - कुल सं। आंगनवाड़ी की",
			"_central_dashboard_mppcb": "MPPCB (प्रदूषण) - AQI की संख्या - PM 2.5",
			"_central_dashboard_industry": "MPAKVN - कुल औद्योगिक भूमि (वर्ग किमी)",
			"_central_dashboard_imc": "IMC- लिटर बिन लोकेशन",
			"_central_dashboard_smartCity": "इंदौर स्मार्ट सिटी - परियोजनाओं की कुल संख्या",
			"_aictsl_header": "AICTSL",
			"_aictsl_li1": "AICTSL विभाग डैशबोर्ड इंदौर शहर में काम करने वाली बसों की कुल संख्या प्रदर्शित करेगा।",
			"_aictsl_li2": "उपयोगकर्ता इस तरह की रिपोर्ट पर नेविगेट कर सकते हैं:",
			"_aictsl_chart1": "बस के मार्ग",
			"_aictsl_chart1_li1": "बस रूट वाइज काउंट",
			"_aictsl_chart1_li2": "कुल बस रूट",
			"_aictsl_chart2": "बस रूकने की जगह",
			"_aictsl_chart2_li1": "वार्ड वार बस स्टॉप की गिनती",
			"_aictsl_chart2_li2": "कुल बस स्टॉप",
			"_aictsl_chart3": "AFCS",
			"_aictsl_chart3_li1": "उपकरण प्रकार वार संग्रह राशि",
			"_aictsl_li3": "उपयोगकर्ता वार्ड के अनुसार डेटा को फ़िल्टर भी कर सकता है",
			"_aictsl_li4": "उपयोगकर्ता ग्राफ के बारे में अधिक जानकारी के लिए प्रत्येक पट्टी पर होवर कर सकता है।",
			"_aictsl_li5": "किसी भी चार्ट पर क्लिक करने पर डेटा को मैप पर प्लॉट किया जाएगा।",
			"_aictsl_li6": "उपयोगकर्ता उस समय देखे जाने वाले ग्राफ़ में पट्टियों की संख्या को बढ़ाने के लिए स्लाइडर बार की चौड़ाई बढ़ा सकता है।",
			"_aictsl_li7": "उपयोगकर्ता डाउनलोड बटन पर क्लिक करके ग्राफ भी डाउनलोड कर सकते हैं।",
			"_electric_header": "विद्युतीय",
			"_electric_li1": "विद्युत डैशबोर्ड विद्युत विभाग का पूरा डेटा प्रदर्शित करेगा जैसे:",
			"_electric_chart1": "स्ट्रीट लाईट",
			"_electric_chart1_li1": "कुल स्ट्रीट लाइट",
			"_electric_chart1_li2": "वार्ड वाइज स्ट्रीट लाइट",
			"_electric_chart2": "ट्रान्सफ़ॉर्मर",
			"_electric_chart2_li1": "कुल ट्रांसफार्मर",
			"_electric_chart2_li2": "वार्ड वाइज ट्रांसफॉर्मर",
			"_electric_chart3": "स्मार्ट एलईडी",
			"_electric_chart3_li1": "कुल स्मार्ट एलईडी",
			"_electric_chart3_li2": "वार्ड वाइज स्मार्ट एलईडी",
			"_electric_chart3_li3": "वाट वार स्मार्ट एलईडी वितरण (%)",
			"_electric_li2": "उपयोगकर्ता वार्ड के अनुसार डेटा को फ़िल्टर भी कर सकता है।",
			"_electric_li3": "उपयोगकर्ता ग्राफ के बारे में अधिक जानकारी के लिए प्रत्येक पट्टी पर होवर कर सकता है।",
			"_electric_li4": "किसी भी चार्ट पर क्लिक करने पर डेटा को मैप पर प्लॉट किया जाएगा।",
			"_electric_li5": "उपयोगकर्ता उस समय देखे जाने वाले ग्राफ में पट्टियों की संख्या को बढ़ाने के लिए स्लाइडर बार की चौड़ाई बढ़ा सकता है।",
			"_electric_li6": "उपयोगकर्ता डाउनलोड बटन पर क्लिक करके ग्राफ भी डाउनलोड कर सकते हैं।",
			"_police_header": "पुलिस",
			"_police_li1": "पुलिस डैशबोर्ड पुलिस विभाग से संबंधित डेटा प्रदर्शित करेगा जिसमें निम्नलिखित शामिल हैं:",
			"_police_chart1": "पुलिस स्टेशन",
			"_police_chart1_li1": "कुल पुलिस स्टेशन",
			"_police_chart1_li2": "जोन वाइज पुलिस स्टेशन",
			"_police_chart1_li3": "पुलिस स्टेशन वार सड़क दुर्घटनाओं की संख्या",
			"_police_chart1_li4": "दुर्घटनाओं में चोट की प्रकृति (%)",
			"_police_chart1_li5": "दुर्घटनाओं में शामिल वाहन प्रकार (%)",
			"_police_chart1_li6": "सड़क श्रेणी वार दुर्घटना गणना (%)",
			"_police_chart1_li7": "पुलिस स्टेशन वार वाहन चोरी की घटनाएं",
			"_police_li2": "उपयोगकर्ता वार्ड के अनुसार डेटा को फ़िल्टर भी कर सकता है।",
			"_police_li3": "उपयोगकर्ता ग्राफ के बारे में अधिक जानकारी के लिए प्रत्येक पट्टी पर होवर कर सकता है।",
			"_police_li4": "किसी भी चार्ट पर क्लिक करने पर डेटा को मैप पर प्लॉट किया जाएगा।",
			"_police_li5": "उपयोगकर्ता उस समय देखे जाने वाले ग्राफ में पट्टियों की संख्या को बढ़ाने के लिए स्लाइडर बार की चौड़ाई बढ़ा सकता है।",
			"_police_li6": "उपयोगकर्ता डाउनलोड बटन पर क्लिक करके ग्राफ भी डाउनलोड कर सकते हैं।",
			"_tcplanning_header": "टाउन एंड कंट्री प्लानिंग",
			"_tcplanning_li1": "टाउन प्लानिंग डैशबोर्ड निम्नलिखित डेटा प्रदर्शित करेगा:",
			"_tcplanning_chart1": "टाउन प्लानिंग एरिया",
			"_tcplanning_chart1_li1": "भूमि उपयोग वितरण (%)",
			"_tcplanning_chart1_li2": "वाणिज्यिक क्षेत्र में अनुमानित विकास दर (2020 से 2031 तक)",
			"_tcplanning_chart1_li3": "आवासीय क्षेत्र में अनुमानित विकास दर (2020 से 2031 तक)",
			"_tcplanning_li2": "उपयोगकर्ता वार्ड के अनुसार डेटा को फ़िल्टर भी कर सकता है।",
			"_tcplanning_li3": "उपयोगकर्ता ग्राफ के बारे में अधिक जानकारी के लिए प्रत्येक पट्टी पर होवर कर सकता है।",
			"_tcplanning_li4": "किसी भी चार्ट पर क्लिक करने पर डेटा को मैप पर प्लॉट किया जाएगा।",
			"_tcplanning_li5": "उपयोगकर्ता उस समय देखे जाने वाले ग्राफ में पट्टियों की संख्या को बढ़ाने के लिए स्लाइडर बार की चौड़ाई बढ़ा सकता है।",
			"_tcplanning_li6": "उपयोगकर्ता डाउनलोड बटन पर क्लिक करके ग्राफ भी डाउनलोड कर सकते हैं।",
			"_ida_header": "IDA",
			"_ida_li1": "आईडीए डैशबोर्ड नगर नियोजन योजनाओं की कुल संख्या को निम्नानुसार प्रदर्शित करेगा:",
			"_ida_chart1": "स्थिति वार कुल टीपी योजनाएं",
			"_ida_chart1_li1": "कुल टीपी योजनाएं",
			"_ida_chart2": "विकसित योजनाएँ",
			"_ida_chart2_li1": "कुल विकसित योजनाएं",
			"_ida_chart3": "प्रस्तावित योजनाएं",
			"_ida_chart3_li1": "कुल प्रस्तावित योजनाएं",
			"_ida_li2": "उपयोगकर्ता वार्ड के अनुसार डेटा को फ़िल्टर भी कर सकता है।",
			"_ida_li3": "उपयोगकर्ता ग्राफ के बारे में अधिक जानकारी के लिए प्रत्येक पट्टी पर होवर कर सकता है।",
			"_ida_li4": "किसी भी चार्ट पर क्लिक करने पर डेटा को मैप पर प्लॉट किया जाएगा।",
			"_ida_li5": "उपयोगकर्ता उस समय देखे जाने वाले ग्राफ में पट्टियों की संख्या को बढ़ाने के लिए स्लाइडर बार की चौड़ाई बढ़ा सकता है।",
			"_ida_li6": "उपयोगकर्ता डाउनलोड बटन पर क्लिक करके ग्राफ भी डाउनलोड कर सकते हैं।",
			"_health_header": "स्वास्थ्य",
			"_health_li1": "हेल्थ डैशबोर्ड इंदौर शहर में उपलब्ध स्वास्थ्य सुविधाओं को निम्नानुसार प्रदर्शित करेगा:",
			"_health_chart1": "अस्पताल",
			"_health_chart1_li1": "कुल अस्पताल",
			"_health_chart1_li2": "स्वामित्व प्रकार वार अस्पताल",
			"_health_chart1_li3": "अस्पताल के जानकार आई.सी.यू.",
			"_health_chart1_li4": "आपातकालीन सेवाएं (%)",
			"_health_chart1_li5": "ब्लड बैंक सुविधा (%)",
			"_health_chart1_li6": "मुर्दाघर (%)",
			"_health_chart1_li7": "वार्ड वार अस्पताल",
			"_health_chart2": "फार्मेसी",
			"_health_chart2_li1": "कुल फार्मासिस्ट",
			"_health_chart2_li2": "वार्ड वार फार्मासिस्ट",
			"_health_li2": "उपयोगकर्ता वार्ड के अनुसार डेटा को फ़िल्टर भी कर सकता है।",
			"_health_li3": "उपयोगकर्ता ग्राफ के बारे में अधिक जानकारी के लिए प्रत्येक पट्टी पर होवर कर सकता है।",
			"_health_li4": "किसी भी चार्ट पर क्लिक करने पर डेटा को मैप पर प्लॉट किया जाएगा।",
			"_health_li5": "उपयोगकर्ता उस समय देखे जाने वाले ग्राफ में पट्टियों की संख्या को बढ़ाने के लिए स्लाइडर बार की चौड़ाई बढ़ा सकता है।",
			"_health_li6": "उपयोगकर्ता डाउनलोड बटन पर क्लिक करके ग्राफ भी डाउनलोड कर सकते हैं।",
			"_phe_header": "जन स्वास्थ्य एवं अभियांत्रिकी (शहरी)",
			"_phe_li1": "सार्वजनिक स्वास्थ्य इंजीनियरिंग डैशबोर्ड पानी की आपूर्ति लाइन (किमी) की कुल लंबाई, ट्यूबवेल और पानी के वाल्वों की कुल गणना निम्नानुसार प्रदर्शित करेगा:",
			"_phe_chart1": "जल आपूर्ति लाइन (ABD क्षेत्र)",
			"_phe_chart1_li1": "कुल जल रेखा की लंबाई (मीटर में)",
			"_phe_chart1_li2": "व्यास के हिसाब से पानी की आपूर्ति (मिमी)",
			"_phe_chart1_li3": "वार्ड वार जल आपूर्ति लंबाई (mt)",
			"_phe_chart2": "पानी के वाल्व (ABD क्षेत्र)",
			"_phe_chart2_li1": "कुल पानी की वाल्व",
			"_phe_chart2_li2": "वार्ड समझदार पानी के वाल्व",
			"_phe_li2": "उपयोगकर्ता वार्ड के अनुसार डेटा को फ़िल्टर भी कर सकता है।",
			"_phe_li3": "उपयोगकर्ता ग्राफ के बारे में अधिक जानकारी के लिए प्रत्येक पट्टी पर होवर कर सकता है।",
			"_phe_li4": "किसी भी चार्ट पर क्लिक करने पर डेटा को मैप पर प्लॉट किया जाएगा।",
			"_phe_li5": "उपयोगकर्ता उस समय देखे जाने वाले ग्राफ में पट्टियों की संख्या को बढ़ाने के लिए स्लाइडर बार की चौड़ाई बढ़ा सकता है।",
			"_phe_li6": "उपयोगकर्ता डाउनलोड बटन पर क्लिक करके ग्राफ भी डाउनलोड कर सकते हैं।",
			"_pwd_header": "लोक निर्माण विभाग",
			"_pwd_li1": "पीडब्लूडी विभाग डैशबोर्ड इंदौर शहर के सड़क नेटवर्क विवरण को निम्नानुसार प्रदर्शित करेगा:",
			"_pwd_chart1": "रोडवेज",
			"_pwd_chart1_li1": "कुल सड़क की लंबाई (किमी)",
			"_pwd_chart1_li2": "टाइप वाइज रोड की लंबाई (किमी)",
			"_pwd_chart1_li3": "सतही प्रकार वार रोड की लंबाई (किमी)",
			"_pwd_chart2": "पुल",
			"_pwd_chart2_li1": "कुल पुल",
			"_pwd_chart2_li2": "वार्ड वार पुल",
			"_pwd_li2": "उपयोगकर्ता वार्ड के अनुसार डेटा को फ़िल्टर भी कर सकता है।",
			"_pwd_li3": "उपयोगकर्ता ग्राफ के बारे में अधिक जानकारी के लिए प्रत्येक पट्टी पर होवर कर सकता है।",
			"_pwd_li4": "किसी भी चार्ट पर क्लिक करने पर डेटा को मैप पर प्लॉट किया जाएगा।",
			"_pwd_li5": "उपयोगकर्ता उस समय देखे जाने वाले ग्राफ में पट्टियों की संख्या को बढ़ाने के लिए स्लाइडर बार की चौड़ाई बढ़ा सकता है।",
			"_pwd_li6": "उपयोगकर्ता डाउनलोड बटन पर क्लिक करके ग्राफ भी डाउनलोड कर सकते हैं।",
			"_education_header": "शिक्षा",
			"_education_li1": "एजुकेशन डैशबोर्ड इंदौर शहर में उपलब्ध शिक्षा के बुनियादी ढांचे को निम्नानुसार प्रदर्शित करेगा:",
			"_education_chart1": "प्राथमिक विद्यालय",
			"_education_chart1_li1": "कुल प्राथमिक विद्यालय",
			"_education_chart1_li2": "खेल का मैदान वितरण (%)",
			"_education_chart1_li3": "पुरुष छात्रावास वितरण (%)",
			"_education_chart1_li4": "महिला छात्रावास वितरण (%)",
			"_education_chart2": "माध्यमिक विद्यालयों",
			"_education_chart2_li1": "कुल माध्यमिक विद्यालय",
			"_education_chart2_li2": "खेल का मैदान वितरण (%)",
			"_education_chart2_li3": "पुरुष छात्रावास वितरण (%)",
			"_education_chart2_li4": "महिला छात्रावास वितरण (%)",
			"_education_li2": "उपयोगकर्ता वार्ड के अनुसार डेटा को फ़िल्टर भी कर सकता है।",
			"_education_li3": "उपयोगकर्ता ग्राफ के बारे में अधिक जानकारी के लिए प्रत्येक पट्टी पर होवर कर सकता है।",
			"_education_li4": "किसी भी चार्ट पर क्लिक करने पर डेटा को मैप पर प्लॉट किया जाएगा।",
			"_education_li5": "उपयोगकर्ता डाउनलोड बटन पर क्लिक करके ग्राफ भी डाउनलोड कर सकते हैं।",
			"_wcwd_header": "महिला बाल और कल्याण",
			"_wcwd_li1": "महिला और बाल कल्याण विभाग डैशबोर्ड इंदौर शहर में आंगनवाड़ी की कुल संख्या का विवरण निम्नानुसार प्रदर्शित करेगा:",
			"_wcwd_chart1": "आंगनवाड़ी",
			"_wcwd_chart1_li1": "कुल आंगनवाड़ी",
			"_wcwd_chart1_li2": "आंगनवाड़ी में खुला स्थान या खेल का मैदान (%)",
			"_wcwd_chart1_li3": "वार्ड वाइज आंगनवाड़ी",
			"_wcwd_li2": "उपयोगकर्ता वार्ड के अनुसार डेटा को फ़िल्टर भी कर सकता है।",
			"_wcwd_li3": "उपयोगकर्ता ग्राफ के बारे में अधिक जानकारी के लिए प्रत्येक पट्टी पर होवर कर सकता है।",
			"_wcwd_li4": "किसी भी चार्ट पर क्लिक करने पर डेटा को मैप पर प्लॉट किया जाएगा।",
			"_wcwd_li5": "उपयोगकर्ता डाउनलोड बटन पर क्लिक करके ग्राफ भी डाउनलोड कर सकते हैं।",
			"_mppcb_header": "MPPCB (प्रदूषण)",
			"_mppcb_li1": "प्रदूषण विभाग के डैशबोर्ड में द्विभाजन के साथ गैसों और खनिजों के मिश्रण का विवरण प्रदर्शित किया जाएगा।",
			"_industry_header": "औद्योगिक (MPIDA)",
			"_industry_li1": "औद्योगिक डैशबोर्ड वार्ड वार, क्षेत्रवार, स्वामित्व वार, प्रकार वार औद्योगिक पार्कों का विवरण प्रदर्शित करेगा:",
			"_industry_chart1": "औद्योगिक प्रशिक्षण केंद्र",
			"_industry_chart1_li1": "जोन वाइज औद्योगिक प्रशिक्षण केंद्र",
			"_industry_chart2": "व्यावसायिक उद्यान",
			"_industry_chart2_li1": "जोन वाइज औद्योगिक पार्क क्षेत्र वितरण (%)",
			"_industry_li2": "उपयोगकर्ता वार्ड के अनुसार डेटा को फ़िल्टर भी कर सकता है।",
			"_industry_li3": "उपयोगकर्ता ग्राफ के बारे में अधिक जानकारी के लिए प्रत्येक पट्टी पर होवर कर सकता है।",
			"_industry_li4": "किसी भी चार्ट पर क्लिक करने पर डेटा को मैप पर प्लॉट किया जाएगा।",
			"_industry_li5": "उपयोगकर्ता उस समय देखे जाने वाले ग्राफ में पट्टियों की संख्या को बढ़ाने के लिए स्लाइडर बार की चौड़ाई बढ़ा सकता है।",
			"_industry_li6": "उपयोगकर्ता डाउनलोड बटन पर क्लिक करके ग्राफ भी डाउनलोड कर सकते हैं।",
			"_imc_header": "आईएमसी",
			"_imc_li1": "आईएमसी डैशबोर्ड वार्ड वार डस्टबिन स्थान, सार्वजनिक शौचालय, ज़ोन वार जनसंख्या, सीवर नेटवर्क सूचना और अधिक प्रदर्शित करता है:",
			"_imc_chart1": "लिटर बिन स्थान",
			"_imc_chart1_li1": "कुल लिटर बिन स्थान",
			"_imc_chart1_li2": "वार्ड वार लिटर बिन स्थान",
			"_imc_chart2": "सार्वजनिक शौंचालय",
			"_imc_chart2_li1": "कुल सार्वजनिक शौचालय",
			"_imc_chart2_li2": "वार्ड वाइज सार्वजनिक शौचालय",
			"_imc_chart3": "जोन वाइज जनसंख्या",
			"_imc_chart4": "सीवर नेटवर्क सूचना",
			"_imc_chart4_li1": "कुल सीवर",
			"_imc_chart4_li2": "व्यास समझदार सीवर (%)",
			"_imc_chart4_li3": "वार्ड वार सीवर की लंबाई",
			"_imc_chart5": "इंदौर 311",
			"_imc_chart5_li1": "श्रेणी वार शिकायतें",
			"_imc_chart5_li2": "स्टेटस वाइज शिकायतें",
			"_imc_chart6": "संपत्ति कर",
			"_imc_chart6_li1": "निर्माण प्रकार वार संपत्ति कर",
			"_imc_chart6_li2": "वार्ड वार संपत्ति कर",
			"_imc_chart6_li3": "वार्ड वाइज भवन विवरण",
			"_imc_chart7": "ISWM",
			"_imc_chart7_li1": "GTS वार वेट कलेक्शन",
			"_imc_chart7_li2": "स्थिति वार वाहन",
			"_imc_li2": "उपयोगकर्ता वार्ड के अनुसार डेटा को फ़िल्टर भी कर सकता है।",
			"_imc_li3": "उपयोगकर्ता ग्राफ के बारे में अधिक जानकारी के लिए प्रत्येक पट्टी पर होवर कर सकता है।",
			"_imc_li4": "किसी भी चार्ट पर क्लिक करने पर डेटा को मैप पर प्लॉट किया जाएगा।",
			"_imc_li5": "उपयोगकर्ता उस समय देखे जाने वाले ग्राफ में पट्टियों की संख्या को बढ़ाने के लिए स्लाइडर बार की चौड़ाई बढ़ा सकता है।",
			"_imc_li6": "उपयोगकर्ता डाउनलोड बटन पर क्लिक करके ग्राफ भी डाउनलोड कर सकते हैं।",
			"_land_header": "भू अभिलेख",
			"_land_li1": "भूमि अभिलेख डैशबोर्ड इंदौर शहर के भूमि वितरण को निम्नानुसार प्रदर्शित करता है:",
			"_land_chart1": "खेती की जमीन",
			"_land_chart1_li1": "जोन वाइज कृषि भूमि",
			"_land_chart2": "गाँव का इलाका",
			"_land_chart2_li1": "जोन वाइज विलेज एरिया",
			"_land_chart3": "ओपन स्पेस एरिया",
			"_land_chart3_li1": "जोन वाइज ओपन स्पेस एरिया",
			"_land_chart4": "खसरा सीमा",
			"_land_chart4_li1": "जोन वार खसरा वितरण (%)",
			"_land_li2": "उपयोगकर्ता वार्ड के अनुसार डेटा को फ़िल्टर भी कर सकता है।",
			"_land_li3": "उपयोगकर्ता ग्राफ के बारे में अधिक जानकारी के लिए प्रत्येक पट्टी पर होवर कर सकता है।",
			"_land_li4": "किसी भी चार्ट पर क्लिक करने पर डेटा को मैप पर प्लॉट किया जाएगा।",
			"_land_li5": "उपयोगकर्ता उस समय देखे जाने वाले ग्राफ में पट्टियों की संख्या को बढ़ाने के लिए स्लाइडर बार की चौड़ाई बढ़ा सकता है।",
			"_land_li6": "उपयोगकर्ता डाउनलोड बटन पर क्लिक करके ग्राफ भी डाउनलोड कर सकते हैं।",
			"_smartCity_header": "इंदौर स्मार्ट सिटी",
			"_smartCity_li1": "इंदौर स्मार्ट सिटी डैशबोर्ड इंदौर स्मार्ट सिटी द्वारा निष्पादित परियोजनाओं से संबंधित डेटा प्रदर्शित करता है:",
			"_smartCity_chart1": "परियोजना वार लागत",
			"_smartCity_chart2": "जोन वाइज प्रोजेक्ट्स",
			"_smartCity_chart3": "श्रेणी वार परियोजनाएं",
			"_cityMap_header": "शहर का नक्शा",
			"_cityMap_li1": "लॉगिन के बाद 2डी दृश्य में नक्शा दिखाया जाएगा।",
			"_language_header": "भाषा",
			"_language_li1": "उपयोगकर्ता ऊपरी दाएं कोने से भाषा चयन से हिन्दी या अंग्रेजी भाषा चुन सकते हैं।",
			"_language_li2": "यदि उपयोगकर्ता हिंदी का चयन करता है, तो सभी जानकारी हिंदी भाषा में ही प्रदर्शित की जाएगी।",
			"_language_li3": "यदि उपयोगकर्ता अंग्रेजी भाषा का चयन करता है, तो सभी जानकारी केवल अंग्रेजी भाषा में प्रदर्शित की जाएगी।",
			"_map_tools_header": "नक्शा उपकरण",
			"_map_tools_globalSearch_header": "वैश्विक खोज",
			"_map_tools_globalSearch_para1": "खोज आपको एक श्रेणी में सुविधाओं (उदाहरण के लिए बस स्टॉप, एटीएम, स्कूल, बैंक, सरकारी कार्यालय आदि) देखने का अवसर प्रदान करता है और मानचित्र पर उनका स्थान देखता है।",
			"_map_tools_globalSearch_li1": "खोज श्रेणी का चयन करने के लिए खोज बार पर डाउन एरो पर क्लिक करें, पोर्टल के शीर्ष पर पाठ बॉक्स में खोज शब्द लिखें, जैसा कि आप लिखते हैं, आप देख सकते हैं कि शब्द खोज बॉक्स के नीचे दिखाई देने लगते हैं। ये ऐसे ऑटो-सुझाव हैं जो आपकी रुचि के अनुरूप हो सकते हैं।",
			"_map_tools_globalSearch_li2": "वास्तविक खोज परिणाम लोड होने पर, मानचित्र पर स्थान और पॉप-अप पर संबंधित जानकारी देखने के लिए सुविधा परिणाम पर क्लिक करें।",
			"_map_tools_zoomIn_header": "ज़ूम इन",
			"_map_tools_zoomIn_para1": "मैप को विस्तार से देखने के लिए ज़ूम इन आइकन पर क्लिक करें। आप मैप को ज़ूम इन करने के लिए माउस स्क्रॉल का भी उपयोग कर सकते हैं।",
			"_map_tools_zoomOut_header": "ज़ूम आउट",
			"_map_tools_zoomOut_para1": "मैप से ज़ूम आउट करने के लिए ज़ूम आउट आइकन पर क्लिक करें। मैप को ज़ूम आउट करने के लिए आप माउस स्क्रॉल का भी उपयोग कर सकते हैं।",
			"_map_tools_home_header": "होम",
			"_map_tools_home_para1": "होम को उसकी डिफ़ॉल्ट सीमा तक रीसेट करने के लिए होम आइकन पर क्लिक करें। जब आप होम पर बहुत अधिक ज़ूम इन या आउट करते हैं तो यह फ़ंक्शन बेहद मददगार साबित होता है और आप अपने मूल लैंडिंग पृष्ठ पर वापस आ सकते हैं।",
			"_map_tools_myLocation_header": "माय लोकेशन",
			"_map_tools_myLocation_para1": "आइकन पर क्लिक करने पर, मैप पर एक प्रतीक प्रदर्शित होता है, जो आपके वर्तमान लोकेशन को दर्शाता है। मैप का स्थान वर्तमान लोकेशन को रुचि के क्षेत्र के रूप में दिखाने के लिए अद्यतन करता है।",
			"_map_tools_myLocation_para2": "पहली बार जब आप सिटीजन पोर्टल पर जाते हैं, तो आपके पास अपने स्थान डेटा को साझा करने से ब्राउज़र को अनुमति देने या अस्वीकार करने का विकल्प होगा। यदि आपने अनुमति से इनकार कर दिया है और सेटिंग्स बदलना चाहते हैं, तो अपने ब्राउज़र पर स्थान साझाकरण को सक्षम करने के लिए नीचे दिए गए चरणों का पालन करें:",
			"_map_tools_myLocation_chromeHeader": "गूगल क्रोम",
			"_map_tools_myLocation_chromeli1": "क्रोम खोलें।",
			"_map_tools_myLocation_chromeli2": "शीर्ष दाईं ओर, अधिक और फिर सेटिंग्स पर क्लिक करें।",
			"_map_tools_myLocation_chromeli3": "सबसे नीचे, उन्नत पर क्लिक करें।",
			"_map_tools_myLocation_chromeli4": "“गोपनीयता और सुरक्षा” के तहत, सामग्री सेटिंग पर क्लिक करें।",
			"_map_tools_myLocation_chromeli5": "स्थान पर क्लिक करें।",
			"_map_tools_myLocation_chromeli6": "चालू या बंद करने से पहले पूछें चालू करें।",
			"_map_tools_myLocation_ieHeader": "इंटरनेट एक्स्प्लोरर",
			"_map_tools_myLocation_ieli1": "इंटरनेट एक्सप्लोरर में, टूल (मेनू बार या गियर आइकन) और इंटरनेट विकल्प पर क्लिक / टैप करें।",
			"_map_tools_myLocation_ieli2": "प्राइवेसी टैब पर क्लिक / टैप करें",
			"_map_tools_myLocation_ieli3": "वेबसाइटों को आपके स्थान का अनुरोध करने की अनुमति देने के लिए, कभी भी वेबसाइटों को अपने भौतिक स्थान बॉक्स का अनुरोध करने की अनुमति न दें, ठीक पर क्लिक / टैप करें।",
			"_map_tools_myLocation_ieli4": "बंद करें और लागू करने के लिए इंटरनेट एक्सप्लोरर को फिर से खोलें।",
			"_map_tools_myLocation_firefoxHeader": "फ़ायरफ़ॉक्स",
			"_map_tools_myLocation_firefoxli1": "उपकरण मेनू पर जाएं, और फिर पृष्ठ जानकारी का चयन करें।",
			"_map_tools_myLocation_firefoxli2": "अनुमतियाँ टैब का चयन करें।",
			"_map_tools_myLocation_firefoxli3": "शेयर स्थान के लिए सेटिंग बदलें।",
			"_map_tools_myLocation_noteHeader": "ध्यान दें:",
			"_map_tools_myLocation_note": "Google की गोपनीयता नीति के कारण वर्तमान स्थान Chrome के माध्यम से Chrome में समर्थित नहीं है। अन्य ब्राउज़र में भी, टूल तभी कार्य करेगा जब आप वेबसाइट को अपना स्थान ट्रैक करने देंगे।",
			"_map_tools_print_header": "प्रिंट",
			"_map_tools_print_para1": "PDF, PNG, JPG एक्सटेंशन में फ़ाइलों को एक्सपोर्ट और प्रिंट करने के लिए प्रिंट पर क्लिक करें। उपयोगकर्ता शीर्षक, फ़ाइल नाम और पेज सेटअप A1 से A5, ओरिएंटेशन: लैंडस्केप / पोर्ट्रेट दर्ज कर सकता है। यदि आवश्यक हो तो उपयोगकर्ता लेजेंड्स को शामिल कर सकता है।",
			"_map_tools_measurement_header": "माप उपकरण",
			"_map_tools_measurement_li1": "मापन उपकरण पर क्लिक करें",
			"_map_tools_measurement_li2": "उपयोगकर्ता नक्शे पर किसी भी आकार को मापने के लिए इस उपकरण का चयन कर सकता है। उपयोगकर्ता इस उपकरण का उपयोग करके दूरी, क्षेत्र या बिंदु के विशेष स्थान को माप सकते हैं।",
			"_map_tools_measurement_li3": "उपयोगकर्ता क्षेत्र, दूरी और स्थान के लिए माप की इकाई को भी बदल सकता है।",
			"_map_tools_measurement_li4": "मानचित्र पर किसी भी 2 बिंदुओं के बीच की लंबाई को मापने के लिए; उपयोगकर्ता माप दूरी उपकरण का उपयोग कर सकते हैं।",
			"_map_tools_measurement_li5": "उपयोगकर्ता माप क्षेत्र उपकरण का उपयोग करके नक्शे पर बहुभुज खींचकर क्षेत्र को माप सकता है।",
			"_map_tools_measurement_li6": "माप उपकरण के तहत स्थान टूल ढूंढें उपयोगकर्ता को चयनित बिंदु के स्थान का विवरण मिलेगा",
			"_map_tools_bookmark_header": "बुकमार्क",
			"_map_tools_bookmark_para1": "एक स्थानिक बुकमार्क एक विशेष भौगोलिक स्थान की पहचान करता है जिसे आप बाद में सहेजना और संदर्भित करना चाहते हैं। बुकमार्क नक्शे पर दिलचस्प स्थानों के लिए शॉर्टकट प्रदान करते हैं। उपयोगकर्ता मानचित्र के वर्तमान स्थान और पैमाने के आधार पर एक बुकमार्क बना सकता है। जब अन्य उपयोगकर्ता किसी बुकमार्क पर क्लिक करता है, तो मानचित्र उस स्थान पर पहुंच जाता है।",
			"_map_tools_bookmark_li1": "स्क्रीन के निचले बाएँ पैनल से बुकमार्क आइकन पर क्लिक करें।",
			"_map_tools_bookmark_li2": "उस क्षेत्र पर ज़ूम करें जो आप अक्सर आते हैं। उदाहरण के लिए, यदि \"राजवाड़ा पैलेस\" आपके अक्सर मैप किए गए क्षेत्रों में से एक है, तो इसे मैप पर खोजें। अब, बाद में उपयोग के लिए इस नक्शे को बुकमार्क करें।",
			"_map_tools_bookmark_li3": "बुकमार्क को नाम प्रदान करें और बुकमार्क जोड़ने के लिए + बटन पर क्लिक करें।",
			"_map_tools_bookmark_li4": "जब किया जाता है, तो आप बाद में आ सकते हैं और राजवाड़ा पैलेस क्षेत्र के बुकमार्क पर क्लिक करके मैप को ज़ूम करने के लिए मैप की सीमा और पैमाने पर ज़ूम करके देख सकते हैं",
			"_map_tools_bookmark_li5": "उस बुकमार्क को चुनें जिसे आप हटाना चाहते हैं और सिस्टम से बुकमार्क हटाने के लिए डिलीट बटन पर क्लिक करें।",
			"_map_tools_bookmark_noteHeader": "ध्यान दें",
			"_map_tools_bookmark_note": "अतिथि उपयोगकर्ता सिस्टम में बुकमार्क को सहेजने में सक्षम नहीं होगा।",
			"_map_tools_share_header": "शेयर",
			"_map_tools_share_para1": "उपयोगकर्ता इंदौर जीआईएस पोर्टल के लिंक को ईमेल भेजकर, सोशल मीडिया पर पोस्ट करके या वेब पेज पर एम्बेड करके साझा कर सकता है।",
			"_map_tools_share_li1": "शेयर बटन पर क्लिक करें, और इसे साझा करने के लिए एक विकल्प चुनें।",
			"_map_tools_share_li2": "शॉर्ट यूआरएल को कॉपी करें और ईमेल, ब्लॉग या वेबसाइट में पेस्ट करें।",
			"_map_tools_share_li3": "किसी वेबसाइट में नक्शा एम्बेड करें।",
			"_map_tools_share_li4": "शेयर पॉप-अप में जीमेल, फेसबुक और ट्विटर बटन पर क्लिक करें।",
			"_map_tools_csb_header": "कस्टम स्केल बार",
			"_map_tools_csb_li1": "उपयोगकर्ता न्यूनतम मान 100 से अधिकतम मूल्य 100000 तक कस्टम स्केल निर्धारित कर सकता है।",
			"_map_tools_clearMap_header": "क्लियर मैप",
			"_map_tools_clearMap_para1": "मैप पर प्रदर्शित किसी भी परिणाम को साफ़ करने के लिए स्पष्ट मानचित्र  क्लियर मैप पर क्लिक करें।",
			"_map_tools_swipeLayer_header": "स्वाइप लेयर",
			"_map_tools_swipeLayer_li1": "स्वाइप विजेट उपयोगकर्ताओं को आसानी से स्वाइप टूल को स्लाइड करके मैप में विभिन्न परतों की सामग्री की तुलना करने में सक्षम बनाता है।",
			"_map_tools_kyc_header": "अपने समन्वय को जानें",
			"_map_tools_kyc_para1": "उपयोगकर्ता अपने निर्देशांक उपकरण का उपयोग करके मानचित्र पर बिंदु को प्लॉट कर सकते हैं और इच्छित स्थान पर ज़ूम कर सकते हैं",
			"_map_tools_kyc_li1": "उपयोगकर्ता या तो वर्तमान स्थान बटन का चयन कर सकता है या बिंदु का चयन करने के लिए मानचित्र द्वारा स्थान का चयन कर सकता है।",
			"_map_tools_kyc_li2": "Go To पर क्लिक करें",
			"_map_tools_kyc_li3": "बिंदु को प्लॉट किया जाएगा और मानचित्र को उस स्थान पर ज़ूम किया जाएगा",
			"_menu_header": "मेन्यू",
			"_menu_para1": "मेनू पेज के बाएं पैनल पर होगा और आप मेनू को छिपा या दिखा सकते हैं। मेनू से आप विभिन्न मॉड्यूल पर नेविगेट कर सकते हैं।",
			"_menu_basemap_header": "बेस मैप गैलरी",
			"_menu_basemap_li1": "उपयोगकर्ता विभिन्न प्रकार के आधार मानचित्रों को देख और चुन सकता है।",
			"_menu_basemap_li2": "किसी भी आधार मानचित्र को चुनने पर इसे स्क्रीन पर प्रदर्शित किया जाएगा",
			"_menu_basemap_li3": "बेस मैप में ISCDL ड्रोन इमेज 2020, ISCDL सैटेलाइट इमेज 2015, हाइब्रिड, स्ट्रीट मैप और नो बेस मैप शामिल हैं।",
			"_menu_basemap_li4": "उपयोगकर्ता किसी भी बेस मैप को एक क्लिक में देख सकता है।",
			"_menu_layers_header": "परतें",
			"_menu_layers_para1": "एक समूह लेयर्स उन सभी सुविधाओं का संग्रह है जो किसी श्रेणी में आती हैं। स्थान (स्थानों) और विशेष सुविधाओं की जानकारी का पता लगाने के लिए आप इसके संबंधित डेटा को देखने के लिए लेयर्स का चयन कर सकते हैं।",
			"_menu_layers_li1": "नागरिक पोर्टल के बाएं हाथ की ओर मेनू बार से लेयर्स पर क्लिक करें।",
			"_menu_layers_li2": "विजेट पर आप सूचीबद्ध सभी समूह लेयर्स श्रेणियों को देख और विस्तारित कर सकते हैं",
			"_menu_layers_li3": "लेयर्स पर क्लिक करके, उपयोगकर्ता लेयर्स की सूची देख सकते हैं जैसे: बिल्डिंग, डिवाइडर, इलेक्ट्रिक पोल, स्ट्रीट लाइट, ट्री आदि।",
			"_menu_layers_li4": "लेयर पैनल से उस पर क्लिक करके लेयर दिखाई देगा।",
			"_menu_query_header": "प्रश्न",
			"_menu_query_para1": "भौगोलिक विश्लेषण की शक्ति भौगोलिक विशेषताओं और उनकी विशेषताओं और उनके बीच संबंधों के बारे में सवाल पूछने और जवाब देने की क्षमता है।",
			"_menu_query_basicQuery_header": "बुनियादी प्रश्न",
			"_menu_query_basicQuery_para1": "किसी विशिष्ट विशेषता क्वेरी को देखने के लिए उपयोगकर्ता को निम्नलिखित क्रियाएं करने की आवश्यकता होती है:",
			"_menu_query_basicQuery_li1": "परत का चयन करें",
			"_menu_query_basicQuery_li2": "फ़ील्ड प्रकार का चयन करें - चयनित परत के आधार पर यह भिन्न हो सकता है",
			"_menu_query_basicQuery_li3": "मूल्य का चयन करें - ड्रॉपडाउन से",
			"_menu_query_basicQuery_li4": "वार्ड का चयन करें",
			"_menu_query_basicQuery_li5": "खोज पर क्लिक करें",
			"_menu_query_adQuery_header": "अग्रिम प्रश्न",
			"_menu_query_adQuery_para1": "उपयोगकर्ता डेटाबेस से रिकॉर्ड का चयन कर सकते हैं (कम से अधिक, के बराबर, के बराबर या नहीं के बराबर) या बूलियन बीजगणित (और, या, जैसे और नहीं। किसी विशेष विशेषता क्वेरी को देखने के लिए उपयोगकर्ता को निम्नलिखित क्रियाएं करने की आवश्यकता होती है",
			"_menu_query_adQuery_li1": "वार्ड का चयन करें",
			"_menu_query_adQuery_li2": "परत का चयन करें",
			"_menu_query_adQuery_li3": "फ़ील्ड प्रकार का चयन करें - चयनित परत के आधार पर यह भिन्न हो सकता है",
			"_menu_query_adQuery_li4": "लॉजिकल ऑपरेटर्स का चयन करें - चयनित फ़ील्ड प्रकार के आधार पर यह भिन्न हो सकता है",
			"_menu_query_adQuery_li5": "मूल्य का चयन करें - ड्रॉपडाउन से",
			"_menu_query_adQuery_li6": "खोज पर क्लिक करें",
			"_menu_query_para2": "चयनित डेटा के आधार पर खोज परिणाम दिखाए जाएंगे जो मानचित्र पर देखे जा सकते हैं।",
			"_menu_query_noteHeader": "नोट:",
			"_menu_query_note": "यदि उपयोगकर्ता कई विशेषता प्रश्नों को देखना चाहता है, तो वे \"+\" बटन पर क्लिक करके ऐसा कर सकते हैं।",
			"_menu_query_spQuery_header": "स्थानिक प्रश्न",
			"_menu_query_spQuery_para1": "स्थानिक क्वेरी उनके भौगोलिक संबंध या अन्य सुविधाओं के साथ स्थानिक संबंध के आधार पर सुविधाओं का चयन करने की प्रक्रिया है। उपयोगकर्ता स्थानिक क्वेरी निम्नानुसार कर सकते हैं:",
			"_menu_query_spQuery_li1": "वार्ड का चयन करें",
			"_menu_query_spQuery_li2": "स्रोत परत का चयन करें",
			"_menu_query_spQuery_li3": "क्वेरी प्रकार चुनें",
			"_menu_query_spQuery_li4": "मास्क परत का चयन करें",
			"_menu_query_spQuery_li5": "खोज पर क्लिक करें",
			"_menu_query_spQuery_para2": "चयनित डेटा के आधार पर खोज परिणाम दिखाए जाएंगे जो मानचित्र पर देखे जा सकते हैं।",
			"_menu_userMgmt_header": "उपयोगकर्ता प्रबंधन",
			"_menu_userMgmt_para1": "उपयोगकर्ता इस मॉड्यूल से उपयोगकर्ताओं और भूमिकाओं का प्रबंधन कर सकता है। मेनू से उपयोगकर्ता प्रबंधन पर क्लिक करें।",
			"_menu_userMgmt_deptMaster_header": "विभाग के मास्टर",
			"_menu_userMgmt_deptMaster_li1": "विभागों की सूची ग्रिड में दिखाई जाएगी। आप कार्रवाई कॉलम से विभाग को संपादित या हटा सकते हैं।",
			"_menu_userMgmt_deptMaster_li2": "उपयोगकर्ता सूची से विभाग को खोज सकता है। एक्सपोर्ट बटन पर क्लिक करके एक्सेल और पीडीएफ में विभागों को निर्यात किया जा सकता है।",
			"_menu_userMgmt_deptMaster_li3": "व्यवस्थापक प्रत्येक विभाग के विवरण को बदल या अपडेट कर सकता है",
			"_menu_userMgmt_roleMaster_header": "भूमिका मास्टर",
			"_menu_userMgmt_roleMaster_li1": "भूमिकाओं की सूची ग्रिड में दिखाई जाएगी। व्यवस्थापक कार्रवाई कॉलम से भूमिका संपादित या हटा सकता है।",
			"_menu_userMgmt_roleMaster_li2": "उपयोगकर्ता सूची से भूमिकाएं खोज सकता है। एक्सपोर्ट बटन पर क्लिक करके एक्सेल और पीडीएफ को रोल्स एक्सपोर्ट किए जा सकते हैं।",
			"_menu_userMgmt_roleMaster_li3": "नई भूमिकाएँ जोड़ने के लिए ऐड रोल पर क्लिक करें और निम्न कार्य करें",
			"_menu_userMgmt_roleMaster_li31": "ऐड रोल बटन पर क्लिक करें",
			"_menu_userMgmt_roleMaster_li32": "विभाग का चयन करें",
			"_menu_userMgmt_roleMaster_li33": "भूमिका का नाम दर्ज करें",
			"_menu_userMgmt_roleMaster_li34": "चेकबॉक्स की जांच करके पहले से मौजूद मॉड्यूल के अधिकार प्रदान करें",
			"_menu_userMgmt_roleMaster_li35": "रोल प्रकार का चयन करें",
			"_menu_userMgmt_roleMaster_li36": "सेव बटन पर क्लिक करें",
			"_menu_userMgmt_roleMaster_li37": "भूमिका जोड़ी जाएगी और सूची में दिखाई देगी",
			"_menu_userMgmt_userMaster_header": "उपयोगकर्ता मास्टर",
			"_menu_userMgmt_userMaster_li1": "उपयोगकर्ता मास्टर पर क्लिक करने पर, उपयोगकर्ता को ग्रिड में दिखाए गए उपयोगकर्ताओं की सूची में नेविगेट किया जाएगा। ",
			"_menu_userMgmt_userMaster_li2": "उपयोगकर्ता कार्रवाई कॉलम से भूमिका संपादित या हटा सकता है। व्यवस्थापक उपयोगकर्ता सूची से उपयोगकर्ताओं को खोज सकते हैं।",
			"_menu_userMgmt_userMaster_li3": "एक्सपोर्ट बटन पर क्लिक करके यूजर्स को एक्सेल और पीडीएफ में एक्सपोर्ट किया जा सकता है।",
			"_menu_userMgmt_userMaster_li4": "नए उपयोगकर्ता को जोड़ने के लिए नए उपयोगकर्ताओं को जोड़ने पर क्लिक करें और निम्नलिखित करें",
			"_menu_userMgmt_userMaster_li41": "पॉपअप में, नाम दर्ज करें।",
			"_menu_userMgmt_userMaster_li42": "मोबाइल नंबर दर्ज करें।",
			"_menu_userMgmt_userMaster_li43": "ईमेल दर्ज करें।",
			"_menu_userMgmt_userMaster_li44": "विभाग का चयन करें।",
			"_menu_userMgmt_userMaster_li45": "इस उपयोगकर्ता के लिए पासवर्ड सेट करें।",
			"_menu_userMgmt_userMaster_li46": "ड्रॉपडाउन से भूमिका का चयन करें।",
			"_menu_userMgmt_userMaster_li47": "सेव बटन पर क्लिक करें",
			"_menu_userMgmt_userMaster_li48": "उपयोगकर्ता जोड़ा जाएगा और यह सूची में दिखाई देगा।",
			"_menu_citizenServices_header": "नागरिक सेवाएँ",
			"_menu_event_header": "आयोजन",
			"_menu_event_para1": "उपयोगकर्ता इवेंट जोड़ सकते हैं और इवेंट मैनेजमेंट मॉड्यूल से इवेंट विवरण प्रबंधित कर सकते हैं",
			"_menu_event_li1": "अधिकृत उपयोगकर्ता प्रदान किए जाने वाले इवेंट के विवरण देख सकता है और प्रदान किए गए विवरण के आधार पर घटना को अनुमोदित या अस्वीकार कर सकता है।",
			"_menu_event_li2": "उपयोगकर्ता सूची से ईवेंट खोज सकते हैं। एक्सपोर्ट टू एक्सेल बटन और पीडीएफ पर एक्सपोर्ट पर क्लिक करके एक्सेल को एक्सपोर्ट किया जा सकता है।",
			"_menu_event_li3": "उपयोगकर्ता ईवेंट जोड़ें बटन पर क्लिक करके भी ईवेंट जोड़ सकते हैं",
			"_menu_announcement_header": "घोषणा",
			"_menu_announcement_addHeader": "घोषणा जोड़ें",
			"_menu_announcement_addli1": "विभाग का चयन करें",
			"_menu_announcement_addli2": "घोषणा शीर्षक दर्ज करें।",
			"_menu_announcement_addli3": "घोषणा विवरण दर्ज करें।",
			"_menu_announcement_addli4": "घोषणा तिथि और समय चुनें।",
			"_menu_announcement_addli5": "देशांतर और अक्षांश प्राप्त करने के लिए मानचित्र पर एक बिंदु प्लॉट करें।",
			"_menu_announcement_addli6": "सबमिट पर क्लिक करें।",
			"_menu_announcement_addli7": "यदि आप डेटा को हटाना चाहते हैं तो क्लीयर पर क्लिक करें।",
			"_menu_announcement_viewHeader": "घोषणा देखें",
			"_menu_announcement_viewpara1": "घोषणाओं की सूची इस टैब में दिखाई जाएगी। घोषणा से संबंधित स्थान का विवरण भी मानचित्र पर देखा जा सकता है।",
			"_menu_feedback_header": "प्रतिक्रिया और सुझाव",
			"_menu_feedback_feedback_header": "प्रतिपुष्टि",
			"_menu_feedback_li1": "प्रतिक्रिया और सुझाव पर क्लिक करने पर उपयोगकर्ता को फीडबैक पेज पर नेविगेट किया जाएगा, जहां वह आईएससीडीएल के नागरिकों से प्राप्त फीडबैक की सूची देख सकता है।",
			"_menu_feedback_li2": "प्राप्त फ़ीडबैक पर प्रतिक्रिया प्रदान करने के लिए व्यवस्थापक को ऐड रिस्पांस पर क्लिक करना होगा जहां एक पॉपअप फीडबैक विवरण के साथ दिखाया जाएगा, नीचे स्क्रॉल करें और प्रतिक्रिया क्षेत्र में अपनी प्रतिक्रिया जोड़ें।",
			"_menu_feedback_li3": "आप सूची से प्रतिक्रिया खोज सकते हैं। एक्शन कॉलम से डिलीट आइकन पर क्लिक करके फीडबैक को डिलीट किया जा सकता है। निर्यात बटन पर क्लिक करके एक्सेल और पीडीएफ में फीडबैक निर्यात किया जा सकता है",
			"_menu_suggestion_header": "सुझाव",
			"_menu_suggestion_li1": "प्रतिक्रिया पृष्ठ से सुझाव टैब पर क्लिक करने पर उपयोगकर्ता को सुझाव पृष्ठ पर भेज दिया जाएगा जहां वह आईएससीडीएल के नागरिकों से प्राप्त सुझावों की सूची देख सकता है।",
			"_menu_suggestion_li2": "प्राप्त सुझाव पर प्रतिक्रिया देने के लिए व्यवस्थापक को ऐड रिस्पांस पर क्लिक करना होगा जहां एक पॉपअप सुझाव विवरण के साथ दिखाया जाएगा, नीचे स्क्रॉल करें और प्रतिक्रिया क्षेत्र में अपनी प्रतिक्रिया जोड़ें।",
			"_menu_suggestion_li3": "आप सूची से सुझाव खोज सकते हैं। एक्शन कॉलम से डिलीट आइकन पर क्लिक करके सुझाव को डिलीट किया जा सकता है। निर्यात बटन पर क्लिक करके एक्सेल और पीडीएफ में सुझाव निर्यात किया जा सकता है",
			"_menu_complaint_header": "शिकायतें",
			"_menu_complaint_li1": "शिकायत टैब पर क्लिक करने पर उपयोगकर्ता ISCDL के नागरिकों से प्राप्त शिकायतों की सूची देख सकता है।",
			"_menu_complaint_li2": "प्राप्त शिकायतों पर प्रतिक्रिया प्रदान करने के लिए; व्यवस्थापक को ऐड रिस्पांस पर क्लिक करना होगा जहां एक पॉपअप शिकायत विवरण के साथ दिखाया जाएगा, नीचे स्क्रॉल करें और रिस्पॉन्स फ़ील्ड में अपनी प्रतिक्रिया जोड़ें।",
			"_menu_complaint_li3": "आप सूची से शिकायतों को खोज सकते हैं। एक्शन कॉलम से डिलीट आइकन पर क्लिक करके शिकायतों को हटाया जा सकता है। निर्यात बटन पर क्लिक करके एक्सेल और पीडीएफ को शिकायतें निर्यात की जा सकती हैं।",
			"_menu_citizenMaster_header": "सिटीजन मास्टर डाटा",
			"_menu_citizenMaster_para1": "सभी पंजीकृत नागरिक जानकारी देखने के लिए मेनू से नागरिक मास्टर डेटा पर क्लिक करें।",
			"_menu_citizenMaster_para2": "नागरिकों की सूची उपयोगकर्ता नाम, नाम, ईमेल, फोन नंबर, पता और स्थिति के साथ दिखाई जाएगी। उपयोगकर्ता सूची से नागरिक को खोज सकता है। निर्यात करने के लिए एक्सेल बटन और पीडीएफ पर क्लिक करके सिटीजन सूची एक्सेल को निर्यात की जा सकती है।",
			"_menu_adServices_header": "उन्नत सेवाएँ",
			"_menu_addData_header": "डेटा जोड़ें",
			"_menu_addData_para1": "एक नई जगह जोड़ने के लिए जो मानचित्र पर नहीं है, अधिकृत उपयोगकर्ता मेनू से ऐड प्लेस पर क्लिक कर सकता है।",
			"_menu_addData_li1": "नाम दर्ज करें",
			"_menu_addData_li2": "छवि चुने",
			"_menu_addData_li3": "पिन आइकन पर क्लिक करके मानचित्र पर एक स्थान प्लॉट करें",
			"_menu_addData_li4": "जगह के लिए टिप्पणी दर्ज करें।",
			"_menu_addData_li5": "“सबमिट” बटन पर क्लिक करें।",
			"_menu_addData_li6": "जोड़े गए विवरण विशिष्ट विभाग के उपयोगकर्ता के अनुमोदन के बाद मानचित्र पर प्रदर्शित होंगे। जीआईएस सेल मैप पर डेटा को अपडेट करेगा।",
			"_menu_addLayer_header": "परत जोड़ें",
			"_menu_addLayer_li1": "उपयोगकर्ता “परत जोड़ें” मॉड्यूल से परतें जोड़ सकते हैं।",
			"_menu_addLayer_li2": "उपयोगकर्ता ज़िप किए गए फ़ोल्डर का चयन करके आकार फ़ाइल जोड़ सकते हैं जिसमें मान्य फ़ाइल प्रारूप (.shp, .shx आदि) होते हैं या KML या .kmz फ़ाइल प्रारूप का चयन करके KML जोड़ सकते हैं।",
			"_menu_addLayer_li3": "फाइल सेलेक्ट करने के बाद Submit पर क्लिक करें।",
			"_menu_addLayer_li4": "जोड़े गए डेटा को मानचित्र पर प्लॉट किया जाएगा।",
			"_menu_addLayer_li5": "अन्य प्रकार की फ़ाइलों की अनुमति नहीं है और यदि अमान्य फ़ाइल अपलोड की गई है, तो सिस्टम त्रुटि उत्पन्न करेगा।",
			"_menu_proximity_header": "निकटता विश्लेषण",
			"_menu_proximity_para1": "उपयोगकर्ता ड्रॉपडाउन से परत का चयन करके एक विशेष उपयोगिता खोज सकता है। परत का चयन करने के बाद उपयोगकर्ता को मानचित्र पर एक बहुभुज खींचना होगा।",
			"_menu_proximity_para2": "यह खींची गई बहुभुज में चयनित परत की खोज करेगा और विवरण मानचित्र पर प्रदर्शित किया जाएगा।",
			"_menu_proximity_para3": "मानचित्र पर परिणाम देखने के लिए ज़ूम टू फ़ीचर पर क्लिक करें",
			"_menu_heatMap_header": "हीटमैप विश्लेषण",
			"_menu_heatMap_para1": "हीटमैप विश्लेषण डेटा का एक चित्रमय प्रतिनिधित्व है जो एक परत में बिंदुओं के घनत्व की कल्पना करता है। इससे विभाग को शहर के भीतर सेवाओं की बेहतर योजना बनाने में मदद मिलती है।",
			"_menu_heatMap_li1": "ड्रॉप डाउन से विभाग का चयन करें",
			"_menu_heatMap_li2": "उस मापदंड का चयन करें जिसके आधार पर आप हीट मैप बनाना चाहते हैं",
			"_menu_heatMap_li3": "जनरेट हीट मैप पर क्लिक करें",
			"_menu_pm_header": "परियोजना की निगरानी",
			"_menu_pm_manageProject_header": "परियोजना का प्रबंधन",
			"_menu_pm_manageProject_project": "परियोजनाओं",
			"_menu_pm_manageProject_li1": "प्रोजेक्ट्स टैब में, प्रोजेक्ट्स की सूची दिखाई जाएगी। उपयोगकर्ता कार्रवाई कॉलम से संपादन आइकन पर क्लिक करके जानकारी संपादित कर सकते हैं।",
			"_menu_pm_manageProject_li2": "उपयोगकर्ता सूची से प्रोजेक्ट खोज सकता है। एक्सपोर्ट बटन पर क्लिक करके एक्सेल और पीडीएफ में प्रोजेक्ट लिस्ट को एक्सपोर्ट किया जा सकता है।",
			"_menu_pm_manageProject_li3": "उपयोगकर्ता नई परियोजना जोड़ सकते हैं।",
			"_menu_pm_manageProject_li31": "एक-एक करके सभी विवरण दर्ज करें और अगले विवरण पर जाने के लिए अगले पर क्लिक करें।",
			"_menu_pm_manageProject_li32": "सभी विवरण भरने के बाद अंत में सबमिट पर क्लिक करें।",
			"_menu_pm_manageProject_li33": "प्रोजेक्ट विवरण जोड़ा जाएगा और प्रोजेक्ट सूची में दिखाई देगा।",
			"_menu_pm_milestone_header": "माइलस्टोंस",
			"_menu_pm_milestone_li1": "माइलस्टोन टैब में, एक परियोजना के लिए मौजूद माइलस्टोन  की सूची दिखाई जाएगी ड्रॉपडाउन से एक प्रोजेक्ट का चयन करें। माइलस्टोन की जानकारी ग्रिड में दिखाई जाएगी। उपयोगकर्ता कार्रवाई कॉलम से संपादन आइकन पर क्लिक करके जानकारी संपादित कर सकते हैं।",
			"_menu_pm_milestone_li2": "उपयोगकर्ता सूची से माइलस्टोन खोज सकता है। एक्सपोर्ट बटन पर क्लिक करके एक्सेल और पीडीएफ में माइलस्टोन लिस्ट को एक्सपोर्ट किया जा सकता है।",
			"_menu_pm_milestone_li3": "ऐड माइलस्टोन बटन पर क्लिक करके उपयोगकर्ता किसी विशेष परियोजना के लिए एक माइलस्टोन भी जोड़ सकता है",
			"_menu_projectReports_header": "प्रोजेक्ट रिपोर्ट",
			"_menu_projectReports_li1": "परियोजनाओं की सूची और इसकी स्थिति यहां प्रदर्शित की जाएगी।",
			"_menu_projectReports_li2": "उपयोगकर्ता मानचित्र दिखाने के लिए क्लिक करके प्रोजेक्ट स्थान पर नेविगेट कर सकता है।",
			"_menu_projectAlerts_header": "प्रोजेक्ट अलर्ट",
			"_menu_ftl_header": "स्थान से - स्थान के लिए",
			"_menu_ftl_para1": "स्रोत और गंतव्य में प्रवेश करके उपयोगकर्ता दो स्थानों के बीच निर्देश प्राप्त कर सकते हैं।",
			"_menu_ftl_li1": "उपयोगकर्ता स्रोत और गंतव्य पते को स्वतः पूर्ण बॉक्स में लिखकर पा सकते हैं।",
			"_menu_ftl_li2": "उपयोगकर्ता बॉक्स में दिए गए आइकन्स की मदद से \"सेट सोर्स बाई प्लॉटिंग पॉइंट\" या \"करंट लोकेशन सेट करें\" भी कर सकते हैं।",
			"_menu_ftl_li3": "“लागू करें” पर क्लिक करने पर यह मानचित्र पर स्रोत से गंतव्य तक दिशाओं को दिखाएगा।",
			"_menu_reports_header": "रिपोर्ट",
			"_menu_reports_para1": "उपयोगकर्ता उस विभाग के चयन के आधार पर विभिन्न रिपोर्ट उत्पन्न कर सकता है जिसमें वह रुचि रखता है।",
			"_menu_reports_para2": "वार्ड वार फिल्टर को रिपोर्ट में लगाया जा सकता है",
			"_menu_reports_para3": "तालिका से चयनित किसी भी डेटा को मानचित्र पर हाइलाइट किया जाएगा। कई अन्य विकल्प भी दिए गए हैं जिनका उपयोग उपयोगकर्ता कर सकता है।",
			"_menu_poi_header": "POI डेटा",
			"_menu_poi_para1": "POI मोबाइल एप्लिकेशन से एकत्र किए गए डेटा को वेब पोर्टल में दिखाया जाएगा। उपयोगकर्ता विभाग, POI प्रकार, दिनांक के अनुसार डेटा फ़िल्टर कर सकते हैं।",
			"_menu_help_header": "मदद",
			"_menu_help_para1": "यह पृष्ठ पोर्टल का उपयोग करने के तरीके के बारे में जानकारी दिखाएगा।",
			"_3d_map_header": "3डी नक्शा",
			"_3d_map_li1": "सिटी जीआईएस नक्शे पर “3डी” का चयन करने के बाद 3 डी दृश्य में नक्शा दिखाया जाएगा।",
			"_3d_map_li2": "3डी मैप में मेन मेन्यू- बेस मैप गैलरी, लेयर्स ड्रॉ टूल, हेरिटेज बिल्डिंग टूल और अन्य मैप टूल्स शामिल हैं।",
			"_3d_mapTools_header": "मानचित्र उपकरण",
			"_3d_mapTools_para1": "2D मानचित्र में मौजूद सभी मानचित्र उपकरण 3D मानचित्र में उपलब्ध हैं। 3 डी में कुछ अतिरिक्त उपकरण इस प्रकार हैं:",
			"_3d_mapTools_li1": "पैन को टॉगल करें या 3डी में घुमाएँ",
			"_3d_mapTools_li2": "कम्पास ओरिएंटेशन को रीसेट करें",
			"_3d_basemap_header": "बेस मैप गैलरी",
			"_3d_basemap_li1": "उपयोगकर्ता विभिन्न प्रकार के आधार मानचित्रों को देख और चुन सकता है।",
			"_3d_basemap_li2": "किसी भी आधार मानचित्र को चुनने पर इसे स्क्रीन पर प्रदर्शित किया जाएगा",
			"_3d_basemap_li3": "बेस मैप में ISCDL ड्रोन इमेज, ISCDL सैटेलाइट इमेज 2015, डार्क ग्रे कैनवास, इमेजरी, इमेजरी हाइब्रिड, लाइट ग्रे कैनवस, नेविगेशन मैप, ओसेन्स, स्ट्रीट्स (नाइट), स्ट्रीट मैप, टेरेन विद लेबल्स, टॉप वर्ल्ड शामिल हैं।",
			"_3d_basemap_li4": "उपयोगकर्ता किसी भी आधार मानचित्र को एक क्लिक में देख सकता है।",
			"_3d_layers_header": "परतें",
			"_3d_layers_para1": "एक समूह लेयर्स उन सभी सुविधाओं का संग्रह है जो किसी श्रेणी में आती हैं। स्थान (स्थानों) और विशेष सुविधाओं की जानकारी का पता लगाने के लिए आप इसके संबंधित डेटा को देखने के लिए लेयर्स का चयन कर सकते हैं।",
			"_3d_layers_li1": "नागरिक पोर्टल के बाएं हाथ की ओर मेनू बार से लेयर्स पर क्लिक करें।",
			"_3d_layers_li2": "विजेट पर आप सूचीबद्ध सभी समूह लेयर्स श्रेणियों को देख और विस्तारित कर सकते हैं",
			"_3d_layers_li3": "लेयर्स पर क्लिक करके, उपयोगकर्ता लेयर्स की सूची देख सकते हैं जैसे: बिल्डिंग, डिवाइडर, इलेक्ट्रिक पोल, स्ट्रीट लाइट, ट्री आदि।",
			"_3d_layers_li4": "लेयर पैनल से उस पर क्लिक करके लेयर दिखाई देगा।",
			"_3d_drawTool_header": "ड्राइंग टूल",
			"_3d_drawTool_para1": "आप नागरिक पोर्टल के बाएं पैनल में मेनू से ड्राइंग टूल प्राप्त कर सकते हैं.",
			"_3d_drawTool_li1": "ड्रॉ मोड के प्रकार का चयन करें जिसे आप ड्राइंग टूल से उपयोग करना चाहते हैं।",
			"_3d_drawTool_li2": "विभिन्न प्रकार के ड्रा मोड उपलब्ध हैं जैसे कि बिंदु, पॉलीलाइन और बहुभुज",
			"_3d_drawTool_li3": "उदाहरण के लिए, जब आप लाइन स्ट्रिंग बटन पर क्लिक करते हैं, तो टूल लाइन ज्यामिति को सक्रिय करता है",
			"_3d_drawTool_li4": "मैप पर माउस पॉइंटर को मूव करें और मैप पर ग्राफिक / ज्योमेट्री जोड़ने के लिए क्लिक करें।",
			"_3d_drawTool_li5": "अब आप मानचित्र पर ग्राफिक / ज्यामिति देख सकते हैं, और इसे प्रिंट भी कर सकते हैं।",
			"_3d_drawTool_li6": "आप उपलब्ध विकल्प से स्पष्ट, पूर्ववत और फिर से कर सकते हैं",
			"_3d_drawTool_noteHeader": "नोट:",
			"_3d_drawTool_note": "कुछ ग्राफिक्स के लिए एक क्लिक या एक क्लिक और ड्रैग से अधिक की आवश्यकता हो सकती है।",
			"_3d_heritage_header": "हेरिटेज बिल्डिंग",
			"_3d_heritage_para1": "उपयोगकर्ता इंदौर शहर में मौजूद विरासत इमारतों की सूची देख सकते हैं।",
			"_3d_heritage_li1": "लेयर पैनल से वे जिस भी हेरिटेज बिल्डिंग को देखना चाहते हैं, उसे चालू / बंद कर सकते हैं",
			"_3d_heritage_li2": "ज़ूम टू फ़ीचर विशेष विरासत भवन में ज़ूम करेगा",
			"_3d_heritage_li3": "उपयोगकर्ता चयनित हेरिटेज बिल्डिंग के लिए बेस लेयर के रूप में देखने के लिए ड्रोन इमेज पर भी स्विच कर सकता है।",
			"_3d_lidar_header": "LiDAR",
			"_3d_lidar_para1": "विभाग के उपयोगकर्ता इंदौर शहर के डेटा को देख सकते हैं।",
			"_3d_lidar_li1": "मेनू से LiDAR पर क्लिक करें और यह उपयोगकर्ता को LiDAR डैशबोर्ड पर पुनर्निर्देशित करेगा।",
			"_3d_lidar_li2": "उपयोगकर्ता माप क्षेत्र उपकरण का उपयोग करके किसी भी इमारत की ऊंचाई को माप सकता है।",
			"_3d_lidar_li3": "उपयोगकर्ता दो बिंदुओं के बीच की दूरी को भी माप सकता है जो अधिक सटीक है।",
			"_3d_attrQuery_header": "गुण को स्वीकार करें",
			"_3d_attrQuery_para1": "विभाग उपयोगकर्ता सड़क और भवन परतों पर विशेषता क्वेरी कर सकते हैं",
			"_3d_attrQuery_li1": "मेनू से विशेषता क्वेरी का चयन करें",
			"_3d_attrQuery_li2": "ड्रॉप डाउन से लेयर का चयन करें",
			"_3d_attrQuery_li3": "ड्रॉप डाउन से फ़ील्ड चुनें",
			"_3d_attrQuery_li4": "तार्किक संचालक लागू करें",
			"_3d_attrQuery_li5": "ड्रॉप डाउन से मान का चयन करें",
			"_3d_issue_header": "रिपोर्ट किए गए मुद्दे",
			"_3d_issue_para1": "विभाग के उपयोगकर्ता किसी भी विभाग में रिपोर्ट किए जाने पर 3D में कोई भी समस्या देख सकते हैं",
			"_3d_issue_li1": "ड्रॉप डाउन से विभाग का चयन करें",
			"_3d_issue_li2": "उस समस्या का चयन करें जिसे आप देखना चाहते हैं",
			"_3d_issue_li3": "सबमिट पर क्लिक करें",
			"_3d_proximity_header": "निकटता विश्लेषण",
			"_3d_proximity_li1": "ड्रॉप डाउन से लेयर का चयन करें",
			"_3d_proximity_li2": "मानचित्र पर बहुभुज बनाएं",
			"_3d_proximity_li3": "उस बहुभुज में गिरने वाली इमारतों या सड़क को परिणाम टैब में प्रदर्शित किया जाएगा",
			"_3d_proximity_li4": "ज़ूम टू फ़ीचर पर क्लिक करने पर यह हाइलाइट और मैप पर ज़ूम हो जाएगा।",
			
		}
	};

	// set language according to type
	set_lang = function(language) {
		if (dictionary.hasOwnProperty(language)) {

			// $(".loader").fadeIn();

			$("[data-translate]").text(function() {
				var key = $(this).data("translate");
				if (dictionary.hasOwnProperty(language)) {
					if ($(this).is("input") || $(this).is("textarea")) {
						let value = dictionary[language][key];
						$(this).attr('placeholder', value)
					} else {
						let value = dictionary[language][key];
						$(this).text(value);
					}
				}
				// $(".loader").fadeOut();
			});
		}
	};

	/**
	 * Hindi language
	 */
	$("#pills-hindi-tab").click(function() {
		set_lang(hindi_lang);
		setCurrentLanguage(hindi_lang);
	});

	/**
	 * English language
	 */
	$("#pills-english-tab").click(function() {
		set_lang(eng_lang);
		setCurrentLanguage(eng_lang);
	});

	function setCurrentLanguage(language) {
		localStorage.setItem("current_language", language);
	}

	function configureLanguage() {

		var c_lang = localStorage.getItem("current_language");

		if (c_lang == null) {
			set_lang(eng_lang);
			setCurrentLanguage(eng_lang);
			$("#pills-tab #pills-hindi-tab").removeClass("active");
			$("#pills-tab #pills-english-tab").addClass("active");
		}

		if (c_lang == eng_lang) {
			$("#pills-tab #pills-hindi-tab").removeClass("active");
			$("#pills-tab #pills-english-tab").addClass("active");
		} else if (c_lang == hindi_lang) {
			$("#pills-tab #pills-english-tab").removeClass("active");
			$("#pills-tab #pills-hindi-tab").addClass("active");
		}
		set_lang(c_lang);
	}

	/**
	 * READY FUNCTION
	 */

	$(document).ready(function() {
		configureLanguage();
	});
});

